### ISSUE TITLE
Is it possible to fetch BODYSTRUCTURE with imap_tools ? 

### ISSUE THREAD

**Issue by SamirM-BE** [ikvk/imap_tools#100]
Hello,

For a project I need to fetch BODYSTRUCTURE, I don't if is it possible to do it using imap_tools, anyone knows if is it possible ? 

Thank you for you help

**Comment by ikvk** [comment]
Hello
```
from imap_tools import MailBox
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    mailbox.box # imaplib.IMAP4/IMAP4_SSL client instance
```

**Comment by ikvk** [comment]
May you tell for what?

**Comment by SamirM-BE** [comment]
Hello,

With a colleague we are developing a tool to delete old or unnecessary emails. This tool has an ecological purpose.

We want to be able to detect email attachments without having to download the email. The solution we found is to parse the body structure of the email, it contains whether any attachments are present and the name of those attachments.

Some similar problems : 
https://stackoverflow.com/questions/31335415/parsing-imap-email-bodystructure-for-attachment-names
https://stackoverflow.com/questions/13847821/python-and-imaplib-obtain-attachment-names-or-body-without-downloading-full-ema

**Comment by ikvk** [comment]
I will read about it.

**Comment by ikvk** [comment]
Would you like to implement it?
like this:
```
for msg in mailbox.fetch(with_struct=True):
    msg.structure # parsed decoded 
```

**Comment by ikvk** [comment]
Anyone, feel free to implement it.

**Comment by maxie112** [comment]
How to implement?

**Comment by ikvk** [comment]
> 
> 
> How to implement?

Simple:
1. Read RFC
2. Write universal robust parser
3. Write tests
4. Do pull request

**Comment by ikvk** [comment]
Example for get BODYSTRUCTURE
```
uid_list = mailbox.uids()
fetch_result = mailbox.client.uid('fetch', uid_list[0], 'BODYSTRUCTURE')
print(fetch_result)
```
('OK', [b'1 (UID 1 BODYSTRUCTURE (("text" "html" ("charset" "utf-8") NIL NIL "base64" 2456 32 NIL NIL NIL NIL)("image" "jpeg" NIL "<collector.jpg@parts.yandex.ru>" NIL "base64" 7274 NIL ("attachment" ("filename" "collector.jpg")) NIL NIL) "related" ("boundary" "===============1696383123==") NIL NIL NIL))'])
