### ISSUE TITLE
Message files (.msg for example) joined to an email are not in attachements

### ISSUE THREAD

**Issue by ilep** [ikvk/imap_tools#102]
I have had the case of an email with a .msg file joined to the mail 

In this case, values of :
**(part.get_content_type(), part.get_content_maintype(), part.get('Content-ID'), part.get_filename())**
are respectively 
**('message/rfc822', 'message', None, None)**

where part is the variable used in these function
https://github.com/ikvk/imap_tools/blob/master/imap_tools/message.py#L221

Thus, in this case, the folllowing condition is equal to True
https://github.com/ikvk/imap_tools/blob/master/imap_tools/message.py#L230

and the script goes to next iteration of the for loop without adding the .msg attachement to results list 
(results.append(MailAttachment(part)))

regards, 

Ivan

**Comment by ikvk** [comment]
May you show me email src? cutted if need.

**Comment by ilep** [comment]
Thank you for your response.  
Sending raw email to you is not possible. What do you mean by cutted email src? 
I have an object imap_tools.message.MailMessage
How do you go from this object to what you needfor debug

Regards
ps: if you want to easily create a problem test : the email that caused problem was a simple mail with a .msg file attached (windows outlook mail stored on filesystem)

**Comment by ikvk** [comment]
I need this info:

...
------==--bound.887287.myt5-262fb1897c00.qloud-c.yandex.net
Content-Disposition: attachment;
	filename="yandex_email.eml"
Content-Transfer-Encoding: base64
Content-Type: message/rfc822;
	name="yandex_email.eml"
...

**Comment by ikvk** [comment]
This block needs for write new test

**Comment by ikvk** [comment]
*I do not need other parts

**Comment by ikvk** [comment]
Check it https://github.com/ikvk/imap_tools/releases/tag/v0.39.0
