### ISSUE TITLE
filter datetime

### ISSUE THREAD

**Issue by Bastilla123** [ikvk/imap_tools#104]
Hello,

i want to filter mailbox.fetch(AND(date=obj.date)) and obj.date is a datetime object but i get a exception that a date object is ecpected. In your description stands: msg.date         # datetime.datetime: 1900-1-1 for unparsed, may be naive or with tzinfo

Why your filter expects a date object? I need a solution with datetime object.

Have anyone a idea how i can change that?

Regards

**Comment by ikvk** [comment]
Hi, imap can filter by date  only.

**Comment by ikvk** [comment]
https://tools.ietf.org/html/rfc3501#section-6.4.4
