### ISSUE TITLE
Flaged as Seen on fetch

### ISSUE THREAD

**Issue by Bastilla123** [ikvk/imap_tools#106]
Hello,

i write me a email and in Thunderbird ist email als unseen declared. Is shown strong. Now i fetch email:

 emailentrys = [(msg.uid, msg.subject, msg.from_, msg.to, msg.cc, msg.bcc, msg.reply_to, msg.date, msg.text,
                        msg.html, msg.flags, msg.headers) for msg in connection.fetch()]

and then all emails have the flag "SEEN". Why?

**Comment by ikvk** [comment]
BaseMailBox.fetch
    mark_seen = True, mark emails as seen on fetch

Next time try to read lib docs - just one page.
