### ISSUE TITLE
Uncertainties regarding Mailbox.fetch, miss_defect=False

### ISSUE THREAD

**Issue by jonaswinkler** [ikvk/imap_tools#107]
Hello!

This isn't really a bug or feature request, and much rather an inquiry for some advice, so I might as well close this immediately.

On the method `Mailbox.fetch`, there's an optional kwarg `miss_defect` that's set to `True` by default.

* Some users of my application reported that certain mails don't get picked up, but when they send them again using a different client, they do get picked up. (Well, not with all clients.)
* In one specific case that I've examined more closely, I've seen some mails with an `InvalidMultipartContentTransferEncodingDefect` defect.

I wonder if it's okay to just set `miss_defect=False`, or if I have to then take extra care when working with the parsed mail data. We're using various data from the parsed mails, such as from_values, from_, subject, attachments, attachment.content_disposition, att.payload, and att.filename.

* Are there any drawbacks to passing `miss_defect=False`? Especially:
* Should I expect any of the fields above to contain invalid data, `None`, or no data even if the mail has that specific attribute?

**Comment by ikvk** [comment]
Greeting.

miss_defect arg introduced for work with emails more reliable.
In fact email with defects are invalid, and error may occur in any place of work with that message.

As a result we collects unprocessed invalid messages in mailbox.
You can process it separately, and inform sender about bad emails.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.40.0
