### ISSUE TITLE
Search criteria for date not working

### ISSUE THREAD

**Issue by f1ynn-zhan9** [ikvk/imap_tools#108]
![image](https://user-images.githubusercontent.com/80672942/111124360-66786480-85ab-11eb-8606-42a3762c4fe5.png)

HELP!!!
As you can see in the picture, search criteria for date does not work for me.
Did I use it in wrong way? Or the email server does not support date limitation?

**Comment by f1ynn-zhan9** [comment]
![image](https://user-images.githubusercontent.com/80672942/111130747-895a4700-85b2-11eb-90c1-a4d4efd3a023.png)

By this way, it work!!!
When it contains "()", it does not work. Is it a flaw?

**Comment by ikvk** [comment]
Checked with AND(date_gte=datetime.date(2020, 1, 1))
YANDEX - works
MAIL_RU - [CANNOT] Unsupported search criterion: SINCE 1-JAN-2020
GOOGLE - works

so, this is "feature" of your server
