### ISSUE TITLE
mail.ru serch mail by subject

### ISSUE THREAD

**Issue by InstDev** [ikvk/imap_tools#113]
`mailbox.fetch(A(subject='any_subject'))`

rise error: imap_tools.errors.MailboxSearchError: Response status "OK" expected, but "NO" received. Data: [b'[CANNOT] Unsupported search criterion: SUBJECT "ANY_SUBJECT"']

p.s. How search mails by subjects?

**Comment by InstDev** [comment]
ok, mail.ru not support search criterias. one way - make it on client side
I'm right?

**Comment by ikvk** [comment]
Heh, seems it is. It supports only few simple params. This is fiasco of mail.ru :D
