### ISSUE TITLE
reply to a message thread with this tool

### ISSUE THREAD

**Issue by Allaye** [ikvk/imap_tools#114]
Hi, thanks for this tool, i was thinking if there is any way i can reply to a message thread with this tool?

**Comment by ikvk** [comment]
Glad you like. This lib aims to imap, not smtp, so - no. But I think it will be easy with imap_tools.

**Comment by ikvk** [comment]
May be you mean build a thread at client side. I'm not against it, but it is not interesting for me now, and I have no much time. Here is the conversation about it: https://github.com/ikvk/imap_tools/issues/66 Of course you can implement it for imap_tools.

**Comment by Allaye** [comment]
Not a bad idea, let see what i can do about it.

**Comment by ikvk** [comment]
There is even a branch already: imp_treader
