### ISSUE TITLE
Typing refactor

### ISSUE THREAD

**Issue by edkedk99** [ikvk/imap_tools#115]
Would the developer consider a pull request improving typing information?

For example, as mentioned in link below, fetch method in class BaseMailBox should return `Iterator[MailMessage]` or better `Generator[MailMessage, None, None]` and not `'iter` and in other places `[str]` should be `List[str]`.

Pyright showed me some errors because it misunderstood some typings because the way it is, type checker doesn't know fetch method iterate thru MailMessage. 

https://github.com/ikvk/imap_tools/blob/84dbf2b612bc7fc2fdf6e1e77ddb6058160225fb/imap_tools/mailbox.py#L78-L80

**Comment by ikvk** [comment]
Simple type notes are saved for backward compatibility with old python versions. 
Current type annotations are enough for IDEs and peoples. Also it is simple, nice to read and has no dependencies.

Of course, I know about typing module. 
May be you know how to fix "iter" annotation without typing module?

**Comment by edkedk99** [comment]
I understand your point. Since I am new to python, I have never used older versions. But for my sole use case, if you don't annotate the return fetch function, my type checker infer it is in fact a Generator of MailMessage objects then when iterate thru the messages, it recognizes all methods and attributes correctly. 

I don't know the effects of this change for other type checkers and python versions.

Anyway, this packages has been very useful for me, thank you very much for your effort on this.

**Comment by ikvk** [comment]
May be much later I will do it, it depend on typing module

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.47.0
