### ISSUE TITLE
SSL is not verified by default

### ISSUE THREAD

**Issue by ziima** [ikvk/imap_tools#117]
Lately we noticed that SSL connections created by python standard library doesn't verify server by default. Sadly, it's not stressed enough in documentation, although it is recommended to use `create_default_context`, see https://docs.python.org/3.8/library/ssl.html#security-considerations.

I suggest following changes to improve default security:
 * If `ssl_context` is not provided, create it using `create_default_context`.
 * If `certfile` is provided, load certificate using `SSLContext.load_cert_chain`.
 * Deprecate `certfile` and `keyfile` arguments in `MailBox`.
 * Raise exception if both `certfile`/`keyfile` and `ssl_context` are used.

**Comment by ikvk** [comment]
This lib aims to provide IMAP tools.
Other things like connection or save message to file are assigned to the python libs, if they can do it well.
Here is example of TLS connection:
https://github.com/ikvk/imap_tools/blob/master/examples/tls.py
Save message to file:
https://github.com/ikvk/imap_tools/blob/master/examples/email_to_file.py

If you have another good examples, I will add it to examples path.
And it is good idea to do link on secure connection into readme.

**Comment by ikvk** [comment]
May you provide example of your secure connection ?

**Comment by ziima** [comment]
I think it should be created as
```python
import ssl

ssl_context = ssl.create_default_context()
if certfile:
    ssl_context.load_cert_chain(certfile, keyfile)
```

**Comment by ikvk** [comment]
Is readme better now?

**Comment by ziima** [comment]
I still think, it would be better to implement it, but readme is good enough.
