### ISSUE TITLE
Can't get the latest email from a specific email folder instead return an old email

### ISSUE THREAD

**Issue by shenxianpeng** [ikvk/imap_tools#118]
Hi there,

I have a problem that I can't get the latest mail. here is my debug message:

![image](https://user-images.githubusercontent.com/3353385/115816602-b6104280-a42b-11eb-92c7-55fb0ace205b.png)

And here is my email in the initial_folder 

![image](https://user-images.githubusercontent.com/3353385/115816705-e9eb6800-a42b-11eb-810e-228a7f80c945.png)

I expect it will return the latest date email which is 4/18/2021, but it always returns 2021-03-28. 

I changed the query from  `query = AND(all=True)` from `query = AND(subject="Lab Systems Report - Product Family")`, also the same result, it can not return the latest date's email.

The rest of the code:

```python
def connect_outlook():
    mailbox = MailBox('outlook.office365.com')
    mailbox = mailbox.login(email_address, email_password, initial_folder=email_folder)
    return mailbox

def convert_email_to_html():
    query = AND(all=True)
    # query = AND(subject=email_subject)
    for msg in outlook.fetch(criteria=query):
    last_msg_date = msg.date
    ...
    ...

outlook = connect_outlook()
convert_email_to_html()
outlook.logout()
````

Do I need to make some settings on outlook? or something else. looking forward to your suggestion. thanks a lot.

**Comment by shenxianpeng** [comment]
I know the workaround. there is a space in my `initial_folder`, after removing the space(change `VM Report` to `VM_Report`), I can get the latest email now. but it looks like a bug or an enhancement.

**Comment by ikvk** [comment]
Hi. Behaviour with spaces is a feature of you server. I tried with 'zz|и я' folder at yandex - works.
