### ISSUE TITLE
Mail Headers are interpreted case sensitive

### ISSUE THREAD

**Issue by mrh1997** [ikvk/imap_tools#119]
Accourding to [this comment](https://stackoverflow.com/a/6143644/4330657) Mail Headers should **not** be handled case sensitive. But The current version of ``imap_tools`` interprets mail headers case sensitive.

I.e. the Office365 IMAP bridge returns mail headers lower case (instead of mixes case like our last mail server (zimbra)). According to this link this is perfectly valid. But when using the ``headers`` attribute of a message to access a specific attribute this mail fail:

```python
      print(msg.headers["Content-Type"])    # will fail on Office365
      print(msg.headers["content-type"])     # will fail on zimbra
```

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.37.0
