### ISSUE TITLE
[Feature Request] Ability to filter by datetime instead of just date

### ISSUE THREAD

**Issue by caffeinatedMike** [ikvk/imap_tools#12]
This is a great project that makes integrating imap capabilities so much simpler.

I was wondering if you'd be willing to consider adding the ability to filter by datetime instead of just date. This could be implemented by utilizing [RCF2822](https://tools.ietf.org/html/rfc2822#page-7)'s `time` entry that provides GWT hours, minutes, seconds, and timezone offset.

**Use-case for this proposed functionality:**
- Objective - Email cronjob that runs every 10 minutes to log all new emails for communication record-keeping and statistical analysis.
```
from imap_tools import MailBox, Q, AND
from datetime import datetime, timedelta

mailbox = MailBox('imap.mail.com')
mailbox.login('test@mail.com', 'password', initial_folder='INBOX')

# Using system received time
mailbox.fetch(Q(AND(new=True, datetime_gte=datetime.now() - timedelta(minutes=10))))
# And using sent date
mailbox.fetch(Q(AND(new=True, sent_datetime_gte=datetime.now() - timedelta(minutes=10))))

mailbox.logout()
```

**Comment by ikvk** [comment]
Thanks, Mike.
It is not possible: 
RFC 3501:
  SINCE <date>
     Messages whose internal date (**disregarding time and timezone**)
     is within or later than the specified date.

And also, using Q and AND together in your code is redundant, Q is just an alias for AND.

*great projects like stars ;-)
