### ISSUE TITLE
add an option to authenticate instead of login

### ISSUE THREAD

**Issue by galitzhaksf** [ikvk/imap_tools#120]
Hi, could you please add authenticate method in addition to the login method? this is the code that should be added to mailbox class:

    def authenticate(self, mechanism: str, authobject: str, initial_folder: str or None = 'INBOX'):
        login_result = self.box.authenticate(mechanism, authobject)
        check_command_status(login_result, MailboxLoginError)
        self.folder = self.folder_manager_class(self)
        if initial_folder is not None:
            self.folder.set(initial_folder)
        self.login_result = login_result
        return self  # return self in favor of context manager

thanks!

**Comment by ikvk** [comment]
Hi, may you provide usage example?

**Comment by galitzhaksf** [comment]
> Hi, may you provide usage example?

sure, this how I use it to connect with oauth2:
```
    mailbox_address = "..."
    access_token = "..."
    auth_string = f"user={mailbox_address}\1auth=Bearer {access_token}\1\1"
    auth_method = lambda get_auth_string: auth_string
    mechanism = "XOAUTH2"

    with YahooMailbox(YAHOO_IMAP_SERVER_NAME).authenticate(mechanism, auth_method) as mailbox:
        ...
```

**Comment by ikvk** [comment]
What about https://github.com/ikvk/imap_tools/blob/master/imap_tools/mailbox.py#L282

**Comment by ikvk** [comment]
*And in examples now: https://github.com/ikvk/imap_tools/blob/master/examples/oauth2.py
