### ISSUE TITLE
mailbox.fetch brokes with mutated vowel

### ISSUE THREAD

**Issue by ThKue** [ikvk/imap_tools#121]
hi together,
i have a problem with the fetch function.

for example, when the incoming subject is like "tttt xx xx-xx2 (07:06): (XXX xxx xx) Däsxxxx xxx"

the fetch function only get the following subject text:  tttt xx xx-xx2 (07:06): (XXX xxx xx). 
can i set a charset for the subject? i think the mutated vowels are the problem.

for msg in mailbox.fetch(AND(subject='tttt', from_='xxx@xxxx.de'), mark_seen=False, reverse=True, limit=1):

thanks alot

**Comment by ThKue** [comment]
here for example, the origin messages includes the Bö in the subject, and is encoded with UTF-8

do you need this information?

tttt xx xx-xx2 (07:06): (XXX xxx xx) Böxxxx xxx

tttt xx xx-xx2 (07:06): (XXX xxx xx)=?UTF-8?B?QsO2c2VsZXI=?=

**Comment by ikvk** [comment]
seems yes

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.41.0
Thanks!
