### ISSUE TITLE
Fetch wrong uid

### ISSUE THREAD

**Issue by Bastilla123** [ikvk/imap_tools#122]
Hello,

i have:

[(msg.uid, msg.subject, msg.from_, msg.to, msg.cc, msg.bcc, msg.reply_to, msg.date, msg.text,
                    msg.html, msg.flags, msg.headers) for msg in
                   mailbox.fetch(A(uid=U(239, '*')))]

with this i get everytime the last e-mail with uid=238 but with criteria A(uid=U(239, '*')) i expect a empty list.

Regards

**Comment by ikvk** [comment]
Try to read UidRange doc string, then rfc3501 if you need proofs. This is normal.
