### ISSUE TITLE
Cant append a custom flag/keyword to a message

### ISSUE THREAD

**Issue by tiuub** [ikvk/imap_tools#123]
Hello,

I want to add an custom flag/keyword to my message. Therefore I have tried to use `mailbox.append(...)` and `mailbox.flag(...)`, but both of them only returns `Error in IMAP command APPEND: Invalid system flag ...`.

I know this library is based on imaplib. In imaplib it is possible to add an custom flag/keyword with `imap.store(uid, '+FLAGS', '<flag>')`. So is there any other method in this library to add a custom flag/keyword to my messages?

Kind regards
tiuub

**Comment by ikvk** [comment]
Hi. I think this is email server restriction. Can you successfully add custom flag by imaplib?
In my case this code works but tag not adding:
```
for i in mailbox.fetch(A(subject='eml sub tree'), limit=1):
    print(i.date, i.subject)
    uids.append(i.uid)
mailbox.flag(uids, ['tag1'], True)
```

**Comment by Endyl** [comment]
I have just now run into this problem as well.

I think the problem is that [on this line](https://github.com/ikvk/imap_tools/blob/66f6e5ca300ca467003b291248494a6907a8253d/imap_tools/mailbox.py#L176) `'\\'` is prepended to the flag names which is only supposed to be there for "system" flags (eg. \SEEN).

By running this code:
```python
mailbox.box.uid('STORE', uid, '+FLAGS', '(_MyFlag)')
```
I managed to add the flag.

**Comment by ikvk** [comment]
I will check it

**Comment by MadJlzz** [comment]
Exactly the same issue I faced and thanks to @Endyl, I have a working solution. Context was to append "labels" to emails from Gmail:
```python
mailbox.flag(uid_list, ["X-GM-LABELS"], label)
```
doesn't work with:
```
Traceback (most recent call last):
  File "/home/madjlzz/Projects/ngt/ngt-datamail/manual_run.py", line 15, in <module>
    core.datamail_extraction(debug=True)
  File "/home/madjlzz/Projects/ngt/ngt-datamail/datamail/core.py", line 79, in datamail_extraction
    imap_conn.flag(list_uid_processed, "X-GM-LABELS", "Test")
  File "/home/madjlzz/Projects/ngt/ngt-datamail/library/__init__.py", line 40, in flag
    self.mailbox.flag(uid_list, [flag_name], flag_value)
  File "/home/madjlzz/Projects/ngt/ngt-datamail/venv/lib/python3.7/site-packages/imap_tools/mailbox.py", line 173, in flag
    '({})'.format(' '.join(('\\' + i for i in flag_set))))
  File "/usr/lib/python3.7/imaplib.py", line 879, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: UID command error: BAD [b'Invalid Arguments: Unable to parse flag \\X-GM-LABELS']
```
as for:
```python
mailbox.box.uid("STORE", uid, 'X-GM-LABELS', label)
```
works like a charm.

**Comment by ikvk** [comment]
Check it https://github.com/ikvk/imap_tools/releases/tag/v0.42.0

Thanks, @tiuub !

**Comment by MattSidney** [comment]
> Exactly the same issue I faced and thanks to @Endyl, I have a working solution. Context was to append "labels" to emails from Gmail:
> 
> ```python
> mailbox.flag(uid_list, ["X-GM-LABELS"], label)
> ```
> 
> doesn't work with:
> 
> ```
> Traceback (most recent call last):
>   File "/home/madjlzz/Projects/ngt/ngt-datamail/manual_run.py", line 15, in <module>
>     core.datamail_extraction(debug=True)
>   File "/home/madjlzz/Projects/ngt/ngt-datamail/datamail/core.py", line 79, in datamail_extraction
>     imap_conn.flag(list_uid_processed, "X-GM-LABELS", "Test")
>   File "/home/madjlzz/Projects/ngt/ngt-datamail/library/__init__.py", line 40, in flag
>     self.mailbox.flag(uid_list, [flag_name], flag_value)
>   File "/home/madjlzz/Projects/ngt/ngt-datamail/venv/lib/python3.7/site-packages/imap_tools/mailbox.py", line 173, in flag
>     '({})'.format(' '.join(('\\' + i for i in flag_set))))
>   File "/usr/lib/python3.7/imaplib.py", line 879, in uid
>     typ, dat = self._simple_command(name, command, *args)
>   File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
>     return self._command_complete(name, self._command(name, *args))
>   File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
>     raise self.error('%s command error: %s %s' % (name, typ, data))
> imaplib.error: UID command error: BAD [b'Invalid Arguments: Unable to parse flag \\X-GM-LABELS']
> ```
> 
> as for:
> 
> ```python
> mailbox.box.uid("STORE", uid, 'X-GM-LABELS', label)
> ```
> 
> works like a charm.

was mailbox.box.uid and old method? 
Trying to understand how you were using this to set a label.
