### ISSUE TITLE
[Feature Request] add MailMessage.dump() -> email.Message method and MailMessage.import(<email.Message>)

### ISSUE THREAD

**Issue by repodiac** [ikvk/imap_tools#124]
Hi @ikvk ,

I really like and appreciate your library, however what is really missing is the possibility to change/modify a MailMessage object and generate/clone a new one - so far it is basically "immutable" (as much as Python allows for it ;-) and not directly "reproducible" via the available methods.

It took me quite some time to fiddle with and "reverse-engineer" a solution which works for my use case: I simply needed to change the subject of an existing message, i.e. something like "any subject" should be modified to "[my own subject extension] any subject" without changing anything else of the message.

Here is my code:
```
import email
from imap_tools import MailBox

with MailBox(host=mail_server, ssl_context=ssl_context).login(login, passwd) as mailbox:
    for msg in mailbox.fetch():
        altered_msg = email.message_from_bytes(msg.obj.as_bytes())
        altered_msg.replace_header('Subject', '[my own subject extension] ' + msg.subject)
        mailbox.append(altered_msg.as_bytes())

<... here code to delete the original messages afterwards, without the subject modification...>
```

I suggest a more generic method to **dump** or **export** the MailMessage to e.g. the Message object format of the standard `email` library:
* This would allow more options to change/extend the existing message
* In addition, add another method to **generate** a new copy based on the dump/export or
*  **import** this modified version back to the MailMessage object format

Currently, importing is only possible via `from_bytes(...)` method which is counter-intuitive or unpleasant to use and needs a byte version of the message (which you cannot get directly from the methods at hand).

**Comment by ikvk** [comment]
1. email.message.EmailMessage.as_string and email.message.EmailMessage.as_bytes have well docs.
This methods are really not simple, but there are exists and do it work well.
Their complexity is due to the difference in platforms.
I don't see the need/possibility to implement the method MailMessage.dump

2. MailMessage.from_bytes counter-intuitive - why? It's very natural.

3. MailMessage.import(<email.Message>) will not be added. 
- This lib aims to IMAP. 
- Сode of import will be far from trivial.
- Email messages are not intended for editing. (but it is)

Anyway, if you have any code suggestions, I will see it.
I could be wrong, as all.

**Comment by repodiac** [comment]
Rehi,

First of all: It is fine if you do not feel like it :-) It is simply a feature request (or proposal)... so relax ;-)

However, I still think this is a valid inquiry - I tried to motivate my use case and need also with a code snippet (see above). I am using your library for a tool to filter mails and similar to SPAM filters which add [SPAM] ..." to each subject they have recognized as "spam", I would like to modify those kind of mails, as well.

In the current state of the library, this is doable as I figured out with my code snippet from above. Nonetheless, I would love to see a more simple method and easier to approach. I think there are also other cases, where mails need to be modified or (re)created from other data but still share stuff with (an) existing message(s). Don't you think so?

Importing or creating a message from a ``from_bytes(...)`` method and not knowing exactly (intuitively) how I can get such a "byte version" beforehand is what I call "counter-intuitive" and unpleasant :-)

If I had the time I could come in with a PR but until then I have raised my hand and made this proposal.

**Comment by ikvk** [comment]
If your code example works, I think it is simple and short enough.
It is really good example for community, I will add it.

Email modification is not most popular operations - it may be not so intuitive.

I have tried to add public attribute - MailMessage.orig_bytes (raw_message_data)
But it have increased memory consumption: ~10%
So, not now.
