### ISSUE TITLE
fetch returns incorrect found set

### ISSUE THREAD

**Issue by Bobspadger** [ikvk/imap_tools#125]
Hi Good work on the library so far - been enjoying it , so thanks for the hard work.

I have an issue on getting the correct emails returned from the mailserver. For reference I have the same issue if I use my development IMAP server (dovecot) or our live works mailserver (kerio) but only with your library.

For reference - using the easyimap library https://github.com/keitaoouchi/easyimap my query works and returns the correct emails.

## EasyImap Example:

```python
import easyimap

mailserver = easyimap.connect(
    host=settings.email.host,
    user=settings.email.user,
    password=settings.email.password,
    mailbox="INBOX.websalesin_duplicate",
)

test_emails = mailserver.listup(limit=10, criterion='SUBJECT "Sold, dispatch now"')
for em in test_emails:
    print(em)
```

<img width="2302" alt="Screenshot 2021-06-03 at 13 11 48" src="https://user-images.githubusercontent.com/1614970/120642807-426f4580-c46d-11eb-8224-4061f07e708d.png">

## Imap-tools Example

```python
with MailBox(host=settings.email.host, port=settings.email.port).login(settings.email.user,
                                                                       settings.email.password) as mailbox:
    for rule_name, rules in settings.mail_rules.items():
        log.info(rule_name)
        mailbox_in = 'INBOX.websalesin_duplicate'
        mailbox.folder.set(mailbox_in)
        search = AND(**rules.filter) # Effectively subject=Sold, dispatch now
        emails = mailbox.fetch(search, limit=10)
        # emails = mailbox.search(search)
        for email in emails:
            print(email)
```
This returns emails such as;

```
TO: ('ebay@xxx.co.uk',) FROM: ebay@ebay.co.uk SUBJECT: Your eBay listing is confirmed: Alto TX210 Active (Neuf)
TO: ('ebay@xxx.co.uk',) FROM: ebay@ebay.co.uk SUBJECT: Your eBay listing is confirmed: Fishman PRF-MS7-TA2 Fluence Tosin Abasi 7-String Moderno Humbucker Set (Nuovo)
TO: ('ebay@xxx.co.uk',) FROM: ebay@ebay.co.uk SUBJECT: eBay fixed price listing end: Ernie Ball 8-String Slinky Juego Cuerdas Guitarra Eléctrica, 10-74 Gauge (Nuevo) (xxx)
TO: ('alex@xxx.co.uk', 'sales.support@xxx.co.uk') FROM: automation@xxx.co.uk SUBJECT: xxx Backorders Feed
```
I've tried combining this with `from_=` etc but I just get incorrect emails back.

Are you able to shed any light on where this may be going wrong - I've tried tracing the code through and can't see anything obvious.

Thanks in advance.

**Comment by Bobspadger** [comment]
Jus to add to this - following through the code (from easyimap and imap-tools) the only real difference I can see is that easyimap calls `fetch` on the mailserver via pythons Imaplib, but this library calls the `search` via imaplib.

I'm not too up on the difference in these two commands when it comes to the lower level interface with an imapserver. 

Hope this helps.

**Comment by ikvk** [comment]
Hi, here is my check results of mailbox.fetch(A(subject='Sold, dispatch now')):
YANDEX works
GOOGLE works
MAIL_RU Response status "OK" expected, but "NO" received. Data: [b'[CANNOT] Unsupported search criterion: SUBJECT "SOLD, DISPATCH NOW"']
ZIMBRA works
YAHOO works

So, seems lib works good.

You can check is all symbols are really identical, for example:
'Sold, dispatch now ого'.encode()
b'Sold, dispatch now \xd0\xbe\xd0\xb3\xd0\xbe'

**Comment by ikvk** [comment]
I have checked "\r\n" in subject case - works too. 
May be charset arg? I have no more ideas.

**Comment by Bobspadger** [comment]
Very odd then, as both libraries call the underlying Python IMAPlib. Just different parts of the code.

I've confirmed the issue is present on multiple mail servers, I'll try the encoding / charset, but I have tried `utf-8` and the default `us-ascii`

Seems odd the mailserver will return the correct lists using easyimap (again, just a wrapper around imaplib!) I'll keep digging

Thanks for looking, I'll update this with what I find

**Comment by ikvk** [comment]
You example is
search = AND(**rules.filter) # Effectively subject=Sold, dispatch now
Have you checked out a clean example?  like:
mailbox.fetch(A(subject='Sold, dispatch now'))

**Comment by Bobspadger** [comment]
> You example is
> search = AND(**rules.filter) # Effectively subject=Sold, dispatch now
> Have you checked out a clean example? like:
> mailbox.fetch(A(subject='Sold, dispatch now'))

Hi

Yes, same results - random emails.

It appears it doesn't matter what I use as a query - I do not get back emails that do not match.

Example:

```
'SUBJECT "korg backorder"'
```

Returns ebay emails, emails from me etc etc.

I'm using this as my test mail server

https://github.com/antespi/docker-imap-devel

But again, the queries fail on our live server (kerio mailserver)

**Comment by ikvk** [comment]
imap_tools let set bytes at search criterias, have you try it?

**Comment by Bobspadger** [comment]
> imap_tools let set bytes at search criterias, have you try it?

yes, I had already tried that :(

**Comment by ikvk** [comment]
Do you know some free kerio mail servise ?

**Comment by Bobspadger** [comment]
> Do you know some free kerio mail servise ?
sadly no.

However, I get the same results on the dovecot in docker development system (I linked to it above)

**Comment by ikvk** [comment]
Let me know if you get some news
