### ISSUE TITLE
Socks5 proxy support of imap_tools.

### ISSUE THREAD

**Issue by hongyi-zhao** [ikvk/imap_tools#127]
On Ubuntu 20.04, I want to know how can I use imap_tools to access my Gmail account through a local socks5 proxy listening on `127.0.0.1:18888`. I tried [this example](https://github.com/ikvk/imap_tools/blob/master/examples/pysocks_proxy.py) with python 3.8/3.9, but all failed.

Any hints will be highly appreciated.

Regards,
HY

**Comment by ikvk** [comment]
I am not support/use this example. People said it works
