### ISSUE TITLE
Multi threaded access to mailbox not grab right emails

### ISSUE THREAD

**Issue by CheemaOTB** [ikvk/imap_tools#131]
Okay so I have a threaded script that finds the email corresponding to the catchall used but it doesn't seem to grab the email for the first thread but the second thread works. How would I properly grab the email that is being sent to the specific catchall in the thread? Here is the imap code that I am using
```python 
with MailBox('imap.gmail.com').login(gmailEmail, gmailPassword, 'INBOX') as mailbox:
    for msg in mailbox.fetch(AND(to=CatchallEmail)):
        body = msg.text or msg.html
        print(body)
```

**Comment by ikvk** [comment]
I think it depends on your email server, I do not know how multiple simultaneous fetching may affects on results. May be it is there in RFC?

**Comment by ikvk** [comment]
Is it behaviour the same on other servers?

**Comment by CheemaOTB** [comment]
> Is it behaviour the same on other servers?

Yes, I made my friend test he had the same issue. What I have noticed is that it grabs the same email for every thread. Is there a better way to grab the email that is being sent to the catchall for the specific thread because it grabs the same email for each thread?

**Comment by ikvk** [comment]
1. What is use case for multi threaded access to email from 1 host?
2. How are you split access to threads: thread/process/aio, may you provide example ?
3. All sourses are opened, you can start investigation.

**Comment by ikvk** [comment]
I understand what you want.
You want to use email server as synchronization mechanism.
I think this is impossible and also is bad idea.
Just syncronize you threads in separate place.
