### ISSUE TITLE
Moving message destroys iteration over messages

### ISSUE THREAD

**Issue by Yannik** [ikvk/imap_tools#133]
Hi,

moving a message while iterating over all messages like this
```
for msg in mailbox.fetch():
    mailbox.move(msg.uid, 'Processed')

```

results in the following exception during the second iteration (second message)
```
Traceback (most recent call last):
  File "imap-to-fax.py", line 26, in <module>
    for msg in mailbox.fetch():
  File "/usr/local/lib/python3.7/dist-packages/imap_tools/mailbox.py", line 105, in fetch
    for fetch_item in (self._fetch_in_bulk if bulk else self._fetch_by_one)(nums, message_parts, reverse):  # noqa
  File "/usr/local/lib/python3.7/dist-packages/imap_tools/mailbox.py", line 68, in _fetch_by_one
    fetch_result = self.box.fetch(message_num, message_parts)
  File "/usr/lib/python3.7/imaplib.py", line 534, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))

```

**Comment by ikvk** [comment]
msg.uid are changing after moving, so this is normal.

Use fetch generator or uid set as 1st arg:
`mailbox.move(mailbox.fetch(), 'Processed')`

I will fix docs

**Comment by Yannik** [comment]
@ikvk I only want to move select messages, to using the uid set is not possible. Can you give a example for the generator?

**Comment by Yannik** [comment]
My current code (simplified):

```
for msg in mailbox.fetch():
    if msg.subject.endswidth("Fax"):
        mailbox.move(msg.uid, 'Processed')
```

**Comment by ikvk** [comment]
There is a fetch() generator instance in my first message here.

**Comment by Yannik** [comment]
Which message? 

` mailbox.move(mailbox.fetch(), 'Processed')` does move all messages, doesn't it? I only need to move specific messages.

**Comment by ikvk** [comment]
Collects needed uids and call move once

**Comment by Yannik** [comment]
@ikvk Unfortunately, that is not possible because I need to move some messages to folder x and some messages to folder y.

**Comment by Yannik** [comment]
@ikvk What do you recommend doing about this?

**Comment by ikvk** [comment]
Do copy instead move in fetch iterations, and delete unneded copies after iteration by one delete action
