### ISSUE TITLE
strip/remove attachments from a message

### ISSUE THREAD

**Issue by va3dxv** [ikvk/imap_tools#134]
Hello I'm wondering if this is something you might be interested in implementing?

I'm using your library for my project and I'd like to be able to strip a message of its attachments (after I extract them and do something with them), then save the .eml file to disk.

I can extract my attachments and write them plus the .eml file to disk no problem (with attachments and all), but I've been fighting for hours with imaplib to get it to strip attachments from the .eml first... my python skills and imap knowledge aren't there. I thought having it in a library already used would be a bit nicer.

I found [another project that does something similar](https://github.com/guido4000/Email-Attachment-Remover/blob/master/email_attachment_remover.py) but they're filtering by size first

Regardless thank you for an already useful tool.

**Comment by ikvk** [comment]
This is beyond the scope of the library
