### ISSUE TITLE
Request is throttled. Suggested Backoff Time: N milliseconds. How to handle MailboxFetchError? Or option to wait for the Backoff Time and continue.

### ISSUE THREAD

**Issue by HenkVanHoek** [ikvk/imap_tools#135]
Fetch e-mails from an outlook online(OO) mailserver is throttled by OO.  

Is there an option possible to allow the fetch to wait the given backup time in de received data from OO.

Example of the received throttle error:
imap_tools.errors.MailboxFetchError: Response status "OK" expected, but "NO" received. Data: [b'Request is throttled. Suggested Backoff Time: 299910 milliseconds']

**Comment by HenkVanHoek** [comment]
At this moment it looks as if a have a limit on the amount of messages to fetch and wait 5 minutes the process is working wel. But an option to have the 5 minute wait in de fetch would be nice.

**Comment by ikvk** [comment]
```
import time
from imap_tools import MailBox

# 1
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for msg in mailbox.fetch():
        print(msg.date)
        time.sleep(30)
   
# 2   
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for msg in mailbox.fetch(bulk=1):  # fetch bulk msgs
        print(msg.date)
```
Are this variants are not suitable?
