### ISSUE TITLE
Incorrect type annotations

### ISSUE THREAD

**Issue by UlisseMini** [ikvk/imap_tools#136]
[Here](https://github.com/ikvk/imap_tools/blob/a3754fc5af0785632da02e297aeb4ec48227081f/imap_tools/utils.py#L131) and in many other places you use the notation `str or bytes`. this evaluates to `str` (since `str` is truthy `or` returns the first argument) giving the wrong type hints to IDEs.

The correct way to do this is to use [typing.Union](https://docs.python.org/3/library/typing.html#typing.Union) eg.
```py

from typing import Union
def quote(value: Union[str, bytes]) -> Union[str, bytes]:
  ...
```

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/issues/115

**Comment by ikvk** [comment]
I see that 3.3 - 3.5 are already unsupported, so I will drop it soon. Thanks for your concern

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.47.0
