### ISSUE TITLE
"ssl_context" and "starttls" not work

### ISSUE THREAD

**Issue by nixiam** [ikvk/imap_tools#137]
Hello,
meanwhile, thank you for the work you have done.

I'm having trouble using the module by forcing the ssl context.

Indeed this code works

`tls_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`
`tls_context.set_ciphers('DEFAULT@SECLEVEL=1')`
`server = imaplib.IMAP4(email_credentials['Host'])`
`server.starttls(ssl_context=tls_context)`
`server.login(email, email_credentials['Password'])`

but this

`tls_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`
`tls_context.set_ciphers('DEFAULT@SECLEVEL=1')`
`mailbox = MailBox(email_credentials['Host'], ssl_context=tls_context, starttls=True)`
`mailbox.login(email, email_credentials['Password'])`

not work, returning "socket error: EOF" error

I'm using python 3.8.11 and imap-tools 0.46.0

**Comment by TheZavitaev** [comment]
Hi, Guys!
Faced a similar problem

**Comment by ikvk** [comment]
I have no mailbox with TLS support. Hope for info from anyone.

**Comment by ikvk** [comment]
Thanks to all. If anyone see how to improve lib logic - let me know, or just to it.

**Comment by ikvk** [comment]
@nixiam, about you examples: I think it must works:

    import ssl, imaplib, imap_tools

    tls_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    tls_context.set_ciphers('DEFAULT@SECLEVEL=1')

    # imaplib
    server = imaplib.IMAP4('Host')
    server.starttls(ssl_context=tls_context)
    server.login('email', 'Password')

    # imap_tools variant
    server = imap_tools.MailBox('Host')
    server.box.starttls(ssl_context=tls_context)  # server.box
    server.login('email', 'Password')

**Comment by ikvk** [comment]
May anyone check it https://github.com/ikvk/imap_tools/pull/157 - MailBoxTls
Is it good enough interface?
Is it works correct?

May be someone knows public mail that supports STARTTLS?

**Comment by ikvk** [comment]
STARTTLS logic moved to MailBoxTls
