### ISSUE TITLE
Junk mails for hotmail

### ISSUE THREAD

**Issue by siwalex** [ikvk/imap_tools#138]
hello, is it possible to read emails from junk (spam) mail pls?
thx

**Comment by ikvk** [comment]
```
from imap_tools import MailBox, AND
with MailBox('imap.mail.com').login('test@mail.com', 'pwd', 'junk') as mailbox:
    subjects = [msg.subject for msg in mailbox.fetch()]

# mailbox.folder.list() to see folders
```

Do not be so lazy!

**Comment by siwalex** [comment]
thank you, but I meant at the same time.
my code is like : 

with MailBox(imap_url).login(user, password, 'inbox') as mailbox:
    with MailBox(imap_url).login(user, password, 'junk') as mailboxj:

there is another way to do it maybe?
sorry i'm not that good at python :/

thx

**Comment by ikvk** [comment]
folder.set
