### ISSUE TITLE
Move messages unread

### ISSUE THREAD

**Issue by arddg** [ikvk/imap_tools#14]
Hi!
I'm using mailbox.move to move some messages from one folder to another, but all messages become read after moving. Can we move them with unread status? Or maybe set unread status again to that messages after moving?
Thanks!

**Comment by vivekgiri1991** [comment]
mailbox.move(msg.uid, 'foldername')

**Comment by ikvk** [comment]
Hello.
Seen flag sets when you fetch uids.
MailBox.fetch mark_seen argument - mark emails as seen on fetch
It should solve your problem with move. 
Anyway you can use MailBox.fetch seen method.

You say "I'm using" but do not "I'm set star" =)

**Comment by arddg** [comment]
Sorry, haven't noticed "mark_seen" argument before :)
Here is my current code:
```
from imap_tools import MailBox, Q
with MailBox('Outlook.Office365.com').login('username@outlook.com', '123456', initial_folder='Junk') as mailbox:
mailbox.move(mailbox.fetch(mark_seen=False), 'Inbox')
```
It seems it works now. Thanks for your help!

**Comment by ikvk** [comment]
You are welcome
