### ISSUE TITLE
Wrong attachment size

### ISSUE THREAD

**Issue by Nicarex** [ikvk/imap_tools#140]
Hello, I have a problem with the wrong attachment size
I know my file size is 10 353 154 bytes, but attachment.size says 13 986 311 bytes
With the following code:
```
mailbox = MailBox('imap.gmail.com')
mailbox.login(username=USERNAME, password=PASSWORD)
for msg in mailbox.fetch(AND(seen=False)):
    for attachment in msg.attachments:
        print(attachment.size)
```
I am using Python 3.9 and imap-tools 0.48.1
Can someone check it?

**Comment by ikvk** [comment]
Interesting question. Seems like a bug, I checked too. Any Ideas?

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.49.0
