### ISSUE TITLE
MailBox Not Refreshing?

### ISSUE THREAD

**Issue by Jmarks199** [ikvk/imap_tools#142]
When new messages come into the inbox, mailbox.uids() returns the exact same result set. And, calling fetch on the UID that exists yields an error.

Then, after calling logout() and then login() again, mailbox.uids() returns the correct result set. Is this the expected behavior? Is there anyway to refresh the connection?

**Comment by ikvk** [comment]
Really interesting behaviour, reprodused it. I will investigate it.

**Comment by ikvk** [comment]
*There is no "reconnect" in IMAP, only logout-login

**Comment by Jmarks199** [comment]
I did not find out the reason. I suppose it is not a bug, just the way that it is. I went back to using aioimaplib instead.
