### ISSUE TITLE
does not support pgp encrypted email that without a filename

### ISSUE THREAD

**Issue by wlya** [ikvk/imap_tools#144]
```
-----------=_123124123123-123-123
Content-Type: application/pgp-encrypted
Content-Disposition: inline
Content-Transfer-Encoding: 7bit

Version: 1
-----------=_123124123123-123-123
Content-Type: application/octet-stream
Content-Disposition: inline
Content-Transfer-Encoding: 7bit

----------BEGIN PGP MESSAGE--------

Version: GnuPG v1

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

This will let html and text and attachments are ALL empty.

**Comment by ikvk** [comment]
It is possible that reason is the defect in eml: 
print(msg.obj.defects)
[MissingHeaderBodySeparatorDefect()]

**Comment by Luto73** [comment]
Like @stumpylog I am using paperless-ngx for my archive. And since I am signing my mails with s/mime paperless can't import the pdf file. It seems that this is in issue in imap_tools according to the issue mentioned by stumpylog 3 weeks ago. What can I do to help find a fix?
