### ISSUE TITLE
Not catching a login error due to invalid credentials

### ISSUE THREAD

**Issue by NickC-NZ** [ikvk/imap_tools#148]
imap_tools.Mailbox.login() should raise an imap_tools.MailboxLoginError exception on invalid credentials. However a imaplib error gets raised instead:

> Nov 15 03:37:20 python3[26043]:   File "/opt/3686-imap-client/bin/3686-imap-client.py", line 60, in broadcast_messages
> Nov 15 03:37:20 python3[26043]:     mb.login(settings["username"], settings["password"], initial_folder=settings["mailbox"])
> Nov 15 03:37:20 python3[26043]:   File "/opt/3686-imap-client/lib/imap_tools/mailbox.py", line 46, in login
> Nov 15 03:37:20 python3[26043]:     login_result = self.box.login(username, password)
> Nov 15 03:37:20 python3[26043]:   File "/usr/lib/python3.7/imaplib.py", line 598, in login
> Nov 15 03:37:20 python3[26043]:     raise self.error(dat[-1])
> Nov 15 03:37:20 python3[26043]: imaplib.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

It's because the imap_tools.Mailbox.login function calls the imaplib.IMAP4.login function, checks the result, then raises the imap_tools.MailboxLoginError exception if the result isn't 'OK'. That check is never reached as the imaplib.IMAP4.login function has already checked whether the result is 'OK' and raised its own error.

I think the imap_tools.Mailbox.login function needs to try/except the imaplib.IMAP4.login function to catch the imaplib exception and and raise the MailboxLoginError exception.

**Comment by ikvk** [comment]
Thanks, Nick. This is old bug, I do not decided how to fix it right - imaplib can change login behaviour. I will fix it.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.50.0
