### ISSUE TITLE
date_gte does not work anymore

### ISSUE THREAD

**Issue by HenkVanHoek** [ikvk/imap_tools#149]
I have the following code:
mailbox.fetch(criteria=AND(date_gte=date(yyyy, mm, dd)),
                                 charset='US-ASCII',
                                 bulk=True,
                                 limit=1000)

The problem is, that whatever I use for yyyy, mm and dd, the returned messages are from the current date.
Funny thing is, that it worked before. I did not change the code

I tested it with outlook, gmail and another imap server.

**Comment by ikvk** [comment]
Have checked just now ('YANDEX', 'ZIMBRA', 'OUTLOOK', 'GOOGLE', 'YAHOO') - all works.
May be firewall, of admin magic?

**Comment by ikvk** [comment]
What python ver?

**Comment by HenkVanHoek** [comment]
Sorry, I had a loop of multiple servers. I reset the date to today after the first mailserver got the messages. Therefore the other servers got only the messages from today. Silly me.

**Comment by ikvk** [comment]
"Some" happens :D
