### ISSUE TITLE
Should "socket.gaierror: [Errno 2] temporary failure in name resolution" raise ImapToolsError for convenience?

### ISSUE THREAD

**Issue by nkuehnle** [ikvk/imap_tools#150]
I have some code that looks like the example below,  which periodically runs to fetch new messages from an inbox using a try/except block, since this runs on a Raspberry Pi that occasionally loses WiFi before reconnecting later on.

I thought that excepting only ImapToolsError would catch all errors specifically associated with connecting to the IMAP server of interest, but that doesn't seem to be the case. I would suggest that these type of errors should be collected under ImapToolsError. Or perhaps a new high-level exception that can be used to grab all such more primitive errors related to connecting to an IMAP server.

Thoughts? I would put in a PR myself, but I'm actually familiar with the low-level workings of IMAP to put in something that is both specific enough and comprehensive to fulfill this use-case (hence why I'm using this library, which is a wonderful high-level API, btw!).

I know that for my particular use case a broad "except Exception:" would probably be fine, but it's obviously less elegant.

```
def check_orders(self, box: str = 'INBOX') -> CancelJob:
    """
    Wraps :meth: 'Messenger.check()'

    This function is passed to :meth: PJob.do() to be repeated if an 
    exception occurs.

    Helps ensure that messenger connection issues do not crash the program

    Parameters
    ----------
    box : str, optional
      The inbox to search in, by default 'INBOX'

    Returns
    -------
    CancelJob
      Cancels any scheduled recurrent jobs.
    """

    try:
      new_messages = self.messenger.check(box)
      self.pending_commands += new_messages
    except ImapToolsError: # Re-schedules w/ low priority
      try_again = self.schedule.every(1).minutes
      try_again.lowest_priority
      try_again.do(self.check_orders, box)

    return CancelJob()
```

**Comment by ikvk** [comment]
socket.gaierror not related to imap_tools lib logic, and not related to IMAP.
just use: except (ImapToolsError, gaierror):
