### ISSUE TITLE
Why is there a preference of using Tuples over Dict structure for the objects?

### ISSUE THREAD

**Issue by xprilion** [ikvk/imap_tools#151]
I observed that almost all of the objects in this repo use Tuples wherever possible and almost never a Dict. A Dict structure would help convert the objects to JSON properly and pass over REST APIs.

Is there a specific reason behind this? I'll be happy to work on refactoring the objects to work with Dicts instead of Tuples or in the least provide a method that quickly converts objects to JSON-friendly structure.

**Comment by ikvk** [comment]
* dict consume more memory then tuple, it make sense everywhere
* MailMessage and MailAttachment are for parse message, not for help to convert it to JSON or other
* Anyway, there is no universal mapping to dict for all. Just map into dict all what you need.
* related thread: https://github.com/ikvk/imap_tools/issues/124
