### ISSUE TITLE
Receipients receiving notifications

### ISSUE THREAD

**Issue by C42EFF4Lbb54dwg** [ikvk/imap_tools#155]
Hi,

Thank you for all the hard work. It is much appreciated.

Just one small issue,:

When moving a number of old emails which have been seen, read and attended to, and these emails had delivery and read receipts enabled, the sender of the email receives notification that the email was deleted without having been read.

Generally, this would not be a problem but can cause mayhem and panic on the side of the sender.

Is there anyway we can disable or not allow such notifications from being sent?

Thanks!

**Comment by ikvk** [comment]
Hello
Why just not read them by robot?
.seen method | fetch mark_seen arg

**Comment by C42EFF4Lbb54dwg** [comment]
Does "mark_seen" not change the email from unread to read on the mailbox?

`:param mark_seen: mark emails as seen on fetch`

`message_parts = "(BODY{}[{}] UID FLAGS RFC822.SIZE)".format('' if mark_seen else '.PEEK', 'HEADER' if headers_only else '')`

> [RFC822 is equivalent to BODY[], which is defined to set the read flag. .PEEK is modifier that makes it not set read](https://stackoverflow.com/questions/43791782/python-imap4-dont-mark-messages-as-read#comment74626149_43791885) 

In my instance, I fetch a number of emails and, based on certain conditions, have them moved to different folders:
`mailbox.fetch((NOT(AND(uid=list(seen_emails))) if len(seen_emails) > 0 else 'ALL'), bulk=True, reverse=True, limit=n_to_process, mark_seen=False)` returns a list of uids. This is not what is sending the notification to the email sender.

The list is then passed to a function and:
` for x in uid:
    move_ = mailbox.move(x, str(_dest_folder))`

On successful move and consequent delete, notwithstanding if the moved email is old and read, and subject to the moved email having had delivery and read receipts enabled, the email sender receives a notification that the email has been deleted without being read.

So the issue is not caused by the actual move but by the `delete` function 
`store_result = self.box.uid('STORE', uid_str, '+FLAGS', r'(\Deleted)')`

Maybe adding `\Seen` after `\Deleted` may work? I will play around with this.

**Comment by ikvk** [comment]
I meaned:
1. first mark them as read
2. after that, del it
Now I see that emails old and read.
Interesting case, I will try to check it at free time.
Let me know about news

**Comment by ikvk** [comment]
You should work with Disposition-Notification-To email header. (or, maybe: X-Confirm-Reading-To, Return-Receipt-To)
Logix may depends on server implementation.
https://www.rfc-editor.org/rfc/rfc2298 :

```
The Disposition-Notification-To Header

   A request that the receiving user agent issue message disposition
   notifications is made by placing a Disposition-Notification-To header
   into the message.
```

I have no working example, if you will find decision, please share it.
