### ISSUE TITLE
i can login with imaplib but imap_tools else

### ISSUE THREAD

**Issue by luanon404** [ikvk/imap_tools#158]
I dont know why imap_tools always return b'authentication failed' instead i can login with imaplib. I used example on readme, if you know way to fix, please tell me, thanks.

**Comment by luanon404** [comment]
trying add ssl_context and got this error
imaplib.abort: socket error: EOF

**Comment by ikvk** [comment]
So, what about details?

**Comment by Miltonbhowmick** [comment]
I am having same problem!

**Comment by luanon404** [comment]
> I am having same problem! Using imaplib: `('OK', [b'miltonbhowmick7@gmail.com authenticated (Success)'])` Using imap_tools: `imaplib.IMAP4.error: b'authentication failed'`

yes, that it, i dont know what is the real reason for that, just use imaplib instead of imap_tools, i guess

**Comment by ikvk** [comment]
@Miltonbhowmick, @luanon404 
may you show examples?

**Comment by luanon404** [comment]
> @Miltonbhowmick, @luanon404 may you show examples?

i dont know, i just use simple method like MailBox(...).login(email, pwd) but imaplib return login success but imap_tools else

**Comment by ikvk** [comment]
so, give me 2 minimal blocks of code:

1 with imap_tools error
2 with imaplib ok

imap_tools  is not block any login method, BaseMailBox is flexible enough

**Comment by luanon404** [comment]
> so, give me 2 minimal blocks of code:
> 
> 1 with imap_tools error 2 with imaplib ok
> 
> imap_tools is not block any login method, BaseMailBox is flexible enough

i think because "less secure apps", because now i using password for app to login and it working

**Comment by Miltonbhowmick** [comment]
@ikvk 
Using imaplib:
`
import email, imaplib
username= "abc@gmail.com"
password= "your-app-password"
mail= imaplib.IMAP4_SSL("imap.gmail.com")
mail.login(username, password)
`

Using imap_tools:
`
from imap_tools import MailBox
username= "abc@gmail.com"
password= "your-app-password"
with MailBox("imap.gmail.com").login(username, password, "INBOX") as mailbox:
   for message in mailbox.fetch(limit=5, reverse=True):
       print(message.date_str, message.subject)
`

I tried from my PC. imap_tools was not working in my end but it works on my friends end.

**Comment by ikvk** [comment]
@Miltonbhowmick , your OS and python ?

**Comment by joealcorn** [comment]
For anybody stumbling upon this, gmail's IMAP server doesn't support TLS. You can override `_get_mailbox_client` as a workaround:

```python
from imaplib import IMAP4_SSL
from imap_tools import MailBoxTls

class MailBox(MailBoxTls):
    def _get_mailbox_client(self) -> IMAP4_SSL:
        client = IMAP4_SSL("imap.gmail.com")
        return client
```
