### ISSUE TITLE
IDLE: New received emails aren't fetched

### ISSUE THREAD

**Issue by Isumairuu** [ikvk/imap_tools#159]
I used `idle.wait` to keep listening to emails by calling `mailbox.fetch`, and while emails that are already in mailbox get fetched when I change their flag to `unseen` newly sent emails aren't retrieved. I tried using `new` in search query and removing the `reverse` attribute from `fetch` but couldn't get it to work. I already checked the answer [here](https://stackoverflow.com/questions/71335734/imap-tools-not-fetching-new-emails) too.
Edit: One way of 'solving' this is to login to the mailbox with each fetch but that isn't practical.

**Comment by ikvk** [comment]
NEW - have the Recent flag set but not the Seen flag

Try another criterias: https://github.com/ikvk/imap_tools/blob/master/examples/idle.py#L19
I have test it on several mail providers, and it works.

Also sometimes it matters that mailbox web interface is opened together with robot.

**Comment by Isumairuu** [comment]
That didn't solve the problem and I had some errors working with it, the only thing that seemed to work was to retry connecting before fetching messages. In this case after 2 minutes or so I get the following error: 
` Response status "OK" expected, but "NO" received. Data: [b'[ALERT] Too many simultaneous connections. (Failure)']`

**Comment by ikvk** [comment]
what about "mark_seen" arg?

**Comment by Isumairuu** [comment]
That's not where the problem is I guess, I did use `mark_seen` arg while fetching, but my problem was that when a new message is sent to the mailbox while the connection is open and the `mailbox.fetch` is called that new messages isn't detected until you logout from the mailbox and login again, here's a short demo of how I *solved* it:
```python
mailbox = MailBox(host).login(username, password, initial_folder='INBOX')

while 1:
    messages = mailbox.fetch(AND(all=True, subject="some subject", seen=False), limit=1, reverse=True, bulk=False,
                             mark_seen=True)
    messages = list(messages)
    if messages:
        msg = messages[0]
        print("Subject:", msg.subject)
    else:
        mailbox.logout()
        mailbox = MailBox(host).login(username, password, initial_folder='INBOX')
        print("No messages")
    time.sleep(2)
```
The output when you get a new message with "some subject" should be something like this:
```
Subject: some subject
No messages
No messages
```

**Comment by ikvk** [comment]
is it works on your server? 
https://github.com/ikvk/imap_tools/blob/master/examples/idle.py#L19
All servers for tests this lib works with it example for days
Try to localize problem

While 1 may cause server ban.

MailBox create client with socket, of course it must be in while, but you have two MailBox - strange

Why are you ignore MailBox context manager?

**Comment by Isumairuu** [comment]
@ikvk I did try using the context manager but it didn't work as expected, at times it just stops fetching emails, even older ones.
