### ISSUE TITLE
gmail: Unreliable parsing of dates

### ISSUE THREAD

**Issue by dlwaticg** [ikvk/imap_tools#160]
I am using imap-tools to read emails form Gmail.
After upgrading to python3.x and getting the latest imap-tools library multiple dates (both msg.date and msg,date_str) are missing and represented as None.
However, when I check the same message in Gmail there is a valdi date.
Also, when i look into the msg.obj.__dict__.payload in the debugger I see the same date as in Gmail.
I wonder if this may have something to do with the new tzinfo headache in Python3?
Any ideas would be greatly appreciated.

**Comment by ikvk** [comment]
There is tests in lib. https://github.com/ikvk/imap_tools/blob/master/tox.ini
For now it for: py3.5,py3.6,py3.7,py3.8,py3.9,py3.10
Also I have checked manually on 3.6 and 3.10 with gmail - all works as expected, all dates are identical

1. Try to check on another gmail mailbox
2. Show me .eml (cutted if you need)

**Comment by ikvk** [comment]
* Its enough date header from src:

...
Date: Wed, 01 May 2019 12:20
...

**Comment by ikvk** [comment]
Let me know if you will decide to work on it
