### ISSUE TITLE
Password limited to ASCII at login?

### ISSUE THREAD

**Issue by stumpylog** [ikvk/imap_tools#161]
When trying to login to a MailBox with a password containing non-ascii character, imap_tools will fail with the following:
```
>>> from imap_tools import MailBox
>>> m_box = MailBox("imap.gmx.com", 993)
>>> m_box.login("dev-testing-paperless@gmx.com", "réception")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tank/users/username/projects/paperless/paperless-ngx/.venv/lib/python3.8/site-packages/imap_tools/mailbox.py", line 63, in login
    login_result = self.client._simple_command('LOGIN', username, self.client._quote(password))  # noqa
  File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.8/imaplib.py", line 962, in _command
    arg = bytes(arg, self._encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 2: ordinal not in range(128)
```
(obviously spoofed values in the log here)

Is there a missing option to call the IMAP4.enable?

**Comment by stumpylog** [comment]
If I directly set the underlying IMAP4 object's encoding, login will succeed: `m_box.client._encoding = "utf8"`, though setting a member like that seems pretty incorrect.

**Comment by ikvk** [comment]
BaseMailBox.client - imaplib.IMAP4/IMAP4_SSL client instance.

So, you may:
```
m_box = MailBox("imap.gmx.com", 993)
m_box.client.enable('UTF8=ACCEPT')

```
Is it what are you need?

**Comment by ikvk** [comment]
*As I know, by default user name and password supports only ASCII

**Comment by stumpylog** [comment]
Unfortunately, it appears the capability enable requires the client to be authorized.

 I think you're right, the RFC doesn't say that login can accept a charset, so that implies it is limited to ASCII. 

Does nearer/token allow UTF-8 without auth?

**Comment by cpwnd** [comment]
To login with utf8 input RFC suggests using "AUTHENTICATE", but depends on the server side implementation.
https://datatracker.ietf.org/doc/html/rfc6855.html#page-5

Maybe this could be incorporated into the `login` method (e.g. as fallback), when utf8 input for login is provided.

**Comment by ikvk** [comment]
* Incorporating into login - no
* Implementation as separated method, like xoauth2 - I don't mind. For example: login_utf8

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.57.0
