### ISSUE TITLE
Fetch all emails, not only from inbox

### ISSUE THREAD

**Issue by heirinsinho** [ikvk/imap_tools#168]
Hi!
Great job. I tell you my problem. My domain was blocked a couple of days, so I could not receive emails during those days, but there was no error message to the senders.
Is it possible to recover them with you library? I fetched ALL, but it gives the list of emails in the inbox (not in spam, notifications, newsletters...)

**Comment by ikvk** [comment]
Hello.
Yes, you can.
1. Save - https://github.com/ikvk/imap_tools/blob/master/examples/email_to_file.py
2. Select path - mailbox.folder.set OR login 3rd arg
Thats it.
