### ISSUE TITLE
Search based on a Message-ID value returns nothing

### ISSUE THREAD

**Issue by JacquelinCharbonnel** [ikvk/imap_tools#170]
Hi Vladimir ! I have a mail with this raw header :
```    
List-Id: =?utf-8?B?IkZvcnVtIGfDqW7DqXJhbCIgPG1vb2RsZWZvcnVtMTU5NjFAbW9vZGxlLnU=?=
 =?utf-8?B?bml2LWFuZ2Vycy5mcj4=?=    
```    
 
I print this header with :
```    
print(msg.headers["List-Id"])
```    
and I get something like :
```    
<178c7277b438cd0c8b0864ab7c4e42906a0446b8cb62755ef3ca86488c811f71@moodle.univ-angers.fr>
```    
It's fine ! So I search for it with :
```    
fetch("A(header=[H('List-Id',"moodle")])",**self.fetch_opts)
```    
and I get it, great again !
This mail has the following header :
```    
Message-ID: <69db5c90a1d49a987d67f10a99680ac435d3de5dc990cbb16baf303d0d7039d5@moodle.univ-angers.fr>
```    
So, I search for it with :
```    
fetch("A(header=[H('Message-ID',"moodle.univ-angers.fr")])",**self.fetch_opts)
```    
or
```    
fetch("A(header=[H('Message-ID',"moodle")])",**self.fetch_opts)
```    
but the search returns nothing. With :
```    
fetch("A(header=[H('Message-ID',"")])",**self.fetch_opts)
```    
I get it, but why the 2 firsts don't work ?

**Comment by ikvk** [comment]
Hello,
Thats what i found: 
#Message-Id: <314041645426922@mail.yandex.ru>

A(header=H('Message-Id', '314041645426922@mail.yandex.ru'))
works

A(header=H('Message-Id', '314041645426922'))
not works

Seems that search by Message-Id works like "exact equal"
I think this is a feature, not bug.

**Comment by e-katkov** [comment]
Добрый день!
У меня в чем-то похожая проблема. Почему не работает такой код:
```
with MailBox(HOST).xoauth2(email, access_token) as mailbox:
    mailbox.folder.set(folder_1)
    criteria = A(header=H('Message-ID', '<dkgj699i49fo5@google.com>'))
    messages = mailbox.fetch(mark_seen=False, headers_only=True, criteria=criteria)
    messages_ids = [message.headers['message-id'][0] for message in messages]
```
Письмо с message_id <dkgj699i49fo5@google.com> в папке folder_1 есть, но messages_ids пустой

**Comment by ikvk** [comment]
@e-katkov Попробуйте без <>

И трейс покажите весь

**Comment by e-katkov** [comment]
@ikvk Пробовал задать почтовый ящик без <> - результат тот же.

![Screenshot_36](https://github.com/ikvk/imap_tools/assets/81775754/b449278b-4bbd-4250-bcf1-fd2eda287b67)

**Comment by ikvk** [comment]
Возможно гугел выключил поиск по Message-ID

**Comment by e-katkov** [comment]
@ikvk спасибо!
