### ISSUE TITLE
Shouldn't TLS be the default behavior?

### ISSUE THREAD

**Issue by helgihg** [ikvk/imap_tools#171]
Every IMAP library I've seen for Python so far treats TLS as some kind of special requirement or anomaly, when the reality is that it's the norm and should be a basic requirement for any email-enabled software. It's what should always be done unless there is a particular reason not to.

Seeing that in Python 3, we have access to the CA in the operating system, there is no need to bother the programmer with the intricacies of TLS. The default behavior should be that TLS is assumed, with all that certificate business being handled behind the scenes without the programmer needing to worry about it at all.

Unless of course they have their own certificate, or for some reason need to avoid TLS. These are not the norm, they are anomalies and hopefully extraordinarily rare ones.

**Comment by ikvk** [comment]
1. imap_tools provides 3 class for mailbox
MailBox, MailBoxTls, MailBoxUnencrypted
also there is two auth methods: BaseMailBox.login, MailBox.xoauth2

2. I do not agree than TLS should be default behavior.
Programm may work in trus network, i.e. company network.
Also, I am sure that TLS is not eternal.

3. Have you some concrete suggestions for lib?

**Comment by ikvk** [comment]
Write here any time
