### ISSUE TITLE
'FolderInfo' object is not subscriptable

### ISSUE THREAD

**Issue by cryptobiotic** [ikvk/imap_tools#172]
Hi,  when trying to get a list of all folder names, and using your example, i get the error: 'FolderInfo' object is not subscriptable

from imap_tools import MailBox
with MailBox('imap.mail.com').login('test@mail.com', 'password') as mailbox:
    # get all folders
    for f in mailbox.folder.list():
        print(f['name'])

**Comment by ikvk** [comment]
Hi
Check https://github.com/ikvk/imap_tools/blob/master/docs/release_notes.rst

**Comment by ikvk** [comment]
0.48.0

**Comment by cryptobiotic** [comment]
I'm using 0.55 and still receive the error using your example.  "TypeError: 'FolderInfo' object is not subscriptable"
On Python 3.9.5

**Comment by ikvk** [comment]
.......

```
for i in mailbox.folder.list():
      print(i)
      print(i.name)
```
