### ISSUE TITLE
Fastest way to fetch all headers

### ISSUE THREAD

**Issue by H3nkl3r** [ikvk/imap_tools#173]
Hi. Thank you for this helpful package.

What is the fastest way to download all headers? (I only need the subject and the from_ from an email)

My current approach is like this:
```
with MailBox(TEST_EMAIL_IMAP_SERVER).login(TEST_EMAIl_USERNAME, TEST_EMAIL_PASSWORD) as mailbox:
    mailbox.folder.set('INBOX')
    mail_list = [[mail.subject, mail.from_] for mail in mailbox.fetch(headers_only=True, bulk=True)]
```

But this isn't really fast. I have seen an issue (#56) here where someone is fetching 6000 mails in 15 seconds. Mine takes 80 seconds for 1250 Mails.

I would appreciate any help.
Thank you

**Comment by ikvk** [comment]
Hi.
mark_seen arg may make sense, but I think not very.
There is the fast way in your example.

You may try to find some imap spec. features 
https://github.com/ikvk/imap_tools/blob/master/docs/IMAP_related_RFCs.txt

*Speed depends on many things at all.
