### ISSUE TITLE
Make expunge optional at setting a flag

### ISSUE THREAD

**Issue by DanielB1990** [ikvk/imap_tools#177]
Hello,

Let me start by telling you this project has made my life a lot easier for managing specific kind of mailboxes, moving and/or deleting messages on certain criteria,

I have another specific case where a mailbox filter from a Webmail software sets 'flag' to 'deleted'.
I'm unable to undo this flag via the Webmail and therefor wanted to use imap_tools for it.

The problem I'm facing when having multiple messages marked as 'deleted' is that when handling the first message by using `flag(message_data.uid, MailMessageFlags.DELETED, False)` it is changed correctly, but then due to [this expunge](https://github.com/ikvk/imap_tools/blob/master/imap_tools/mailbox.py#L225) it causes all other messages to be removed, which is what I want to prevent and remove the 'deleted' flag via the search `criteria=AND(deleted=True)` + for loop for all other messages too.

Would it be possible the make this optional, default is 'yes' but option to set to 'no'?
I'm not comfortable to attempt making that change myself unfortunately.

**Comment by ikvk** [comment]
Greetings.
Is there any reasons to send N separate delete queries instead this:
Collect uids for delete and send one delete query (one a few if butch is really very big)
?
The same with flags.

**Comment by ikvk** [comment]
expunge also available:

mailbox.client.expunge()

**Comment by ikvk** [comment]
*desicion: flag + expunge

**Comment by DanielB1990** [comment]
Thanks @ikvk I've never thought of flagging the group of uids to remove the delete flag.
