### ISSUE TITLE
Cloning message

### ISSUE THREAD

**Issue by cboden** [ikvk/imap_tools#18]
I'm having trouble cloning a message. My intent is to serialize and access on a different service. When testing the code below I set at least one message to unread in my native mail client. 

```python
from imap_tools import MailBox, Q, MailMessage

mailbox = MailBox(os.getenv('MAIL_HOST'))
mailbox.login(os.getenv('MAIL_USER'), os.getenv('MAIL_PASS'), initial_folder='INBOX')

msgs_gen = mailbox.fetch(Q(seen=False))
msgs = list(msgs_gen)

test = msgs[0]
test_copy = MailMessage.from_bytes(test.obj.as_bytes())

print(test.uid)
print(test_copy.uid)
```

Results in the error when accessing `test_copy.uid`:
```
     60         """Message UID"""
     61         # zimbra, yandex, gmail, gmx
---> 62         uid_match = re.search(r'UID\s+(?P<uid>\d+)', self._raw_uid_data.decode())
     63         if uid_match:
     64             return uid_match.group('uid')

AttributeError: 'NoneType' object has no attribute 'decode'
```

Many of the email properties make their way to the copy, but not all, including `uid` and `flags`. 

My mail server is hosted on Microsoft Office 365, which is an Exchange server.

**Comment by ikvk** [comment]
# get message by id
fetch_result = self.box.fetch(message_id, "(BODY[] UID FLAGS)"...
UID and FLAGS are separate part of fetch

test.obj.as_bytes() contains only BODY

what is uid:
https://tools.ietf.org/html/rfc3501#section-2.3.1.1

case of usage alternative constructor:
https://github.com/ikvk/imap_tools/blob/master/examples/parse_eml.py

Of course there is no flags and uid when using MailMessage.from_bytes
You can serialize uids explicitly, but it is wrong idea
Serializing flags not so wrong, but not good too
