### ISSUE TITLE
mailbox.idle.wait returns empty set while there are unread emails in Inbox

### ISSUE THREAD

**Issue by quammy** [ikvk/imap_tools#183]
Since ~6 hours ago (after running flawlessly for couple of months), my code with ```mailbox.idle.wait``` suddenly started to return an empty set ```[]``` while ```mailbox.folder.status('INBOX')``` returns a result such as ```INBOX: {'MESSAGES': 4, 'RECENT': 4, 'UIDNEXT': 14058, 'UIDVALIDITY': 14, 'UNSEEN': 2}```.
With ```mailbox.idle.wait``` returns empty set, my code does not try to access the emails, as it expects a result such as ```[b'* 1 RECENT', b'* 1 EXISTS']``` or alike.

I guess I can check the value of ```mailbox.folder.status('INBOX')``` and take it from there, but I assume this is not a normal behavior and make the ```mailbox.idle.wait``` function redundant.

I'm running version 0.54, which I can upgrade  if required. The email supplier is a free account on outlook.com and the browser with outlook.com account was closed at the time of the failures and following tests. The timeout being used is 180 sec.

I'll appreciate any guidance of how to resolve it. Thanks.

**Comment by quammy** [comment]
more info, if helps - I set "justMyCode" to false and went in to the package's code. It seems something deeper than the package wrapper over imaplib as I think it arrives correctly to idle.py -> get_socket_poller -> ```return select.select([sock], [], [], timeout)[0]``` where it returns ```[]```.
BTW, the problem occurs both on Linux and Windows OS.

**Comment by jamesarmst** [comment]
I have the same issue. It started at the same time as quammy's problem. I am using 0.51.1.

**Comment by quammy** [comment]
While waiting for community support, I updated 
```
responses = mailbox.idle.wait(timeout=60*Settings.Email.ResponseTimeout)
if responses:
   ...
```
to 
```
responses = mailbox.idle.wait(timeout=60*Settings.Email.ResponseTimeout)
if responses or mailbox.folder.status('Inbox')["UNSEEN"] > 0:
   ...
```
and ```Settings.Email.ResponseTimeout``` from 3 to 2/60 (i.e. test every 2 seconds)
so now the code is not really in push mode but rather checking every 2 sec. I don't think it is a good solution and wonder if the mail server will not block me at some point.

**Comment by ikvk** [comment]
IMO With timeout in 2 sec there is no reason to use idle.

**Comment by quammy** [comment]
> IMO With timeout in 2 sec there is no reason to use idle.

I 100% agree. I don't want to use 2 sec timeout if idle works. But currently idle finish whatever timeout it has (tested with 180 sec.) and return ```[]``` even if new emails arrived since calling ```mailbox.idle.wait```.

**Comment by ikvk** [comment]
I do not see a bug here yet. 
Lib just invoke imap commands.
Most likely here is changed server logic at outlook.com

**Comment by quammy** [comment]
@ikvk - Yes, please see my second post - 
idle.py -> get_socket_poller -> ```return select.select([sock], [], [], timeout)[0]``` returns ```[]```. Any chance with your experience to look forward in to that part?

**Comment by ikvk** [comment]
I will try at free time, not soon :D

**Comment by quammy** [comment]
Sure, any help will be most appreciated as well as many thanks for the whole package as you publish it freely already. Cheers.

**Comment by jamesarmst** [comment]
This issue doesn't seem to be limited to Outlook. A script that previously worked on Zohomail now gives the same issue.

**Comment by quammy** [comment]
Just to let you know that it started to work again. No change on my side.

**Comment by ikvk** [comment]
So, it possible be
1. server issue
2. A few opened idles on your host
3. MITM ) ?

Just post here if you have info
