### ISSUE TITLE
msg.text Not Working

### ISSUE THREAD

**Issue by rob5185** [ikvk/imap_tools#184]
I've been getting email text using msg.text but it has stopped working on emails it used to work on. I have tested it on different mailboxes.

However, it still works where I forward the same email from a different mailbox which seems strange.

I am on Windows and was using v0.51 so updated to v0.56 but have the same issue.

**Comment by ikvk** [comment]
Give me an .eml with cutted secrets

**Comment by rob5185** [comment]
[Desktop.zip](https://github.com/ikvk/imap_tools/files/9424558/Desktop.zip)
Sure. Two examples from different senders attached.

**Comment by ikvk** [comment]
```
from imap_tools import MailMessage
with open('/files/...', 'rb') as f:
    bytes_data = f.read()
msg = MailMessage.from_bytes(bytes_data)
print('date:', msg.date)
print('subject:', msg.subject)
print('len(msg.text):', len(msg.text))
print('len(msg.html):', len(msg.html))
print('defects', msg.obj.defects)
```

**2 New tips from PEPPONE.eml**
    date: 2022-08-25 09:32:01+00:00
    subject: 2 New tips from PEPPONE
    len(msg.text): 1953
    len(msg.html): 23169
    defects []
    
**LIVE pick from Spongebob for Football Live.eml**  
    date: 2022-08-24 21:02:00+00:00
    subject: LIVE pick from Spongebob for Football / Live
    len(msg.text): 975
    len(msg.html): 4067
    defects []
    

I do not see problem at .eml

.msg seems broken or malformed. I will not check it.
