### ISSUE TITLE
message.from_ returns empty string

### ISSUE THREAD

**Issue by DanSantoDomingo** [ikvk/imap_tools#19]
It is what the title says, also message.from_values return this `{'email': '', 'name': '"Lopez', 'full': '"Lopez'}`

**Comment by ikvk** [comment]
You can provide me with the source of the email .eml (perhaps without critical information for you)?

Do you have any ideas how to fix it?

**Comment by DanSantoDomingo** [comment]
Is it a known issue?

**Comment by ikvk** [comment]
No, I have not encountered this

**Comment by ikvk** [comment]
In General, I encountered it. "from" may not contain an address

**Comment by ikvk** [comment]
Have you check eml source?

**Comment by DanSantoDomingo** [comment]
maybe this will help
https://docs.python.org/release/3.1.3/library/email.util.html#email.utils.parseaddr

**Comment by ikvk** [comment]
May you take me letter src - .eml ?

**Comment by ikvk** [comment]
I will try to use email.utils.parseaddr, thanks. 
If you cannot pass me eml, you may pass just unparsed email heads to me to find the error.

example:
Return-Path: <adr@wow.ru>
Received: from m101.wow.ru (LHLO m101.wow.ru) (91.111.111.101) by m101.wow.ru
 with LMTP; Fri, 17 Jan 2020 09:57:02 +0500 (YEKT)
Received: from localhost (localhost [127.0.0.1])
	by m101.wow.ru (Postfix) with ESMTP id DF4D336AC7;
	Fri, 17 Jan 2020 09:57:01 +0500 (YEKT)
X-Virus-Scanned: LOL-new at wow.ru
Received: from m101.wow.ru ([127.0.0.1])
	by localhost (m101.wow.ru [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id CMQvFwA-qbCP; Fri, 17 Jan 2020 09:57:01 +0500 (YEKT)
Received: from [127.0.0.1] (log1.stage.int.wowwow.ru [192.168.90.40])
	by m101.wow.ru (Postfix) with ESMTPSA id CAB9536AC6
	for <v.ooo@wow.ru>; Fri, 17 Jan 2020 09:57:01 +0500 (YEKT)
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Subject: =?utf-8?b?W0xPR19SRVBPUlRFUiBpbnQuc3RhZ2VdINCe0YLRh9GR0YIg0L7QsSDQvtGI0LjQsdC60LDRhQ==?=
To: v.ooo@wow.ru
Message-Id: <20200117045701.CAB9536AC6@m101.wow.ru>
Date: Fri, 17 Jan 2020 09:57:01 +0500 (YEKT)
From: adr@wow.ru
