### ISSUE TITLE
How to get the reply from this email?

### ISSUE THREAD

**Issue by ppauloces** [ikvk/imap_tools#190]
I'm trying to retrieve information from the email reply but it returns me empty()

My code:
![image](https://user-images.githubusercontent.com/81058578/198697580-003364d3-8bd0-4ed0-9c6e-f92d14a8e91f.png)

return in terminal:
![image](https://user-images.githubusercontent.com/81058578/198697868-ee048ee4-e25e-469a-af53-895ae7a5f95d.png)
Inside the quotes is my variable with email.reply_to. So returning empty

**Comment by ikvk** [comment]
Show me .eml (cut secrets)
