### ISSUE TITLE
Get information from an email reply

### ISSUE THREAD

**Issue by ppauloces** [ikvk/imap_tools#191]
Goodnight. I would like to know if it is possible to get the TIME the email was answered. Example:

Main Email - Good evening - 21:27

Reply to this email -
Good evening Paul - 21:29

**Comment by ikvk** [comment]
Email reply it is just another email. So this is: msg.date?

If you mean to get it from one email body - so - parse it. Reply style is different.

+
https://stackoverflow.com/questions/74270428/how-to-extract-delivery-time-from-an-email-with-python/74272840#74272840
