### ISSUE TITLE
Nested Folders

### ISSUE THREAD

**Issue by psyonara** [ikvk/imap_tools#193]
I use imap-tools to transfer mail messages from one account to another. The source account has nested folders, and this is represented as "Parent/Child" in the name. When I try to create such a folder in the destination account (after the parent folder also exists), I get this error: "[CANNOT] Invalid mailbox name: Name must not have '/' characters".

Is there some way that nested folders can be handled? For now I am renaming those folders in the source account so that they have a flat structure. But it would be nice for nested folders to be handled automatically.

**Comment by ikvk** [comment]
I do not know that ways. 
Usually there are many restrictions on "append" action.
