### ISSUE TITLE
IMAP4 Access Control List (ACL) Extension - Allows an authorised administrator to (fetch or login) into any user's mailbox

### ISSUE THREAD

**Issue by aatm** [ikvk/imap_tools#196]
Good morning
thank you for your work can you add this feature

Allows an authorised administrator to (fetch or login) into any user's mailbox

imaplib.IMAP4.proxyauth
Assume authentication as "user"

**Comment by ikvk** [comment]
Greet. Show me RFC description of it.

**Comment by ikvk** [comment]
imap_tools not blocks imaplib api
mailbox.client.proxyauth is not enough?

**Comment by aatm** [comment]
hello thanks for quick reply
can you check this
https://www.atmail.com/blog/imap-commands/
RFC description
https://www.rfc-editor.org/rfc/rfc4314

**Comment by ikvk** [comment]
imapsync is so hard xD, 22k rows.

[rfc4314](https://www.rfc-editor.org/rfc/rfc 4314) is interesting.
Do you see some interface for implement it?

mailbox.acl - is manager enough for all ACL methods here?
