### ISSUE TITLE
Is it possible to have regex in Search criteria? + [Sieve: An Email Filtering Language] + [rfc5228]

### ISSUE THREAD

**Issue by thanch2n** [ikvk/imap_tools#197]
I saw we can apply regex in [sieve filter](https://www.ietf.org/archive/id/draft-ietf-sieve-regex-01.html), want to know if we can have regex in IMAP search?

**Comment by ikvk** [comment]
There is no regexp in IMAP serach. https://www.rfc-editor.org/rfc/rfc3501#page-49

I am ready to consider your suggestions of implementation if you have. https://www.rfc-editor.org/rfc/rfc5228
