### ISSUE TITLE
Not possible to install?

### ISSUE THREAD

**Issue by TravelTrader** [ikvk/imap_tools#199]
When using `pip3 install imap-tools` I get several times:
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb12292bf70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imap-tools/
```

What could be the reason for those errors?

Other modules can be installed without problems.

(python 3.10.x)

**Comment by ikvk** [comment]
Find here:
https://stackoverflow.com/questions/52815784/python-pip-raising-newconnectionerror-while-installing-libraries
