### ISSUE TITLE
mailbox.move doesn't work

### ISSUE THREAD

**Issue by somepad** [ikvk/imap_tools#2]
```
import logging
from imap_tools import MailBox

## logger setup
log = logging.getLogger('mailClient')
log.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
log.addHandler(ch)

## creds
hostname = ""
login = ""
password = ""

## connect to imap
mbox = MailBox(hostname)
mbox.login(login, password, 'test')

log.debug("%s", [{'id': msg.id, 'uid':msg.uid, 'subj':msg.subject, 'date':msg.date} for msg in mbox.fetch()])
mbox.move(mbox.fetch(), 'processed')

er = mbox.expunge()
log.debug(er)
lo = mbox.logout()
log.debug(lo)
```

Outputs:
2018-12-27 18:38:14,064 - mailClient - DEBUG - [{'id': '1', 'uid': '1', 'subj': 'test', 'date': 'Thu, 27 Dec 2018 18:28:31 +0300'}]
2018-12-27 18:38:14,184 - mailClient - DEBUG - ('OK', [None])
2018-12-27 18:38:14,186 - mailClient - DEBUG - ('BYE', [b'Microsoft Exchange Server 2016 IMAP4 server signing off.'])

But message stays in the 'test' folder.
Could you please advise?

Thanks,
Andrey

**Comment by somepad** [comment]
Not sure what's going on here, but seems like Exchange somehow differs from other software.
Took and example from imaplib doc and modified it so it does pretty much the same what MailBox.fetch() does:

```
import imaplib

M = imaplib.IMAP4(hostname)
M.login(login,password)
M.select('test')

typ, data = M.search(None, 'ALL')
for num in data[0].split():
    typ, data = M.fetch(num, '(RFC822 UID FLAGS)')
    for item in data:
        print(type(item))
        print(item)
M.close()
M.logout()
```

What I see in the console:
<class 'tuple'>
(b'2 (RFC822 {7854}', b'Received: from... <skipped>')
<class 'bytes'>
b' UID 15 FLAGS (\\Seen) FLAGS (\\Seen))'

Correct UID is 15.
But MailMessage._clean_message_data() sees 2 in tuple and uses it as UID.

**Comment by ikvk** [comment]
Getting the uid worked as intended by this regular expression:
https://github.com/ikvk/imap_tools/blob/master/imap_tools/main.py#L205

The reasons for a failed move can be different.
* Pay attention to fetch params: mass_effect=True, miss_no_uuid=True
* Define the path separator for your mail server, I've seen in practice: |? /
* Verify that the directory name and level are corrects

I will be glad to know the results.

**Comment by somepad** [comment]
Here is what I'm talking about. I have a mailbox with folder 'test'. In this folder I have 1 message:
![image](https://user-images.githubusercontent.com/1551929/50535523-fca34a00-0b5b-11e9-97fa-76a204aee504.png)

Now I'm running this code:
```
import imaplib
from imap_tools import MailBox

hostname = ''
login = ''
password = ''

# imaplib
print('\nUsing imaplib')
IL = imaplib.IMAP4_SSL(hostname)
IL.login(login, password)
IL.select('test')
il_search_res = IL.search(None, 'ALL')
print('IL Search result: "{res}"'.format(res=il_search_res))
il_fetch_res = IL.fetch(b'1', '(UID)')
print('IL Fetch result: "{res}"'.format(res=il_fetch_res))

IL.logout()

#imap-tools
print('\nUsing imap-tools')
mbox = MailBox(hostname)
mbox.login(login, password)
mbox.folder.set('test')
for msg in mbox.fetch():
    print('imap-tools: Message #:"{num}", uid:"{uid}"'.format(num=msg.id, uid=msg.uid))
```

Code produces the following output:
```
Using imaplib
IL Search result: "('OK', [b'1'])"
IL Fetch result: "('OK', [b'1 (UID 1262)'])"

Using imap-tools
imap-tools: Message #:"1", uid:"1"
```

UID captured by imap-tools is not an UID.
Furthermore, if I do manually what imap-tools does to capture UID, e.g. with next code:
```
import imaplib

hostname = ''
login = ''
password = ''

# from https://github.com/ikvk/imap_tools/blob/master/imap_tools/main.py#L216
def _clean_message_data(fetch_data):
    """
    :param fetch_data: Message object model
    :returns [message_data: bytes, uid_data: bytes, flag_data: list]
    *Elements may contain byte strings in any order, like: b'4517 (FLAGS (\\Recent NonJunk))'
    """
    message_data = b''
    uid_data = b''
    flag_data = []
    for fetch_item in fetch_data:
        # flags
        if type(fetch_item) is bytes and imaplib.ParseFlags(fetch_item):
            flag_data.extend(imaplib.ParseFlags(fetch_item))
        # data, uid
        if type(fetch_item) is tuple:
            uid_data = fetch_item[0]
            message_data = fetch_item[1]
    return message_data, uid_data, flag_data

# imaplib
IL = imaplib.IMAP4_SSL(hostname)
IL.login(login, password)
IL.select('test')
search_res = IL.search(None, 'ALL')
for i, message_id in enumerate(search_res[1][0].decode().split(' ')):
    fetch_res = IL.fetch(message_id, '(RFC822 UID FLAGS)')
    messgae_data, uid_data, flag_data = _clean_message_data(fetch_res[1])
    print('imap-tools UID data: "{uid}", Flag data: "{flag}"'.format(uid=uid_data, flag=flag_data))
    print('"Flags" part of fetch_res: "{data}"'.format(data=fetch_res[1][1]))

IL.logout()

```

This will produce the following output:
```
imap-tools UID data: "b'1 (RFC822 {3047}'", Flag data: "[b'\\Seen']"
"Flags" part of fetch_res: "b' UID 1262 FLAGS (\\Seen) FLAGS (\\Seen))'"
```

Using given data item names in this order (RFC822 UID FLAGS) with MS Exchange 2016 leads to the situation when UID is located not in the place imap-tools looking it for.

**Comment by ikvk** [comment]
See the problem. May you show fetch_res[1] for last example?
...
messgae_data, uid_data, flag_data = _clean_message_data(fetch_res[1])

**Comment by ikvk** [comment]
Maybe you already have merge request?

**Comment by somepad** [comment]
I did print(fetch_res[1]) for you:
[(b'1 (RFC822 {3047}', b'Received: MESSAGE GOES HERE'), b' UID 1262 FLAGS (\\Seen) FLAGS (\\Seen))']

**Comment by ikvk** [comment]
I will try to fix in free time

**Comment by ikvk** [comment]
Hi, Andrey. I have released a new version: https://github.com/ikvk/imap_tools/releases/tag/v0.5
Can you check it at your side?

**Comment by ikvk** [comment]
* message.uid parse change is here: https://github.com/ikvk/imap_tools/commit/81d62751b00b1bb312faef655d2c1cd8bb7f0674#diff-a658fd0ea9effceb1866bf391205f834L249
