### ISSUE TITLE
Folders with '/' character in folder name

### ISSUE THREAD

**Issue by audemed44** [ikvk/imap_tools#20]
There's an issue with how the '/' characters are treated by the mailbox.folder.list and mailbox.folder.set functions.

When you list all the folders with the mailbox.folder.list function the folders with '/' in their names are returned without the '/' character. For example if I have a nested folder structure like Inbox -> test -> test1/test2 the mailbox.folder.list method returns this as Inbox/test/test1test2. 

This (Inbox/test/test1test2) raises an error when passed as an argument to the mailbox.folder.set function, so not sure if this is a problem with the set function or the list function.

**Comment by ikvk** [comment]
```
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for f in mailbox.folder.list('INBOX'):
        print(f['delim']))
        break
```

what you get on this?

**Comment by ikvk** [comment]
Your email server must not allow the creation of a folder with a separator that you will get by code above

**Comment by audemed44** [comment]
Ok, I get a '/' by the code above - but there are folders within the mailbox that have it in their name. I'll have to get people to rename their folders without special characters then.

**Comment by ikvk** [comment]
so, I think that delimiter in folder name - it is mistake.
