### ISSUE TITLE
Capability Request:  Search Criteria to include time

### ISSUE THREAD

**Issue by Swieter** [ikvk/imap_tools#201]
As I understand it right now, the search criteria is date only.  I'd like to also be able to search by time.  I've got a use case where I want to retrieve and process emails from the past 30 minutes.  I'm not familiar enough to IMAP or their servers to know if there is some limitation in the protocol for this or if it is only this library that limit to search by date only.

**Comment by ikvk** [comment]
Fetch by day and analyze time. There is no search by time. https://github.com/ikvk/imap_tools/issues/12
