### ISSUE TITLE
Add `py.typed` to support type checking

### ISSUE THREAD

**Issue by stumpylog** [ikvk/imap_tools#204]
I think this should be as easy as adding an empty file named `py.typed` and maybe adding to `package_data` in `setup.py`.  This would let users take advantage of the great typing the library has with tools like mypy.  Right now, mypy gives lines like:
```log
error: Skipping analyzing "imap_tools": module is installed, but missing library stubs or py.typed marker  [import]
```

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/pull/207
