### ISSUE TITLE
keyword parameter error?

### ISSUE THREAD

**Issue by Vinnybrunn00** [ikvk/imap_tools#205]
I'm doing some tests on the API and I realized that I can't use the `keyword` parameter in the **`fetch()`** function, could you give me examples of how to use it, I've tried several ways...

unsuccessful example:

```python
with MailBox('imap.gmail.com').login(USERNAME, PASSWORD) as inbox:
    for msg in inbox.fetch(AND(keyword=['github', 'python'])):
        from_ = msg.from_
        print(from_)
```
I already tested with all API operators: `AND, NOT, OR, A`, but I get no response using this parameter.

**Comment by ikvk** [comment]
Greet.

Special for you: 
https://github.com/ikvk/imap_tools/blob/master/examples/keyword_criteria.py
:D
