### ISSUE TITLE
Gmail returns only 2 weeks?

### ISSUE THREAD

**Issue by dzg** [ikvk/imap_tools#209]
Using `mailbox.fetch` and only getting messages newer than 14 days ago.

Why?

**Comment by ikvk** [comment]
It doesn't seem to be a telepathic club here :D, how about the details?

**Comment by dzg** [comment]
Sorry :-o

If I do 

`for msg in mailbox.fetch():`

Then I only get back messages which are less than exactly 14 days old. I.e., yesterday I got messages starting from Aug 9. Today I'm getting from Aug 10.

**Comment by dzg** [comment]
(Also, just want to say, thank you for this, this is fantastic! Much better/faster/easier than all the others I tried. Spasiba!)

**Comment by ikvk** [comment]
> `for msg in mailbox.fetch():`
> 
> Then I only get back messages which are less than exactly 14 days old. I.e., yesterday I got messages starting from Aug 9. Today I'm getting from Aug 10.
> 
> I tried `date_gte=datetime.date(2023, 1, 1)` but that made no difference.

Do you see another emails with another client?

**Comment by ikvk** [comment]
> (Also, just want to say, thank you for this, this is fantastic! Much better/faster/easier than all the others I tried. Spasiba!)

Na zdorov'ye. Pozhaluysta. :D 

(For health. You are welcome.)

**Comment by dzg** [comment]
It was my fault :facepalm: 

Gmail IMAP settings were set to limit = 1,000.

Also I was checking `INBOX` not `All Mail`

So all good, thanks!
