### ISSUE TITLE
message.from_ parsing error

### ISSUE THREAD

**Issue by audemed44** [ikvk/imap_tools#21]
When the from header (the value in message.headers['From']) contains the following:
('"Firstname, Lastname"' <email@xyz.com>) 

the message.from_ only contains -> "Firstname

I got around this by sending this message.headers['From'] value as an argument to the email.utils.getaddresses function as a workaround.

**Comment by ikvk** [comment]
can you give me a src part of this .eml with this headers?

**Comment by ikvk** [comment]
*of course without confidencial data

**Comment by ikvk** [comment]
fixed https://github.com/ikvk/imap_tools/releases/tag/v0.13.0

**Comment by ikvk** [comment]
Thanks for help, Aakash Shrivastava. May the force come with you )
