### ISSUE TITLE
mailbox.fetch(A(limit=1, seen=False)) - error when trying to get 1 single unseen mail

### ISSUE THREAD

**Issue by mmcatbox** [ikvk/imap_tools#213]
mailbox.fetch(A(limit=1, seen=False)):
TypeError: LogicOperator.__init__() got an unexpected keyword argument 'limit'

Is there a way to get 1 single unseen mail using imap_tools?

Thanks

**Comment by ikvk** [comment]
limiе is arg for fetch

**Comment by mmcatbox** [comment]
So the answer 'No' - imap_tools cannot get 1 single unseen mail?

**Comment by ikvk** [comment]
it can

answer is "limit is arg for fetch, not for A"

**Comment by mmcatbox** [comment]
Good to hear.
Rather than talk about it, what the actual code?

**Comment by ikvk** [comment]
do you insist that you don't need to turn on your brains?

**Comment by mmcatbox** [comment]
Resorting to insults is a bad look...

Means your package cannot even do a simple thing like get 1 unseen mail.
You can simply post the fetch code if the package is able.

So the answer is: No, imap_tools cannot get 1 single unseen mail.

This thread also suggests that this package is not well supported (without insults).

**Comment by ikvk** [comment]
How gentle we are.
I gave a specific answer, if you don't want to comprehend it, that's your problem.
