### ISSUE TITLE
Document testing setup

### ISSUE THREAD

**Issue by link2xt** [ikvk/imap_tools#215]
I have created `credentials.ini` in the `tests` folder with the contents similar to this:
```
[EXAMPLE]
host=example.org
email=alice@example.org
password=foobar
path_separator=/
test_folder=INBOX
```

I also modified `TEST_MAILBOX_NAME_SET`:
https://github.com/ikvk/imap_tools/blob/f735d8e71dcf9ae4bef754be8c909b232051a00d/tests/utils.py#L7
Set it to `{"EXAMPLE"}`.

The tests still fail with errors like "Mailbox doesn't exist: INBOX.base (0.001 + 0.000 secs)." and "Mailbox doesn't exist: INBOX.temp1 (0.001 + 0.000 secs).". Am I supposed to create these folders manually?

**Comment by ikvk** [comment]
Yes - manually, hands do not reach to automate it =)

**Comment by ikvk** [comment]
*Also often it is just impossible - to create stuff for test by programm.
