### ISSUE TITLE
New property for HTML content charset

### ISSUE THREAD

**Issue by stumpylog** [ikvk/imap_tools#216]
I'm happy to implement this, but I wanted to discuss the solution a little and make sure there's not a better way.

While investigating paperless-ngx/paperless-ngx/issues/4297 I've gotten an email message file with an HTML portion.  The HTML includes a header of `<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">`.  However, when the `msg.html` property is used to write the HTML into a file, imap_tools does not (yet) provide a way to write with the correct encoding to the file.

So, when the string is decoded to UTF-8 by `decode_value`, the printed values look fine.  But when the HTML is written to a file, the UTF-8 values are rendered by a browser as iso-8859-1 and end up with incorrect characters.  it should be 
![image](https://github.com/ikvk/imap_tools/assets/797416/fa43e0f8-a0dc-4f1d-8273-dc22a6cb8f4e) but instead looks like 
![image](https://github.com/ikvk/imap_tools/assets/797416/518205f6-ab46-49b1-84ea-00fc74a458e2)

My proposed solution would be storing the return of `part.get_content_charset()` and allowing access to it via a new property `html_content_charset`.  This would allow a write to file to utilize this as the `encoding=`.  Any other better ways to handle this?  Changing the actual HTML isn't an option, as we try to archive the original as much as possible.

**Comment by ikvk** [comment]
Interesting, may you give me .eml example?

**Comment by stumpylog** [comment]
The user was able to provide this on: https://github.com/paperless-ngx/paperless-ngx/files/12816937/Testing.aao.in.emails.from.MS.txt

I'm not even convinced this is valid HTML actually.  But anyway.

**Comment by ikvk** [comment]
I understand what you mean, I propose such a solution:

https://github.com/ikvk/imap_tools/pull/217/files

I think this is exactly what everyone expects to see.
What do you think?

**Comment by stumpylog** [comment]
That works great for me.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v1.4.0

Thanks again @stumpylog
