### ISSUE TITLE
Encoding issue with message headers

### ISSUE THREAD

**Issue by stumpylog** [ikvk/imap_tools#218]
Sorry, back with another odd case related to encoding values.  Got to love dealing with Unicode.

Given [this email file](https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/paperless_mail/tests/samples/simple_text.eml), reading the headers of the message returns the "cc" key with some `\u` in the email addresses.  This probably stems from the special characters in the email, encoded with `surrogateescape`.

I think UTF-8 characters are now allowed in email addresses, so I believe these are valid as emails.  Would it be possible to decode these to a UTF-8 string?  This would perhaps apply to all the header values.

If this file isn't actually valid by what you understand emails can be, feel free to close this out.

**Comment by stumpylog** [comment]
I do see the `cc_values` and `cc` appear correct, so that's good.  But the intention here is to extract the metadata of a message, mostly using the headers in this case.

**Comment by ikvk** [comment]
If you mean decode values in msg.headers, so it will not be decoded.

msg.headers are considered as convenient way to access raw data, if imap_tools dot not do enough.
