### ISSUE TITLE
How to get just the body of the email and drop any reply information.

### ISSUE THREAD

**Issue by jslovern391** [ikvk/imap_tools#219]
I would like to just get the body of the new incoming email and none of the reply information.  Is this possible?

**Comment by ikvk** [comment]
Strange question.
Email has two base body variants:
msg.text and msg.html

example:
https://github.com/ikvk/imap_tools#id4

_please_ calculate for me (no offense): 
2 + 2 * 2

**Comment by jslovern391** [comment]
The question about the body was based on seeing it as a search criterion.  What I saw was the header information in the body of replies.  As for the second question, is there a way to separate the new message from the replies?

**Comment by jslovern391** [comment]
I have successfully parsed in Python what I want.  The question now is does the move criteria just 'ALL' or can it be the current emails uid?

mailbox.move(mailbox.uids(), 'Read')

**Comment by jslovern391** [comment]
Figure it out.

**Comment by jslovern391** [comment]
I figured it out.
