### ISSUE TITLE
Filename of attachment could not be read correctly if it not base64-encoded really.

### ISSUE THREAD

**Issue by Docpart** [ikvk/imap_tools#220]
Lib:
imap_tools 1.4.0

Message fragment:

--700a69b5f03bd7443d8b63cdbee5af84288ac0d46e85d633eae993e85834
Content-Disposition: attachment; filename="0 дней.xls"
Content-Transfer-Encoding: base64
Content-Type: application/vnd.ms-excel; name="0 дней.xls"

As we see, filename is "0 дней.xls" right in message src.
When I try to download this file using imap_tools, I retrieve att.filename like "0 ��������.xls". At the same time, file content is downloaded correctly.

I suspect, that the issue with filename is caused by not encoded filename in message src. Or may be some other cause?

**Comment by ikvk** [comment]
May you take me an .eml that can reproduce the problem?

**Comment by Docpart** [comment]
> May you take me an .eml that can reproduce the problem?

Yes, sure
[Uploading Наличие+МСК.zip…]()

**Comment by Docpart** [comment]
[Наличие+МСК.zip](https://github.com/ikvk/imap_tools/files/13242916/%2B.zip)
That's it

**Comment by ikvk** [comment]
Would you like to make a PR? :D

**Comment by Docpart** [comment]
No, I'm desperate) I have spent a whole day in order to fix the issue. I tried everything. But I still at the same point.

**Comment by ikvk** [comment]
@Docpart , check it https://github.com/ikvk/imap_tools/releases/tag/v1.5.0

**Comment by Docpart** [comment]
> @Docpart , check it https://github.com/ikvk/imap_tools/releases/tag/v1.5.0

Wow! I have installed by pip. It works!) Thank you!
