### ISSUE TITLE
Get message/delivery-status content

### ISSUE THREAD

**Issue by CyrosX** [ikvk/imap_tools#221]
Is it possible to get the message/delivery-status content of delivery error mail?
The msg.text output is similar to this:

```
This is the mail system at host XXX.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<XXX>: host
    XXX[IP] said: 550 5.7.1 rejected by DMARC policy
    for XXX, servertime=Nov 11 12:48:14,
    server=XXX, client=IP (in reply to end
    of DATA command)
```

But it is missing the whole report, starting with:
`Reporting-MTA: dns; XXX`

msg.html / msg.attachment is empty.

**Comment by ikvk** [comment]
Usually that report may coming as simple email. Or maybe not come.
I do not know about standarts for it.
Also see here https://github.com/ikvk/imap_tools/issues/155

**Comment by CyrosX** [comment]
I've tried this small code snippet: [https://stackoverflow.com/a/5300759](https://stackoverflow.com/a/5300759)
and was able to get this kind of mail. Maybe this can be used for the implementation?

**Comment by ikvk** [comment]
I will explore it

**Comment by ikvk** [comment]
Example:
```
from imap_tools import MailBox, AND
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    for msg in mailbox.fetch():
        for att in msg.attachments:
            print(type(att.part))
            print('-- filename', att.filename)
            print('-- payload', att.payload)
            print('-- payload decode', att.payload.decode())
```

**Comment by ikvk** [comment]
may you give me .eml example ?
