### ISSUE TITLE
Multiple or conditions do not work with GMX

### ISSUE THREAD

**Issue by mcico** [ikvk/imap_tools#222]
Good Afternoon,

I started using imap_tools to filter mails over various mail accounts (e.g. fastmail, gmx).

I want to filter out mails from various senders, and to do so, I do the following
`(OR(from_=["@icloud.com", "no-reply@netdata.cloud"]`

When I use this criteria to get mails from Fastmail they are correctly filtered, but when I do the same with GMX, **all** mails are returned instead of the ones that match the from criteria.

In #162 the explanation was given that not all imap servers can handle the logical operators properly according to RFC3501. Maybe GMX has troubles to handle this query, is there a way I can get around that except of handling the criteria myself in the code? Not sure if adding parenthesis would even help in this situation.

cheers & thanks,
marco

**Comment by ikvk** [comment]
1. 
> is there a way I can get around that except of handling the criteria myself in the code

in lib - no, but handling the criteria by hands - it is not bad ).

2. 
you cat try various cases for criteria at GMX:
```
mailbox.fetch('TEXT "hello"')          # str
mailbox.fetch(b'TEXT "\xd1\x8f"')      # bytes
```
May be you can find reason of fail or bug at GMX.

**Comment by ikvk** [comment]
*Greet )

**Comment by mcico** [comment]
Thanks for the answer, I will check it out and let GMX know if they can fix it on their side.
