### ISSUE TITLE
Seen flag after move of message to subfolder

### ISSUE THREAD

**Issue by bakotomas** [ikvk/imap_tools#224]
Hello, please, I need advice how to preserve unseen flag on msg after move them to subfolder. This example doesn't work for me. Message is moved, but lost unseen attribute:

                   if mail_domain in self.domain_rules:                    
                        uid = msg.uid                                                        
                        isSeen = imap_tools.MailMessageFlags.SEEN in msg.flags
                        dest = mailbox.move(uid, f'INBOX/{self.domain_rules[mail_domain]}')    
                        if isSeen != True:
                              if imap_tools.MailMessageFlags.SEEN in msg.flags:
                                    flags = msg.flags
                                    flags.remove(imap_tools.MailMessageFlags.SEEN)  
                                    mailbox.flag(dest, flags)

**Comment by ikvk** [comment]
Greet

1. use fetch mark_seen argument
2. if it not help (but it must) - just set flags
3. isSeen -> is_seen
