### ISSUE TITLE
uid keyword criteria doesn't work

### ISSUE THREAD

**Issue by jairuigou** [ikvk/imap_tools#225]
I have tied the [keyword_criteria](https://github.com/ikvk/imap_tools/blob/master/examples/keyword_criteria.py) example:
```
mailbox.fetch(A(uid=uids))
```
but its result is same as mailbox.fetch().It appears that it doesn't filter based on the uids list and still returns all of my emails.

python version i used: 3.11.6
imap_tools version: 1.5.0

**Comment by ikvk** [comment]
check uids type
I have checked it and all works.

```
for msg in mailbox.fetch(A(uid=['360'])):
    print(msg.date, msg.uid)
```

**Comment by ikvk** [comment]
If it is still not works - write your email server name

**Comment by jairuigou** [comment]
> If it is still not works - write your email server name

Thanks for the reply!
I found that `A(uid=['360'])` returns "(UID 360)". But "(UID 360)" dosen't work with`imaplib.IMAP4.client.uid(commands....)` in my environment. And if I use "UID 360" without brackets like this: 
```
for msg in mailbox.fetch("UID 360", limit=2):
    print(msg.date, msg.uid)
```
I am not very familiar with the usage of imaplib, and it seems that the UID criteria **wrapped in parentheses** does not work for me.
My email server name is: "imap.exmail.qq.com"

**Comment by ikvk** [comment]
Thanks, @jarugu 
I hope your experience will useful for people. 
What is you environment?

**Comment by jairuigou** [comment]
> Thanks, @Jarugu I hope your experience will useful for people. What is you mail server?

imap.exmail.qq.com
