### ISSUE TITLE
how to search subject using chinese characters?

### ISSUE THREAD

**Issue by Icy-Cat** [ikvk/imap_tools#226]
I tried to serch specific msg with chinese characters, but it did work, how can i solve this problem?

**Code:**

with MailBox('outlook.office365.com').login('email', 'password') as mailbox:
    for msg in mailbox.fetch(AND(subject='请验证')):
        print(msg.date, msg.subject, len(msg.text or msg.html))
        
 **i got this error traceback:**
 
 Traceback (most recent call last):
  File , line 5, in <module>
    for msg in mailbox.fetch(AND(subject='请验证')):
  File , line 160, in fetch
    uids = tuple((reversed if reverse else iter)(self.uids(criteria, charset)))[limit_range]
  File ", line 118, in uids
    encoded_criteria = criteria if type(criteria) is bytes else str(criteria).encode(charset)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-12: ordinal not in range(128)

**Comment by ikvk** [comment]
Please, read docs carefully my friend.

mailbox.fetch(A(subject='жёлтый 请验证'), charset='utf8')

**Comment by Icy-Cat** [comment]
Sorry to bother again , I tried to use your example code to run, there is still some problem.
**Code**
from imap_tools import MailBox, AND
# Get date, subject and body len of all emails from INBOX folder
with MailBox('outlook.office365.com').login('mail', 'pwd') as mailbox:
    for msg in mailbox.fetch(AND(subject='请验证'), charset='utf8'):
        print(msg.date, msg.subject, len(msg.text or msg.html))
        
**Traceback (most recent call last):**
  File "", line 5, in <module>
    for msg in mailbox.fetch(AND(subject='请验证'), charset='utf-8'):
  File "G:\Anaconda\lib\site-packages\imap_tools\mailbox.py", line 160, in fetch
    uids = tuple((reversed if reverse else iter)(self.uids(criteria, charset)))[limit_range]
  File "G:\Anaconda\lib\site-packages\imap_tools\mailbox.py", line 119, in uids
    uid_result = self.client.uid('SEARCH', 'CHARSET', charset, encoded_criteria)
  File "G:\Anaconda\lib\imaplib.py", line 890, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "G:\Anaconda\lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "G:\Anaconda\lib\imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'Command Error. 11']

Is this indicating that the imap server does not support the way i search subject using chinese characters?
I will appreciate your help!

**Comment by ikvk** [comment]
Try 1.0.0 version, may be you server not support UID command
