### ISSUE TITLE
Response status "OK" expected, but "NO" received. Data: [b'[UNAVAILABLE] UID FETCH Server error - Please try again later']

### ISSUE THREAD

**Issue by davidjhall** [ikvk/imap_tools#229]
Trying to move all messages with 2023 from yahoo mail into an archive directory but after a while it gives the above error:
imap_tools.errors.MailboxFetchError: Response status "OK" expected, but "NO" received. Data: [b'[UNAVAILABLE] UID FETCH Server error - Please try again later']

with MailBox("imap.mail.yahoo.com").login(
        "xxxxx@yahoo.com", "xxxxxxxxxx",initial_folder='INBOX'
    ) as mailbox:
        mailbox.move([msg.uid for msg in mailbox.fetch() if msg.date.year == 2023 ],"Archive/2023")

**Comment by ikvk** [comment]
Try to reduce email batch at one time

**Comment by ikvk** [comment]
* at fetch() by limit arg or criteria
* at move - by hands )
