### ISSUE TITLE
How to do exact from_ and to search

### ISSUE THREAD

**Issue by tilkov** [ikvk/imap_tools#23]
Hi,

This might be the configuration of my IMAP server (Dovecot backed by Solr) or the IMAP protocol itself, but when i search for...
```
client = 'user@example.com'
for msg in imap.fetch(OR(to=client, from_=client)):
    ...
```

... i get the results for `user@example.com`, but also for `"User <other@example.com>"` like the search string is split into parts and they match.

Is this expected? How do i get the results where msg.from_ or msg.to is exactly what i need?

**Comment by ikvk** [comment]
Hi. This is IMAP logic. https://tools.ietf.org/html/rfc3501#section-6.4.4

**Comment by tilkov** [comment]
Thank you, i will add a check if `from_values` or `to_values` contain the exact email address i am searching for.

**Comment by ikvk** [comment]
I am not sure about "search string is split into parts and then match.", but I checked OR search logic on my side and everething is ok.

**Comment by tilkov** [comment]
Doing a check if 'email' is exactly the search string for `to` or `from_`

```
for msg in imap.fetch(OR(to=client, from_=client)):
    if client == msg.from_values['email'] or any(client == to['email'] for to in msg.to_values):
        ...
```
