### ISSUE TITLE
`examples/pysocks_proxy.py` outdated?

### ISSUE THREAD

**Issue by qb-0** [ikvk/imap_tools#232]
When I try to run the current example it fails with `TypeError: Imap4SslProxy.open() takes from 1 to 3 positional arguments but 4 were given`

**Comment by ikvk** [comment]
It is related with python version. (fix like in MailBox._get_mailbox_client) You can help lib by make MR.

**Comment by luiistavares** [comment]
What version its stable, for work pysocks_proxy.py?

**Comment by ikvk** [comment]
@luiistavares , I have never use it byself, and actually it is not a part of lib. If you have some fixes for it - welcome.
