### ISSUE TITLE
Getting error with some parameters

### ISSUE THREAD

**Issue by Beltarm** [ikvk/imap_tools#235]
I'm getting an UID error in two different scenarios

This is the normal search:

`mailbox.fetch(AND(from_='normal_email'), limit=1)`

It works well

but when I try with `mailbox.fetch(AND(from_='normal_email', subject='subject with é character'), limit=1, charset='utf8')` I get this error:

`imaplib.IMAP4.error: UID command error: WRONG [b'Could not parse command']`

And with `mailbox.fetch(AND(from_='normal_email'), limit=1, sort=SortCriteria.DATE_DESC)` I get this:

`imaplib.IMAP4.error: UID command error: BAD [b'Unknown command: UID SORT']`

**Comment by ikvk** [comment]
1. This is related to criteria https://github.com/ikvk/imap_tools/issues/88
2. Public mail server rarely supports sorting. I have not seen that on practice.
