### ISSUE TITLE
i can get sender name?

### ISSUE THREAD

**Issue by qwertyqwert12** [ikvk/imap_tools#236]
how i can get sender name? first name, last name

**Comment by ikvk** [comment]
msg.from_values

of course it is not guarantee, more robust - ask the sender )

**Comment by qwertyqwert12** [comment]
> msg.from_values
> 
> of course it is not guarantee, more robust - ask the sender )

THANKS!!!!

**Comment by qwertyqwert12** [comment]
> msg.from_values
> 
> of course it is not guarantee, more robust - ask the sender )

i can get references? :D 
or only from headers?

**Comment by ikvk** [comment]
From headers
