### ISSUE TITLE
Can't access any other folder than INBOX

### ISSUE THREAD

**Issue by Preetraj2002** [ikvk/imap_tools#237]
I tried to navigate to SENT folded.

![image](https://github.com/ikvk/imap_tools/assets/92105160/a6a666c8-5c98-4c82-8466-c1f83fbfdef2)

But it shows this error and it's the issue with every other folder.

**Comment by Preetraj2002** [comment]
I am basically trying to fetch a thread conversation, but i am only able to fetch upcoming mails(INBOX) of the thread and not the mails that i sent. So i am not able to fetch the whole thread.

**Comment by ikvk** [comment]
Try to see all folders by: mailbox.folder.list('INBOX')
