### ISSUE TITLE
folder exists check function misbehavior

### ISSUE THREAD

**Issue by zssng** [ikvk/imap_tools#243]
`mailbox.folder.exists` check `"70 发票/lli哦i哦 噢"` folder always return `False`， even if it exist

**Comment by ikvk** [comment]
hi, ill see it

**Comment by ikvk** [comment]
I have checked it and it works. 
Try to check delimiters, for example for YANDEX box name will be: 
`folder_name = '70 发票|lli哦i哦 噢'`
Delimiter is "|"

**Comment by zssng** [comment]
I can create subfolder with `"70 发票/lli哦i哦 噢"`, just can't check if it exists

**Comment by ikvk** [comment]
Try to run with debugger. What mailbox provider?

**Comment by zssng** [comment]
[exmail.qq.com](https://exmail.qq.com/)

**Comment by ikvk** [comment]
```
folder_name = '70 发票|lli哦i哦 噢'
for f in mailbox.folder.list():
    print(f.name)
print('exists:', mailbox.folder.exists(folder_name))
```

> INBOX
> 70 发票
> 70 发票|lli哦i哦 噢
> ...
> exists: True

Try to see at debugger, it is interesting - what is wrong.

**Comment by ikvk** [comment]
@zssng, whats news )?

**Comment by zssng** [comment]
![image](https://github.com/user-attachments/assets/be2a780f-4dc4-4e64-993b-45a0c6f4728d)
![image](https://github.com/user-attachments/assets/ade31da1-403e-4491-be83-07cd4b44f4eb)
![image](https://github.com/user-attachments/assets/a67ac154-d8db-4455-acec-e8a89509eff1)
it seems like list func return None

**Comment by ikvk** [comment]
Try to run code like this:
`mailbox.folder.list('', 'INDEX')`
Is it works?

Then some more complex:
`mailbox.folder.list('', 'INDEX/123')`
...
