### ISSUE TITLE
Error processing MailAttachment content_id

### ISSUE THREAD

**Issue by homoLudenus** [ikvk/imap_tools#245]
Got error:
  File ".local/lib/python3.10/site-packages/imap_tools/message.py", line 286, in content_id
    return self.part.get('Content-ID', '').lstrip('<').rstrip('>')
AttributeError: 'Header' object has no attribute 'lstrip'

possible fix:

```
@property
@lru_cache()
def content_id(self) -> str:
    header_obj = self.part.get('Content-ID')
    if header_obj:
        return decode_value(*decode_header(header_obj)[0]).lstrip('<').rstrip('>')
    return ''
```

Environment:
Linux 5.15.0-122-generic #132-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
Python 3.10.12
imap-tools 1.7.3

**Comment by ikvk** [comment]
May you give me .eml with cutted secrets?

**Comment by ikvk** [comment]
*For add tests

**Comment by ikvk** [comment]
Thanks, good luck.
https://github.com/ikvk/imap_tools/releases/tag/v1.7.4
