### ISSUE TITLE
set proxy

### ISSUE THREAD

**Issue by ox-blueblue** [ikvk/imap_tools#246]
Does the tool support setting up proxies? If no proxy is set for batch query of accounts, ip addresses may be restricted

**Comment by ikvk** [comment]
Try to see here:
https://github.com/ikvk/imap_tools/issues?q=proxy

Lib do not restrict nothing, you may implement any proxy.
If then you provide an uniq example, I will be happy.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/tree/master/examples
