### ISSUE TITLE
'MailMessage' object has no attribute 'reply_to'

### ISSUE THREAD

**Issue by nathan30** [ikvk/imap_tools#25]
Hi,

On the PyPI doc I can see there is a "reply_to" into Mailbox object. But when I try to access it I have the following error : 

'MailMessage' object has no attribute 'reply_to'

Any ideas ?

Thanks

**Comment by ikvk** [comment]
What version are you use ?

**Comment by ikvk** [comment]
So, there is no answer - there is no problem =). I think you are using old version.
