### ISSUE TITLE
Receiving emails

### ISSUE THREAD

**Issue by Ray94520** [ikvk/imap_tools#251]
So I'm trying to figure out two things
first I'm trying to figure out how to get a total count of unseen emails
second thing is when emails are retrieved they come in as
name@Gmail.com so how do I not include
@Gmail.com I would like to just receive the name
is this possible

**Comment by Ray94520** [comment]
PS
I did figure out how to do the total number of emails 
now I just need help with the second one

**Comment by ikvk** [comment]
```
    msg.from_values      # imap_tools.EmailAddress | None
    msg.to_values        # tuple: (imap_tools.EmailAddress,)
    msg.cc_values        # tuple: (imap_tools.EmailAddress,)
    msg.bcc_values       # tuple: (imap_tools.EmailAddress,)
    msg.reply_to_values  # tuple: (imap_tools.EmailAddress,)
    # EmailAddress(name='Ya', email='im@ya.ru')  # "full" property = 'Ya <im@ya.ru>'
```

**Comment by Ray94520** [comment]
Well thank you very much for your reply

I did see that settings in your documentation but I did not quite understand it
but I did figured it out by using what you gave me i put this together msg.from_values.name
and it gave me exactly what I needed thank you very much for your help I appreciate it
