### ISSUE TITLE
Could you implement the IMAP4_SSL starttls() function ?

### ISSUE THREAD

**Issue by nathan30** [ikvk/imap_tools#26]
Could you implement the IMAP4_SSL starttls() function ?

**Comment by ikvk** [comment]
MailBox has public attr "box", so have you tried to do something like mailbox.box.starttls() ?

**Comment by nathan30** [comment]
Oh nice, I didn't see the "box" attr. Thanks

**Comment by ikvk** [comment]
I plan to put the mailbox access protocols in a separate module, and then add them to the documentation
