### ISSUE TITLE
Intermittent UnexpectedCommandStatusError from mailbox.fetch()

### ISSUE THREAD

**Issue by danielmroberts** [ikvk/imap_tools#28]
When looping over fetch, every few or dozens of passes will result in error. 

```
with MailBox('outlook.office365.com').login('xxx', 'xxx') as mailbox:
	for message in mailbox.fetch():
		# do something
```
quickly or eventually results in...

*UnexpectedCommandStatusError(imap_tools.utils.UnexpectedCommandStatusError: Response status for command "box.fetch" == "NO", "OK" expected, data: [b'The specified message set is invalid.']*

- Python 3,8.1
- imap-tools==0.13.1

I have added a while loop with catch to try again on error, but I want to make sure there isn't something else going on.

Are there any known issues with certain services or reasons this might be happening?

**Comment by ikvk** [comment]
What happens in other code? When code runs?

**Comment by ikvk** [comment]
*In many years in the prod I have not encountered such an error

**Comment by danielmroberts** [comment]
Could it be due to moving messages while looping over fetch? Should I collect changes needed and then move outside of the fetch loop?

**Comment by ikvk** [comment]
Probably Yes. I always collect the necessary changes and perform actions like move after fetch loop. This is not a bug of lib. This is IMAP )

**Comment by ikvk** [comment]
I will add more examples for this case
