### ISSUE TITLE
space in folder names causing issues

### ISSUE THREAD

**Issue by atlas0fd00m** [ikvk/imap_tools#30]
i'm running into errors in handling folder names with spaces.

```
with MailBox('imap.mail.com').login('test@mail.com', 'pwd') as mailbox:
    mailbox.folder.exists("INBOX/foo/bar baz")
```
returns

```error: LIST command error: BAD [b'Error in IMAP command LIST: Extra arguments (0.001 + 0.000 secs).']```

this is *not* a problem with .set and .create, which makes it very interesting to role through and create based on criteria, but only if a folder doesn't exist.

thanks!

**Comment by ikvk** [comment]
fixed https://github.com/ikvk/imap_tools/releases/tag/v0.14.1
