### ISSUE TITLE
Limit issue?

### ISSUE THREAD

**Issue by oaigudmundsson** [ikvk/imap_tools#31]
Let say your inbox has 90 emails. And your code is 
```
for msg in mailbox.fetch(limit=100):
    print(msg.uid)
```

It seems to stuck in the loop. 

Here is the trace when i stop the debug:

```
 line 99, in fetch
    fetch_result = self.box.fetch(message_id, "(BODY[] UID FLAGS)" if mark_seen else "(BODY.PEEK[] UID FLAGS)")
  File "/usr/lib/python3.6/imaplib.py", line 534, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "/usr/lib/python3.6/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.6/imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.6/imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.6/imaplib.py", line 1094, in _get_response
    data = self.read(size)
  File "/usr/lib/python3.6/imaplib.py", line 305, in read
    return self.file.read(size)
KeyboardInterrupt
```

**Comment by ikvk** [comment]
How does this relate to the limit argument? It has a trivial logic

**Comment by oaigudmundsson** [comment]
Well, when i use limit=1, the loop does execute fine. 

Cheers

**Comment by ikvk** [comment]
I checked case when limit greater then email count - works, I do not see stuck reason at library side. Any suggestions?

**Comment by oaigudmundsson** [comment]
I am debugging. Will post later for more result.

Cheers

**Comment by oaigudmundsson** [comment]
Ok, another quick test

Work
```
mails = mailbox.fetch(Q(from_="system@mailcompany.com", seen=False, new=True), limit=100)
mails = mailbox.fetch(Q(seen=False, new=True), limit=100)
```

Not Work:
```
mails = mailbox.fetch(Q(new=True), limit=100)
mails = mailbox.fetch(limit=100)
```

My mailbox has about 1000 emails. There are unseen + seen emails. Too much to handle?

**Comment by ikvk** [comment]
Email server may bun you or restrict some frequent things. Is there any code between your fetches? Any way seems that server just stop responce.

**Comment by oaigudmundsson** [comment]
No, i don't see any issue with restrict or query to often. This code works 
mails = mailbox.fetch(Q(seen=False, new=True), limit=100)` as expected now.

One question, i see you have this option:
`:param mark_seen: mark emails as seen on fetch`

So, let say i run this `mailbox.fetch(Q(seen=True), limit=100)`, would it mark the email already as **seen** to **seen** again?


Cheers

**Comment by ikvk** [comment]
> would it mark the email already as seen to seen again?
If you mean unnecessary work, I think it depends on email server

**Comment by ikvk** [comment]
Note, semantically your code written incorrectly

```
mails = mailbox.fetch(Q(new=True), limit=100)
mails = mailbox.fetch(limit=100)
mails = mailbox.fetch(Q(seen=True), limit=100) # limit 2 same error as well
```

Not _mails_, just _mail generators_.
Anyway this code works, even though it doesn't make sense. I checked it on diferent email servers.

Do you have new info about stuck?

**Comment by oaigudmundsson** [comment]
Hi, no i could not figure out why, the only possible the code could not mark already seen mails and stuck in loop? Or the inbox has too many seen emails that i takes forever to loop through.

**Comment by ikvk** [comment]
1. mark_seen arg mean - email server mark emails as seen on fetch (imap FETCH).
2. If your fetch query contains too many emails, you can restrict it for example by date - date_gte=..., also you can move unneded to anoter folder.
3. Be sure that you understand how generators works.
4. I do not now when your code runs and what it actually do?

**Comment by oaigudmundsson** [comment]
Hello, 
1. Ok i understand this
2. It works, for me, when i only fetch the unseen emails.
3,4. I understand generators. It's same problem even if i use the for-loop
```
    for msg in mailbox.fetch(limit=100):
        try:
            print(msg.uid)
        except:
            pass
```
I used generator because i can debug by `list(emails)`. 


Cheers

ps: thanks for imap_tools, great work!

**Comment by ikvk** [comment]
Good luck =)
