### ISSUE TITLE
Attachment filename is being partially lost

### ISSUE THREAD

**Issue by unqx** [ikvk/imap_tools#33]
Hi, I've detected a problem with the `filename` property of the `Attachment` class. 

Sometimes I get the following result while decoding attachment filename:

```
In [37]: decode_header(attach_message.get_filename())
Out[37]: [(b'Contract ', 'utf-8'), (b'27 04 20.docx', None)]
```

The `filename` property decodes and returns the first element from the list which is

```
In [24]: mails[0].attachments[0].filename
Out[24]: 'Contract '
```

I suggest the change in the following pull request: https://github.com/ikvk/imap_tools/pull/32

Thank you!

**Comment by ikvk** [comment]
May you give me part of email body that cause it issue?
For example :
------==--bound.887287.myt5-262fb1897c00.qloud-c.yandex.net
Content-Disposition: attachment;
	filename="yandex_email.eml"
Content-Transfer-Encoding: base64
Content-Type: message/rfc822;
	name="yandex_email.eml"

**Comment by ikvk** [comment]
*for add to tests

**Comment by unqx** [comment]
@ikvk 

Is that what you asked for?

```
--5ea6d902_12200854_b3e4
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64
Content-Disposition: attachment; 
 filename="=?utf-8?Q?Contract_?=27 04 20.docx"
```

**Comment by ikvk** [comment]
Yes, thanks for help. Good luck, tovarisch!
