### ISSUE TITLE
error when using search function for arcor.de imap

### ISSUE THREAD

**Issue by thesalah1212** [ikvk/imap_tools#34]
subjects = [msg.text for msg in mailbox.fetch(Q(subject='weather'))]
`UnexpectedCommandStatusError              Traceback (most recent call last)
<ipython-input-21-2060134890e8> in <module>
      1 print(mailbox.folder.get())
----> 2 subjects = [msg.text for msg in mailbox.fetch(Q(subject='weather'))]

<ipython-input-21-2060134890e8> in <listcomp>(.0)
      1 print(mailbox.folder.get())
----> 2 subjects = [msg.text for msg in mailbox.fetch(Q(subject='weather'))]

~\Anaconda3\lib\site-packages\imap_tools\mailbox.py in fetch(self, criteria, charset, limit, miss_defect, miss_no_uid, mark_seen, reverse)
     90         """
     91         search_result = self.box.search(charset, self._criteria_encoder(criteria, charset))
---> 92         check_command_status('box.search', search_result)
     93         message_id_set = search_result[1][0].decode().split(' ') if search_result[1][0] else ()
     94         # first element is string with email numbers through the gap

~\Anaconda3\lib\site-packages\imap_tools\utils.py in check_command_status(command, command_result, expected)
     45         raise UnexpectedCommandStatusError(
     46             'Response status for command "{command}" == "{typ}", "{exp}" expected, data: {data}'.format(
---> 47                 command=command, typ=typ, data=str(data), exp=expected))
     48 
     49 

UnexpectedCommandStatusError: Response status for command "box.search" == "NO", "OK" expected, data: [b'[SERVERBUG] Internal error occurred. Refer to server log for more information. [2020-05-06 15:40:57] (0.001 + 0.000 secs).']`

**Comment by ikvk** [comment]
In my opinion the error is obvious. The server may be blocking the search, or the server may be broken

**Comment by thesalah1212** [comment]
I don't know but it is working in another no open source project

**Comment by ikvk** [comment]
Write to arcor.de admins about [SERVERBUG]
