### ISSUE TITLE
Questions about the fetch method

### ISSUE THREAD

**Issue by MattiaFailla** [ikvk/imap_tools#35]
Hello! 

I have some problems with the following code. Where am I wrong? I'm expecting to see the Subject of the most recent Unseen message but it is not working. Thanks in advance!

```
from imap_tools import MailBox

with MailBox('imap-mail.outlook.com').login('<mymail>', '<mypassword>') as mailbox:
                messages = mailbox.fetch('(UNSEEN)', mark_seen=False)
                for msg in messages:
                	print(msg.subject)
```

**Comment by MattiaFailla** [comment]
Further investigation make me think that the problem is either with the management of the `mark_seen` flag or with limitations of Outlook:

```
from imap_tools import MailBox, Q

with MailBox('imap-mail.outlook.com').login('<mymail>', '<mypassword>') as mailbox:
                messages = mailbox.fetch(criteria=Q(seen=False), mark_seen=False, miss_defect=False, miss_no_uid=False)
                for msg in messages:
                	print(msg.uid)
                	print(msg.subject)
```
It returns:
```
None
Test
```

**Comment by ikvk** [comment]
I will try to reg acc and run tests on it at free time.

**Comment by MattiaFailla** [comment]
> I will try to reg acc and run tests on it at free time.

Thank you. 
Please note that without the `mark_seen` flag everything works like expected.

**Comment by ikvk** [comment]
I have reproduced this behavior, think that is ms "feature" for untrusted clients. If you will continue investigating and find more info, I will be happy to see issue/mrequest. I do not found any useful info in web.
