### ISSUE TITLE
Unable to access GSuite mail

### ISSUE THREAD

**Issue by cboden** [ikvk/imap_tools#36]
Is there anything in particular required to get imap_tools working with a GSuite (Google) email account? I followed Google's instructions by enabling IMAP on my account and created an "App password" which allows programs like this access. 

```python
from imap_tools import MailBox, MailMessage, Q

mailbox = MailBox("imap.gmail.com")
mailbox.login(
    "admin@mycustomdomain.com",
    "my16charapppswrd",
    initial_folder="INBOX",
)
```

> imaplib.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

I have also used this App Password technique with http://improvmx.com where it was able to properly connect to Gmail.

**Comment by ikvk** [comment]
https://www.google.com/settings/security/lesssecureapps

**Comment by cboden** [comment]
From [Google's documentation](https://support.google.com/mail/answer/7126229?hl=en) is says it supports secure IMAP clients. I followed all their steps up to to point of 
> The email client's sign-in method might be insecure.

Can this library be improved to the point Google doesn't mark it as a security vulnerability?

**Comment by ikvk** [comment]
Good question, have you explored ways to solve this problem?

**Comment by cboden** [comment]
I haven't, sorry. I have no understanding of the IMAP protocol.

**Comment by ikvk** [comment]
Возможно предупреждение исчезнет, если использовать более безопасную технологию входа, например ключи ssl.

Не думаю что у гугл есть база доверенных приложений.
https://support.google.com/accounts/answer/6010255/

**Comment by ikvk** [comment]
In any case, this mechanism is not part of the imap Protocol.
