### ISSUE TITLE
Support for getting back all messages in a thread?

### ISSUE THREAD

**Issue by naclander** [ikvk/imap_tools#37]
First, thank you for this great library, it definitely simplifies using imap over some other libraries in python land.

I've been trying to use this to be able to download all messages in a thread ( reply-to chain ), and the only way I've been able to do this was via searching the Header for a `In-Reply-To` message-id from the first email, or via the `References` Header field ( although that has been less reliable ).

I was wondering if `imap_tools` provided and easier way to do this, and if not whether that's something that would be good to implement?

**Comment by ikvk** [comment]
Hi, Key question: how do I do this without the imap_tools library? 
As far as I understand, it is not possible to do this universally by now. 

https://stackoverflow.com/questions/16816425/

I think you're taking the right approach.

**Comment by naclander** [comment]
Correct, it's a pain to do this manually, and requires manually iterating over all messages. I was just wondering if this was something imap_tools wanted to provide.

Ideally I would like to do this without making a server call for each email in the thread, potentially.

**Comment by naclander** [comment]
So from my research the most efficient way to do this is probably:

If IMAP server supports Threading Algorithm ( usually it would say something like `THREAD=` in `CAPABILITIES` then:
Use https://docs.python.org/3.8/library/imaplib.html#imaplib.IMAP4.thread
Else if Mail Server is Gmail ( popular enough to support ), use Gmail's terrible non-standard `X-GM-THRID` https://developers.google.com/gmail/imap/imap-extensions#access_to_the_gmail_thread_id_x-gm-thrid
Since Gmail doesn't support threading in their custom IMAP server implementation.
Else:
Need to manually build up the thread. This is inefficient and so `imap_tools` probably doesn't want to support this.

**Comment by ikvk** [comment]
Now I do not plan to implement this functionality. It is quite difficult to support and has different implementation methods. In any case, anyone can re-open the ticket and we will discuss this topic in more detail.

**Comment by elithompson** [comment]
Related: I needed to get the Gmail thread ids from messages and was able to subclass `Mailbox` to get it like this:
```python
import re
from typing import Iterable, Sequence
from imap_tools import MailBox


class Mbox(MailBox):
    def _fetch_in_bulk(self, message_nums: Sequence[str], message_parts: str, reverse: bool) -> Iterable[list]:
        # attach the X-GM-THRID flag so Gmail returns the values
        message_parts = message_parts.replace(")", " X-GM-THRID)")
        return super(Mbox, self)._fetch_in_bulk(message_nums, message_parts, reverse)


def get():
    thrid_search = re.compile(r"X-GM-THRID (\d+)")
    with Mbox("imap.gmail.com").login("example@example.com", "password") as mb:
        messages = mb.fetch(bulk=True)
        for message in messages:
            d = message._raw_uid_data.decode("utf-8")
            result = re.search(thrid_search, d)
            thrid = result.groups()[0]
            print(message.uid)
            print("\t GmThrid:", thrid)
```
