### ISSUE TITLE
Attachment without a name is not recovered

### ISSUE THREAD

**Issue by upils** [ikvk/imap_tools#38]
When using the outlook feature "Forward email as an attachment", the attached mail did not get a name.

So, as https://github.com/ikvk/imap_tools/blob/master/imap_tools/message.py#L191 cannot find a name, the attachment is skipped.

I proposed to give a default name to this attachment that could be "mail_attachment_XX" with `XX` being the index of the unnamed attachment found (the first one found will be `mail_attachment_1`, etc.).

Moreover, once we encounter this unnamed attachment (with `Content-Type: message/rfc822`, what is parsed is not the initial mail but a forwarded one. And the following attachments will be attachment to this second mail, not the initial one.

**Comment by ikvk** [comment]
May you provide for me src of this email (cutted, if need) ?

**Comment by upils** [comment]
Associated PR https://github.com/ikvk/imap_tools/pull/39

**Comment by ikvk** [comment]
I wrote my version https://github.com/ikvk/imap_tools/releases/tag/v0.16.0

**Comment by ikvk** [comment]
Thank you for participating!

**Comment by upils** [comment]
It is good for me, thanks.
