### ISSUE TITLE
does not extract attached EML files

### ISSUE THREAD

**Issue by TpyoKnig** [ikvk/imap_tools#4]
As .EML files have these headers:

`--00000000000094809105878daac0
Content-Type: message/rfc822; name="Totally legit email (2).eml"
Content-Disposition: attachment; filename="Totally legit email (2).eml"
Content-Transfer-Encoding: base64
Content-ID: <f_jv0apprb0>
X-Attachment-Id: f_jv0apprb0

MIME-Version: 1.0
Date: Fri, 25 Jan 2019 10:37:47 -0800
Message-ID: <CAKKXz3O5qFoTi68Ls4QCqZzQK8m6mASymTZ9ib6ysnBTOwwJOg@mail.gmail.com>
Subject: Totally legit email
From: REDACTED <REDACTED@DOMAIN.COM>
To: REDACTED <REDACTED@DOMAIN.COM>
Content-Type: multipart/alternative; boundary="000000000000a30bb605804c9ff2"

--000000000000a30bb605804c9ff2
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable`

imap-tools does not return this as an attachment and completely disregards the attachment itself along with the filename.

**Comment by ikvk** [comment]
I'll see it on days. Have you any suggestions?

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/commit/4d447b744fa52b16f69f335cfc7ace3766f692cf
it should work now
