### ISSUE TITLE
How to read only headers?

### ISSUE THREAD

**Issue by daitangio** [ikvk/imap_tools#40]
Hi, can you provide an example in the documentation on this topic:
_How to fetch only email headers in a loop?_
I was unable to figure how to use the query language with fetch() to get it
Thank you

**Comment by ikvk** [comment]
You can not do it now. But will, soon.

**Comment by daitangio** [comment]
Thank you...It would help a lot a my side projects. I was able to build a small mailbox synchronizer using imap_tools, and in the past I wrote all the code using  only the basic python API...it was a bit hard.
I like a lot this library  :)

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.16.0

**Comment by ikvk** [comment]
Thank you for participating!
