### ISSUE TITLE
Ability to fetch only certain components instead of entire message?

### ISSUE THREAD

**Issue by naclander** [ikvk/imap_tools#44]
Fetching messages is great, but sometimes I only want certain parameters, and it seems like a waste to download the entire message if I only want a few parameters. It's also much faster to only download say, the subject, instead of the entire message if I'm only interested in the subject.

Does imap_tools support only fetching certain parameters for speed purposes?

I ideally would want the equivalent of:
```
a = mailbox.box.uid('fetch', "$UIDS", "BODY.PEEK[HEADER.FIELDS (SUBJECT)]")
```

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.16.0 headers_only arg.

**Comment by naclander** [comment]
I'm still seeing a significant performance difference when trying to run my command above, vs using the `headers_only=True` flag. 

Would it be possible to select only which headers to chose?

**Comment by ikvk** [comment]
"to select only which headers to chose" - in this case message parser may be broken. I will ckeck work on change message_parts

**Comment by ikvk** [comment]
What do you mean at "significant performance". Are you want less network load or less time to do?
I tested 3 variants, and got avg time of 10 fetches:
    # message_parts='(BODY.PEEK[HEADER.FIELDS (SUBJECT DATE FROM)] UID)' 3.24 sec
    # headers_only=True 2.96 sec
    # all 3.23 sec
Seems not actual for time.

**Comment by ikvk** [comment]
code is here https://github.com/ikvk/imap_tools/tree/message_parts

**Comment by ikvk** [comment]
You can test it too

**Comment by naclander** [comment]
You're right. The speed is the same and I was confused from a different call. I'm going to go ahead and close this issue. Thanks for the help.

**Comment by ikvk** [comment]
And thank you, together we can do more )
