### ISSUE TITLE
Problem with PEC email attachments

### ISSUE THREAD

**Issue by labgua** [ikvk/imap_tools#45]
Hi and thank you for this best project :)
I created a ticket-service email based and it's a very lucky escape for imap lib python :D

So i've a problem when I receive a PEC email, all the information are visibile like date, from and subject but when I try to read the attachments my script throws this exception...

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/imap_tools/message.py", line 226, in attachments
    result.append((filename, codecs.decode(payload_item_bytes, cte)))
LookupError: unknown encoding: 7bit
```

This is a semplification of the script that I use and throws this exception :

```python
import datetime
from imap_tools import MailBox
import itertools

mailbox = MailBox('imap.gmail.com')
email_username = '******************'
email_password = '******************'

mailbox.login(email_username, email_password)

imap_criteria = "UNSEEN"

# suppose only one PEC email
mails = mailbox.fetch(imap_criteria)

# x.id      -> OK
# x.subject -> OK
# x.from_   -> OK

len(x.attachments)
```

I'm using Python3 and imap-tools (0.8.0)

I think it was a codec problem, what can I do to solve it?
Thanks in advance

**Comment by ikvk** [comment]
Hi.
Try last version: https://github.com/ikvk/imap_tools/releases
https://github.com/ikvk/imap_tools/blob/master/release_notes.rst
0.8.0 are very old

**Comment by ikvk** [comment]
If it is not help, you can send to me .eml file (cutted if need)

**Comment by ikvk** [comment]
Any news?

**Comment by labgua** [comment]
Hi,
Sorry for my absence... This problem appears resolved in the latest version.
I installed the last version of the package and now the test works fine! (I must make a little bit of refactoring on the access methods of the attachments..)

You can add PEC to the list of features, I'm sure it would be even more attractive for developers ;)

Thank you so much! :)

**Comment by ikvk** [comment]
=) Good luck!
