### ISSUE TITLE
Not getting all results when using headers_only

### ISSUE THREAD

**Issue by backelj** [ikvk/imap_tools#46]
Hi,

I wanted to get a quick list of the uids of messages in a mailbox. Using:

`msg_uids = [msg.uid for msg in mailbox.fetch()]`

I get a list with the uids for all messages in the mailbox, in length equal to:

`mailbox.folder.status()['MESSAGES']`

But when I do the same with:

`msg_uids = [msg.uid for msg in mailbox.fetch(headers_only=True)]`

I only get to see a few of them...

I would expect either all uids to be returned or none at all, since the uid is not a part of the headers, right?

Similarly, something like:

`for msg in mailbox.fetch(Q(uid=xxx),headers_only): print(msg.headers)`

only works for the uids from the list returned by the previous command.
Without the headers_only, it works for all the uids from that mailbox.

I have not yet looked into the imap_tools code, but I wanted to mention it here already anyway since this looks like strange behavior to me. At least, this is not what I would expect, and even if the usage seems strange (why would I need to use the uids when I can use Q to query), using the headers_only might perhaps also have other side-effects...

Best regards, Franky

**Comment by ikvk** [comment]
Hi
Behavior is strange, I do not face it before. 
I think need investigation here: 
- Try to run code without outside logic - is error here too?
- Watch in debugger to uid parser 
- Make sure to read about uid - https://tools.ietf.org/html/rfc3501#page-8

**Comment by ikvk** [comment]
*there are messages without a uid, such as a greeting when creating a mailbox

**Comment by backelj** [comment]
Well, I've tested with code like this:
```
mailbox.folder.set(<some_folder>)
status = mailbox.folder.status(<some_folder>)
print(<some_folder>, status['MESSAGES'], 'messages')
msg = mailbox.fetch()
count = 0
for i in msg: count += 1
print('fetched', count, 'messages')
msg = mailbox.fetch(headers_only=True)
count = 0
for i in msg: count += 1
print('fetched', count, 'messages')
```
And this gives:
```
<some_folder>: 18 messages
fetched 18 messages
fetched 4 messages
```
Shouldn't using "headers_only=True" without any other option give back all messages?

-- Franky

**Comment by ikvk** [comment]
What mail server are you using?

**Comment by ikvk** [comment]
reproduced everywhere =)
Have you any suggestions?

**Comment by backelj** [comment]
I have it with both our Exchange server and the iCloud IMAP server.
I don't have any suggestions yet, I'll have to dig into your code first.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.18.0
*headers_only disabled for now

**Comment by ikvk** [comment]
fixed https://github.com/ikvk/imap_tools/releases/tag/v0.20.0. Thanks!

**Comment by backelj** [comment]
Hi Vladimir,

Thanks a lot! There’s been a lot in-between, but I will check the changes somewhere next week.

-- Regards,

Franky



Van: Vladimir Kaukin <notifications@github.com>
Beantwoorden - Aan: ikvk/imap_tools <reply@reply.github.com>
Datum: vrijdag 28 augustus 2020 om 12:43
Aan: ikvk/imap_tools <imap_tools@noreply.github.com>
CC: Franky Backeljauw <franky.backeljauw@uantwerpen.be>, Author <author@noreply.github.com>
Onderwerp: Re: [ikvk/imap_tools] Not getting all results when using headers_only (#46)


fixed https://github.com/ikvk/imap_tools/releases/tag/v0.20.0<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fikvk%2Fimap_tools%2Freleases%2Ftag%2Fv0.20.0&data=02%7C01%7Cfranky.backeljauw%40uantwerpen.be%7Cb5a885430f7240bb942e08d84b3f30c9%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637342082063326903&sdata=DMuubWfbKVaJtc013IwdSjQg5ckiBpa9bLnbKcJ6H20%3D&reserved=0>. Thanks!
