### ISSUE TITLE
Exception handling, interfaces

### ISSUE THREAD

**Issue by frispete** [ikvk/imap_tools#47]
Hi,

your lib is quite nice already, as it solves a couple of ugly issues with imaplib.

OTOH, some areas remain improvable. 

Example: for an imap reorganization tool, I did:
```    
    def _select(self, mailbox):
        try:
            resp, data = self._imap.folder.set(mailbox)
        except imap_tools.utils.UnexpectedCommandStatusError as e:
            log.debug('select: %s', e)
            return False, 0
        if resp == 'OK':
            return True, int(data[0].decode('utf-8'))
        return False, 0
```

As you can see, this interface is no beauty as such. I needed a way to deal with non-existing folders properly (e.g. in order to create them later on), but this is obvious only after reading the source.

My tool relocates mails of a certain year into a sub folder. That way, mailboxes for mailing lists like LKML keep manageable.
Hence, I need to fetch uids, and move them. Unfortunately, search is implicitly combined in the fetch method of your lib.

Therefor:
```
        # fetch matching mails
        resp, items = self._imap.box.uid('SEARCH', None, '(SINCE 01-Jan-%s BEFORE 01-Jan-%s)' % (year, year + 1))
        if ret == 'OK':
            log.debug('items: %s', items)
        else:
            log.debug('search: %s %s', ret, items)
            raise ImapReorgError(ERRPROT, 'searching in mailbox <%s> failed' % mailbox)

        # copy matching messages
        nr = 0
        uids = [uid.decode('utf-8') for uid in items[0].split()]
        uidset = []
        limit = self._limit if self._limit is not None else len(uids)
        while uids:
            uidset = uids[:limit]
            log.info('move %s of %s messages to %s', len(uidset), len(uids), dest)
            uids = uids[limit:]
            nr += len(uidset)
            copyres, delres = self._imap.move(','.join(uidset), dest)
            if copyres[0] != 'OK':
                raise ImapReorgError(ERRPROT, 'copying failed: %s' % str(copyres))
            if delres[0][0] != 'OK':
                raise ImapReorgError(ERRPROT, 'deleting failed: %s' % str(delres))

        # messages copied, expunge mailbox
        if nr:
            ret, data = self._imap.expunge()
            if ret != 'OK':
                raise ImapReorgError(ERRPROT, 'expunge <%s> failed' % mailbox)
            log.info('moved %s messages from <%s> to <%s>', nr, mailbox, dest)
        else:
            log.debug('no message dates matched %s in <%s>', year, mailbox)
```

Please note, that the uid handling is not exactly pretty as well. Also, converting to a list in order to properly handle some limit only to generate a string from it, which you in turn split into a list again, is improvable as well.

While that it, the third line of [utils.py:cleaned_uid_set](https://github.com/ikvk/imap_tools/blob/master/imap_tools/utils.py#L20) is, hmm, unpalatable, to put it nicely.

What I've missed is an improved error handling. See the call to `self._imap.move` above, and its error handling.
Your documentation reflects this by mostly ignoring any return values.

My full code is available [here](https://github.com/frispete/imap_reorg/blob/master/imap_reorg.py).

I hope, that you don't misunderstand this note. I would like to show you real world application of your lib and shed some light on the rough corners of your lib.

**Comment by ikvk** [comment]
Greetings.

https://github.com/ikvk/imap_tools/releases/tag/v0.18.0

1. exeptions
added

2. about uids
uid and id not same thing
what is uid: https://tools.ietf.org/html/rfc3501#page-8 2.3.1.1.  
"id" was part of public api of email earlier, I removed it to avoid confusion

3. cleaned_uid_set
Optimized.
About: if inspect.isgenerator(uid_set) and getattr(uid_set, '__name__', None) == 'fetch':
Not perfect, but simple and short. Any suggestions for improvement?

**Comment by ikvk** [comment]
thank you for participating!

**Comment by frispete** [comment]
Sorry for the late answer, I was on holiday. 

Thanks for the exception improvements. I'm sure, this is welcomed by more users of your nice lib.

Hope, you don't mind, if I keep using this thread to discuss some further aspects. It's fine to keep it closed for me.

Imagine, you need to relocate millions of mails from one folder to another. Right now, we have two options:
* use `BaseMailBox.fetch()`, with the disadvantage to transfer the full parsed body
* avoid the fetch, as sketched up above, e.g. simply look up the uids and moves them accordingly

Be assured that with the first option you pay a large penalty in terms of runtime. 

Suggestion: further separate the search process from fetch, such as a user is able to make optimal use of server side look ups similar to my hacks above. While at it, be tolerant about the form of message lists: accept lists of ints and strings separated by spaces (similar to the reply of a search command). Right now, one needs to split the bytes reply of search by **spaces**, (optionally) decode to string, divide the set in palatable portions (to not overflow readline/server), and concatenate them again with **commas**. This all feels a little awkward. Again, see my quoted snippet above.

Do you think, that would be reasonable?

**Comment by ikvk** [comment]
1. If you need to relocate millions of mails, actually you have NO options =)

    The problem is that the server doesn't accept a very large command
    Error example for 22000 uids in yandex:
        * imap_tools.errors.MailboxCopyError: Response status "OK" expected, but "NO" received. Data: [b'command or literal size is too large']
    So, if you even get million uids, this will not help you.

    My approach for such tasks:
    use a bundle: limit arg for fetch and periodical tasks.
    This combination guarantees than even million emails will be processed


2. about uids, again:

    ID and UID are different entities
    example sets for single fetch:
        * ids: ['1', '2', '3', '4', '5', '6']
        * uids: ['1', '2', '3', '17', '18', '19']

    One optimization will be available after fix bug for BaseMailBox.fetch headers_only arg.
    Welcome to fix.
    https://github.com/ikvk/imap_tools/issues/46

    I will not plan for now to create separate methods for get ids/uids.
    I have not see strong reasons.


3. cleaned_uid_set

    Arg types good enough.
        * str, that is comma separated uids
        * Iterable, that contains str uids
        * Generator with "fetch" name, implicitly gets all uids
    Further func optimization is not essential.
