### ISSUE TITLE
Constructing imap_tools.MailMessage object from string export

### ISSUE THREAD

**Issue by amarkham09** [ikvk/imap_tools#48]
Hello,

This is the first time I've contributed on someone else's GitHub project, so my apologies if I have broken established etiquette in my ignorance.

Having spent a good few weeks wrestling with imaplib in vain, I am now using imap_tools into my project (an IMAP client which bulk downloads and archives emails in JSON format). I have quickly come to appreciate how much simpler it makes everything! 

I am writing two classes, a JSON Encoder and Decoder. The encoder class currently encodes imap_tools.MailMessage.obj property as a string using the as_string() method which imap_tools.MailMessage.obj inherits as an instance of the email.message.Message class.

However, when it comes to the Decoder class, I'd like this to recreate the MailMessage object using a constructor method, but currently, the only available options are constructing this from bytes.

As a result, I currently have to create an email.message.Message object from the string export, immediately convert it back into bytes, and then call the MailMessage constructor function. This seems very hack-y and not an efficient way of decoding emails in bulk.

```
import email, imap_tools

message_as_string = my_imap_mailmessage.obj.as_string()
...
bytes_string = email.message_from_string(message_as_string).as_bytes()
b = imap_tools.MailMessage([tuple(['', bytes_string])])
```

Would there be any support from the devs for creating a constructor method that would recreate a MailMessage object from its string representation? I would be happy to contribute to implementing this (although I am relatively unexperienced).

Thanks!

**Comment by ikvk** [comment]
Hi.

I think the right way is convert email.message.Message to bytes instead string.
*Anyway all strings consist of bytes.

I see that email.message.Message.as_bytes not trivial, may be something like this:
generator = email.generator.Generator(out_file)
generator.flatten(msg)

imap_tools.MailMessage has alternative constructor: from_bytes (*used in tests)

I not plan add from_string constructor.
This is beyond the scope of the lib.
from_bytes are in lib, cause it just like a "shortcut"

You can convince me otherwise.

**Comment by amarkham09** [comment]
Hi, thanks for your quick reply.

I now agree that the library does not need adding to.

For the sake of posterity, the alternative solution I settled on was:
```
import imap_tools
...
message_as_string = my_imap_mailmessage.obj.as_string()
bytes_string = bytes(message_as_string, 'utf-8')
b = imap_tools.MailMessage([tuple(['', bytes_string])])
```

It's a little messy, but does the job.

Thanks!

**Comment by ikvk** [comment]
*I see that you serialize uids, this is bad idea. Be sure that you read about it: 

https://tools.ietf.org/html/rfc3501#page-8 

2.3.1.1.        Unique Identifier (UID) Message Attribute
