### ISSUE TITLE
Error in parsing recipient email addresses containing non-ASCII characters

### ISSUE THREAD

**Issue by amarkham09** [ikvk/imap_tools#49]
I'm reporting a bug that I'm getting using `imap_tools`. I am trying to download an email using IMAP where the names of several recipients contain `ü` and `ö`. 

The error message is as follows (`email_to_json.py` is my own file):
```
File "/Users/Andrew/PycharmProjects/imapEmailArchiver/email_to_json.py", line 40, in default
    "to": obj.to,
  File "/Users/Andrew/PycharmProjects/imapEmailArchiver/venv/lib/python3.7/site-packages/imap_tools/message.py", line 118, in to
    return tuple(i['email'] for i in self.to_values)
  File "/Users/Andrew/PycharmProjects/imapEmailArchiver/venv/lib/python3.7/site-packages/imap_tools/message.py", line 112, in to_values
    return parse_email_addresses(self.obj['To'] or '')
  File "/Users/Andrew/PycharmProjects/imapEmailArchiver/venv/lib/python3.7/site-packages/imap_tools/utils.py", line 72, in parse_email_addresses
    for raw_name, email in getaddresses([raw_header]):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/email/utils.py", line 112, in getaddresses
    all = COMMASPACE.join(fieldvalues)
TypeError: sequence item 0: expected str instance, Header found
```

Attempting to inspect the `MailMessage.to` property while debugging results in the following error:

```
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1737-1738: surrogates not allowed
```

Because the `To` header contains recipient names containing these illegal characters, decoding it as `UTF-8` seems to fail (despite the fact these characters appear in the `UTF-8` spec). 

This seems to be a problem with `imap_tools` itself rather than my implementation of it; please correct me if I'm mistaken

**Comment by nixCodeX** [comment]
According to https://docs.python.org/3/library/email.compat32-message.html#email.message.Message.__getitem__ which of the to fields `self.obj['To']` returns is undefined, is there a reason you’re not using https://docs.python.org/3/library/email.compat32-message.html#email.message.Message.get_all and passing the full list to `getaddresses`?

**Comment by amarkham09** [comment]
@nixCodeX In this case, the message in question only had one `To` header, but multiple addressees, so I don't think that can be attributed as the cause of the error.

**Comment by amarkham09** [comment]
Looking into this issue further, the problem specifically seems to be arising when there is an `ö` character in the email address of one of the email recipients. The same problem does not apply when only the "name" field of `to_values` contains an `ö`.

**Comment by ikvk** [comment]
May you provide .eml file? (cutted if need)

**Comment by amarkham09** [comment]
The `To` header from the `.eml` file is as follow:

```
To: Peter Hore <peter.hore@chem.ox.ac.uk>, Christiane Timmel
	<christiane.timmel@chem.ox.ac.uk>, Stuart Mackenzie
	<stuart.mackenzie@chem.ox.ac.uk>, Justin Benesch
	<justin.benesch@chem.ox.ac.uk>, David Manolopoulos
	<david.manolopoulos@chem.ox.ac.uk>, Kevin Henbest
	<kevin.henbest@chem.ox.ac.uk>, Victoire Dejean
	<victoire.dejean@new.ox.ac.uk>, Marcin Konowalczyk
	<marcin.konowalczyk@chem.ox.ac.uk>, Jiate Luo <jiate.luo@ccc.ox.ac.uk>,
	Thomas Player <thomas.player@keble.ox.ac.uk>, Thomas Scrivener
	<thomas.scrivener@trinity.ox.ac.uk>, Angela Gehrckens
	<angela.gehrckens@ccc.ox.ac.uk>, Hang Zhou <hang.zhou@stx.ox.ac.uk>, Matthew
 Golesworthy <matthew.golesworthy@new.ox.ac.uk>, Jamie Gravell
	<jamie.gravell@new.ox.ac.uk>, Patrick Murton <patrick.murton@magd.ox.ac.uk>,
	Gediminas Pazera <gediminas.pazera@ccc.ox.ac.uk>, Yi Ren
	<yi.ren@chem.ox.ac.uk>, Yujing Wei <yujing.wei@merton.ox.ac.uk>, Ruby Lyons
	<ruby.lyons@magd.ox.ac.uk>, Andrew Markham <andrew.markham@new.ox.ac.uk>,
	Jessica Fleming <jessica.fleming@lincoln.ox.ac.uk>, Tommy Pitcher
	<tommy.pitcher@some.ox.ac.uk>, Gabriel Moise <gabriel.moise@new.ox.ac.uk>,
	Shane Chandler <shane.chandler@chem.ox.ac.uk>, henrik.mouritsen
	<henrik.mouritsen@uni-oldenburg.de>, Siu Ying Wong
	<siu.ying.wong@uni-oldenburg.de>, jingjing.xu <jingjing.xu@uni-oldenburg.de>,
	=?iso-8859-1?Q?Stefanie_K=E4sehagen?= <stefanie.kaesehagen@uni-oldenburg.de>,
	Jessica Schmidt <jessica.schmidt@uni-oldenburg.de>,
	=?iso-8859-1?Q?Dr=2E_Beate_Gr=FCnberg?= <beate.gruenberg@uni-oldenburg.de>,
	nadine.ruthenberg <nadine.ruthenberg@uni-oldenburg.de>,
	=?iso-8859-1?Q?Rabea=2EBart=F6lke=40uni-oldenburg=2Ede?=
	<Rabea.Bartölke@uni-oldenburg.de>
```

I hope this is what you wanted to know

**Comment by ikvk** [comment]
May you check it?  https://github.com/ikvk/imap_tools/releases/tag/v0.19.0

**Comment by frispete** [comment]
This one is suspicious:
```
=?iso-8859-1?Q?Rabea=2EBart=F6lke=40uni-oldenburg=2Ede?=
	<Rabea.Bartölke@uni-oldenburg.de>
```
As you can see, it carries an umlaut in the **email address** part. I'm pretty sure, that this email address is invalid, **even** if this would be encoded correctly.

**Comment by amarkham09** [comment]
@frispete Email addresses with non-ASCII characters are valid under SMTPUTF-8. Although not all email servers are able to send/receive emails to/from such addresses, they are valid:

https://tools.ietf.org/html/rfc6531#section-3.5

**Comment by frispete** [comment]
Ah, thanks for the update @amarkham09.

**Comment by ikvk** [comment]
So, is it works like expected?

**Comment by amarkham09** [comment]
I have only just got back to test it. Yes, v0.19.0 has fixed this bug. Thank you very much for sorting it so quickly! Marking this bug as closed.
