### ISSUE TITLE
Encrypted by default?

### ISSUE THREAD

**Issue by kst83** [ikvk/imap_tools#52]
Hi,

just wondering, are connections SSL encrypted by default?
If not, how do you activate encryption?

Best regards

**Comment by mbednarski** [comment]
AFAIK MailBox uses SSL.
If you need to not use it there is `MailBoxUnencrypted` class

**Comment by heitorPB** [comment]
`MailBox` uses SSL. But the examples do not follow Python's [Security Considerations](https://docs.python.org/3/library/ssl.html#ssl-security).

It should be something like this:

```python
context = ssl.create_default_context()
with MailBox(imap_host, imap_port, ssl_context=context).login(email, passw, 'INBOX') as mailbox:
    ...
```
