### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by andyfensham** [ikvk/imap_tools#53]
I love the simplicity of your imap_tools.  It works very well.

What I wanted to find out how would I page through a huge amount of emails.  I see you can limit the amount of emails it should bring back, but I can not find where to page through it.  For e.g. Page 1 Limit 100, Page 2 Limit 100 etc.

**Comment by ikvk** [comment]
Tell me about use case

**Comment by ikvk** [comment]
Check it https://github.com/ikvk/imap_tools/releases/tag/v0.22.0

**Comment by ikvk** [comment]
Please let me know is it fits?

**Comment by ikvk** [comment]
One more release: https://github.com/ikvk/imap_tools/releases/tag/v0.23.0

**Comment by ikvk** [comment]
End of monolog
