### ISSUE TITLE
Adding proxy support?

### ISSUE THREAD

**Issue by chwba** [ikvk/imap_tools#54]
What would be required to add proxy support?

**Comment by chwba** [comment]
im blind xD

**Comment by ikvk** [comment]
Let me know if you check https://github.com/ikvk/imap_tools/blob/master/examples/pysocks_proxy.py

**Comment by ikvk** [comment]
link for others: https://github.com/ikvk/imap_tools/issues/24

**Comment by chwba** [comment]
Actually, I would love to test it  but I am unsure regarding how to implement it, could you provide me an example snippet?

**Comment by ikvk** [comment]
I haven't tried using a proxy and this code, so, I have no snippet =)

**Comment by chwba** [comment]
Im trying to implement it now, opened an issue at pysocks: https://github.com/Anorov/PySocks/issues/146

**Comment by ikvk** [comment]
I'll take a look

**Comment by chwba** [comment]
I can give you some emails to test, if you need.

**Comment by ikvk** [comment]
I can see one, send on my email

**Comment by ikvk** [comment]
I fixed pysocks_proxy.py, you may try to check it. (*I still have not checked it)

**Comment by ikvk** [comment]
Any news?

**Comment by chwba** [comment]
Im waiting for them over at pysocks to respond. luminati.io is one of the biggest players in the proxy market, so I dont understand the error 403 that is coming from pysocks on connect.

**Comment by ikvk** [comment]
Thanks, I will be waiting for end of investigation.

**Comment by ikvk** [comment]
Closing it for now. Feel free to reopen it if needed.

**Comment by chwba** [comment]
It seems nobody cares over at pysocks sadly and I dont know how to address this issue because im sure its not the proxy-provider, lumminati is one of the biggest in the world.
