### ISSUE TITLE
requesting a new public attachment attribute of "content_disposition"

### ISSUE THREAD

**Issue by mwherman95926** [ikvk/imap_tools#55]
First, let me thank you for your well designed imap_tools python library.  It is very elegant and effective.  Thank you for all of your efforts.

I have a code request for the attachments section of messages.py. 

Specifically, I am requesting a new public attachment attribute of "content_disposition".   When I look at messages.py, there are three attributes for attachments: filename, content_type, and payload.  All are located around line 243 of messages.py.   And I see you using 'Content-Disposition' during your attachment walk on line 215.  So maybe there is a way that I am missing.  However, I have not figured out a way to call that attribute of content_disposition. The reason I need this is pretty simple.  I am looking for a way to determine if an attachment is inline or attached so I can download the files as needed..  Here is an example of one of my emails.

--000000000000f6524605af620d7c
Content-Type: image/jpeg; name="image001.jpg"
Content-Disposition: **inline**; filename="image001.jpg"
Content-Transfer-Encoding: base64
Content-ID: <17493fb11c24ce8e91>
X-Attachment-Id: 17493fb11c24ce8e91

verses

--000000000000f6524705af620d7d
Content-Type: application/pdf; name="SKMBT_C65420091513480.pdf"
Content-Disposition: **attachment**; filename="SKMBT_C65420091513480.pdf"
Content-Transfer-Encoding: base64
Content-ID: <17493fb11c332794c592>
X-Attachment-Id: 17493fb11c332794c592

The inline images shows up in the HTML.  It is an image of the person's email signature.  The other is an attachment to the email.  I am looking for a way to differentiate between the two.

Thank you in advance and I appreciate you taking the time

**Comment by ikvk** [comment]
Check it https://github.com/ikvk/imap_tools/releases/tag/v0.22.0
