### ISSUE TITLE
Working with read only mailboxes

### ISSUE THREAD

**Issue by NicolasCARPi** [ikvk/imap_tools#57]
Hello,

I'm trying out your tool, it's nifty :) Thank you!

On fastmail.com you have the option to generate an "app" password, and to give it restrictive permissions, like read-only.

When I use a read-only access, I cannot do a `mailbox.fetch()`. It raises the readonly error.

I tried with `mark_seen=False`, without success.

Is it possible to access a mailbox in read-only? I just want to get the subjects, nothing more. I'm using the default basic example.

**Comment by ikvk** [comment]
Greetings, May you show me an error?

**Comment by NicolasCARPi** [comment]
Sure:

~~~python
Traceback (most recent call last):
  File "./imap.py", line 10, in <module>
    with MailBox('imap.fastmail.com').login('username', 'password') as mailbox:
  File "/home/ktr/.local/lib/python3.7/site-packages/imap_tools/mailbox.py", line 33, in login
    self.folder.set(initial_folder)
  File "/home/ktr/.local/lib/python3.7/site-packages/imap_tools/folder.py", line 45, in set
    result = self.mailbox.box.select(self._encode_folder(folder))
  File "/home/ktr/.pyenv/versions/3.7.5/lib/python3.7/imaplib.py", line 755, in select
    raise self.readonly('%s is not writable' % mailbox)
imaplib.readonly: b'"INBOX"' is not writable
~~~

**Comment by ikvk** [comment]
Strange, I thought self.folder.set is not write... I have no idea, if you find solution, let me know. 

As I see, imaplib.IMAP4.select supports readonly, may be a bug there?

**Comment by NicolasCARPi** [comment]
From the [imaplib doc](https://pymotw.com/2/imaplib/#searching-for-messages), it looks like you can add `readonly=True` to a `select()` call on the connection. I'm not familiar with your code, but maybe you could add it to whatever function is used to list folders so that it is passed on to the imaplib function call? (or maybe in the login call?)

**Comment by ikvk** [comment]
Try to experiment with imap_tools code, I need to now what is going wrong. Actually I have experience with use read only mailbox, all was fine.

**Comment by ikvk** [comment]
I think you can override MailBoxFolderManager.set and then override BaseMailBox.folder_manager_class. I do not know how to detect that mailbox is  readonly. IMAP4.select readonly False guaranties that folder selected, I will not change it.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.26.0 Maybe it will useful for you

**Comment by NicolasCARPi** [comment]
thanks @ikvk I'll try it.
