### ISSUE TITLE
Fetched email without uid.

### ISSUE THREAD

**Issue by wangzhuoxuan** [ikvk/imap_tools#58]
Why some emails I fetched without the uid? But I can get its uid by the mailbox.search func.

**Comment by ikvk** [comment]
You can get email numbers by mailbox.search, this is not uids. Uid parsing not ideal, you can watch data in debugger, also you can paste BaseMailBox._fetch_by_one fetch_result[1] data here.

**Comment by ikvk** [comment]
And aslo there are emails without uid, I met such, for example - welcome email in inbox after create it.

**Comment by wangzhuoxuan** [comment]
@ikvk Thanks. I think I get it.

**Comment by ikvk** [comment]
*I bug there, let me know.
