### ISSUE TITLE
TypeError from email if from is None

### ISSUE THREAD

**Issue by parchd-1** [ikvk/imap_tools#6]
My inbox contains a spam message for which obj["from"] is None.
from_values() calls decode_header(self.obj['from']), which fails with

```
/usr/lib/python3.7/email/header.py in decode_header(header)
     78                     for string, charset in header._chunks]
     79     # If no encoding, just return the header with no charset.
---> 80     if not ecre.search(header):
     81         return [(header, None)]
     82     # First step is to parse all the encoded parts into triplets of the form

TypeError: expected string or bytes-like object
```

I am not sure what the correct action is - is it an upstream bug, or is it a bug here because imap_tools should never call this function when from is missing? If the second of these is true, what should happen? Probably the bug is with the client that sent the spam, but well behaved users shouldn't suffer for this. I leave it in your capable hands because for my current simple requirement I will just remove the email and carry on. Thank you.

**Comment by ikvk** [comment]
Bug, I will fix it soon. Thanks for feedback =)

**Comment by ikvk** [comment]
fixed
