### ISSUE TITLE
loss msg.html

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [ikvk/imap_tools#63]
msg.html is Empty
but 
msg.text has a value 

Is this a problem? 

How can I fix it 
or 
How to judge  

![image](https://user-images.githubusercontent.com/24671601/94634538-e44cfa00-0302-11eb-92f1-53e34bbcdf9f.png)

**Comment by ikvk** [comment]
Inspect your eml and you will know is it problem. Actually this is absolutely normal. And use search engine, this is really simple question, and not related to imap_tools only, but to emails entities at all
