### ISSUE TITLE
Add jwz threading support

### ISSUE THREAD

**Issue by naclander** [ikvk/imap_tools#66]
The [threading algorithm from JWZ](https://www.jwz.org/doc/threading.html) as implemented [here](https://github.com/FreeDiscovery/jwzthreading) would be a great addition to this library. In this way, messages can be threaded on the client side.

**Comment by ikvk** [comment]
Hi, I will see it.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/compare/imp_treader

Seems good. I described the interface, Are you ready to work for the benefit of open source?

**Comment by naclander** [comment]
@ikvk Thanks for agreeing to add this to `imap_tools`! Not sure what you meant by your question. Is there anything specific you want me to test? Were you thinking of copying the implementation, or just taking a dependency on the library that I linked?

**Comment by ikvk** [comment]
@naclander, I suggest that you implement the jwz algorithm with the interface I described in the imp_treader branch

**Comment by naclander** [comment]
Wouldn't it be easier to leverage the work done by this package here? https://github.com/FreeDiscovery/jwzthreading

**Comment by ikvk** [comment]
This is exactly what I did, taking into account the imap_tools entities. It remains to implement all the steps in the private methods of ThreadBuilder or just in ThreadBuilder._build

**Comment by naclander** [comment]
I meant take the `jwzthreading` package as a dependency? Or is that what you mean? Sorry if I'm misunderstanding.

**Comment by ikvk** [comment]
jwzthreading seems like just a draft, I do not see reason to add it as dependency. Have you looked at the branch?

**Comment by naclander** [comment]
I've used the package I linked and it seems to work fairly well. 

I have looked at the branch, and implementing the jwz threading algorithm from scratch would fit in there. However I was more thinking of utilizing the existing written code. I suppose copying the `jwzthreading` package into `imp_reader` would work, it just feels like duplicated effort.

**Comment by ikvk** [comment]
jwzthreading 1. has unneded here code 2. not works with native lib types 3. most likely I will not add the dependency

**Comment by ikvk** [comment]
1. May you tell me about your use case?
2. Which interface more convenient?

**Comment by naclander** [comment]
So right now for a test project, I use `imap_tools` to download the specific messages I want. Then for each message I just use `jwzthreading.Message` and `jwzthreading.thread` to sort them. 

I wasn't saying that the interface you made is bad, just that I don't want to have to duplicate the work that was done in the `jwzthreading` package.

**Comment by ikvk** [comment]
Anyone, feel free to implement it.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/tree/imp_treader
