### ISSUE TITLE
can't get attachment by msg.attachments

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [ikvk/imap_tools#68]
Here's a picture attachment

I can't get it by msg.attachments

here's my msg.obj

`
Return-Path: <test@foxmail.com>
X-Original-To: qmebi@contoso.app
Delivered-To: qmebi@contoso.app
Received: from qq.com (unknown [113.96.223.80])
	by mail.contoso.app (Postfix) with ESMTP id DD4B62140DD4
	for <qmebi@contoso.app>; Wed, 21 Oct 2020 03:34:11 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=foxmail.com;
	s=s201512; t=1603251251;
	bh=bZSz/mtqfdz94kmtGaFYXC+YAQiOxaGFSWBJgZKsdU4=;
	h=From:To:Subject:Mime-Version:Date:Message-ID;
	b=bHrL4mJuop2NculsqdAgtZBTFjvA8VK2WqfJwn4MqmVpNUvfUQ/OyCzC7WAG2DjDq
	 NhaAt5+61RCFDBKuv2NVx7xyH7xPTI0xVrCbUZinXDQQ53r6vBwP08jwx4GaP+b4k6
	 WYypqGbGKA2pDDUKmsABkHWdG2QbANM0YDCLnlBM=
X-QQ-FEAT: AU3gs7VM8fUm1shbPQ2y/acBleNQwil+zNLsynIgszFw26Mnhh/EwwA+B+R36
	yfTKfZtupqkoghvYDKTdaoIJHPvl3hwvMYCK5O0pgoIgbwuFYw2V5fn3Gldt7UXsU6U7tyH
	wqWfCV4fZ445hfnnbUWSDNVElNzvEyQ+KXbeWoY8wscD6YadaE8uZDImlxSshpPqQ6QZ+Hv
	LAH0CFTPcbU0pVX7JZWe+yehkkfGa8pNbg2udDcM+l2It8FiRxZE1Dd/e+eLR6ZeHxrSdcF
	zsYA==
X-QQ-SSF: 00000000000000F100000000000000J
X-QQ-XMAILINFO: MKhv4vGKTxZzZwBiOOWzJjOs1CMM2urx0EOWlCdHAK4tftFk+6UX7CdZHFmrau
	 guT9pUXQHsD4SoKYAbJJgAkezWTcclYEtZ5xC4nTjAObSp7hATM9Wz70KG1uocKqaXQT7MJP0sc9c
	 bpSK6QNPNd3+j7/BptWtYSJjEQSs7BFqvSDf3T7b1gPmf14cCPF4OGaIV332nu7Yfv6UeJDuMtM8E
	 V8WKUfbWqjedOX7j/4mx94I9GBJK7MwebhIqqVST1wrdrAckfU+wzSRmn+GsvqRnYuog5vBEtUjMW
	 dHVOpXPD3GtA0tqfs3mbYyV45ix3wR5P3AQQoVgyyFiIMVWW2Ro/pCCxW4t8IGJLDWtm7SE1x+n5l
	 ovf0oGXFRVI14LDD6ANU8IspSEEhCNBy8VY8j4nAIbME2fbMvnlP65Ypa9e7HpLYcaJryAp/z0qh2
	 qUVXkbM7NBGR/gQfTjUa9HduSGNfUAdrPy/PCFyUr6TzuKfWdv1oaHe5muNm91NtaCZdPcy+bTNYf
	 oI6eyoMTJflL8zriZXN7PjVgtZBrRkuGLDBBphNYVLKnqW0Pf9UQf46pCuQvvneVPqSb3pSzoy+O2
	 fiO8+pRyy/J/L9YrHExFlgz38D8S1qYzUq5nGEBOvkTiaJZfu/ie5Gmv0a8W0CkWEqmNgGCg556Wr
	 cSs9YFvPuleEF6mSFSzbj7R1dz4Q==
X-HAS-ATTACH: no
X-QQ-BUSINESS-ORIGIN: 2
X-Originating-IP: 112.80.214.47
X-QQ-STYLE: 
X-QQ-mid: webmail615t1603251249t9058947
From: "=?ISO-8859-1?B?c2g=?=" <test@foxmail.com>
To: "=?ISO-8859-1?B?cW1lYmk=?=" <qmebi@contoso.app>
Subject: test
Mime-Version: 1.0
Content-Type: multipart/related;
	type="multipart/alternative";
	boundary="----=_NextPart_5F8FAC31_11789E80_23290B52"
Content-Transfer-Encoding: 8Bit
Date: Wed, 21 Oct 2020 11:34:09 +0800
X-Priority: 3
Message-ID: <tencent_DF1A0C2499D7CA259C7FB26CDFCB49C60809@qq.com>
X-QQ-MIME: TCMime 1.0 by Tencent
X-Mailer: QQMail 2.x
X-QQ-Mailer: QQMail 2.x
X-QQ-SENDSIZE: 520
Received: from qq.com (unknown [127.0.0.1])
	by smtp.qq.com (ESMTP) with SMTP
	id ; Wed, 21 Oct 2020 11:34:10 +0800 (CST)
Feedback-ID: webmail:foxmail.com:bgweb:bgweb17

This is a multi-part message in MIME format.

------=_NextPart_5F8FAC31_11789E80_23290B52
Content-Type: multipart/alternative;
	boundary="----=_NextPart_5F8FAC31_11789E80_5FCFFC0B";

------=_NextPart_5F8FAC31_11789E80_5FCFFC0B
Content-Type: text/plain;
	charset="ISO-8859-1"
Content-Transfer-Encoding: base64

------=_NextPart_5F8FAC31_11789E80_5FCFFC0B
Content-Type: text/html;
	charset="ISO-8859-1"
Content-Transfer-Encoding: base64

PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0L2h0bWw7IGNo
YXJzZXQ9R0IxODAzMCI+PGRpdj48aW1nIHNyYz0iY2lkOkY3NjM2MUZDQEUzQzUyMTVGLjMx
QUM4RjVGLnBuZyIgc3R5bGU9IiIgaWQ9ImltZ19pbnNlcnRfMTYwMzI1MTI0NjI0MDA1MDE4
Mjg5MjE5NDk5NDU5Ij48YnI+PGJyPjwvZGl2Pg==

------=_NextPart_5F8FAC31_11789E80_5FCFFC0B--

------=_NextPart_5F8FAC31_11789E80_23290B52
Content-Type: image/jpeg;
	name="F76361FC@E3C5215F.31AC8F5F.png.jpg"
Content-Transfer-Encoding: base64
Content-ID: <F76361FC@E3C5215F.31AC8F5F.png>

iVBORw0KGgoAAAANSUhEUgAAAHMAAAAxCAYAAADp05aBAAADWklEQVR4Ae2bQWgTQRSG/2hB
DFSkqVDJQYoXJZf05CF0IeRmbx4CAW+BQiB47Cl4KDnlJKUQCPQmiAF7qwdBigk5eFKEkBYJ
olJasPGgEPEgkdnspjuzCdZOsG/GFwjJm52dvPd/897ODptI5fnhAPyyQoELVkTBQbgKMEyL
JsLM++4Hi8L5v0OJDAYDvmZaMge4zFoCUoTBMBmmRQpYFApnJsO0SAGLQuHMtAjmjBpLv9/H
lx8X1Wa2CSlw7fIvRKPRkEfSfebH3s9QB26gq8CN2CXJuVGZFRnJL7MUUJmNYHJpNQuk8FZl
NoJpXijssaoAw1QVMdhmmAbDU11nmKoiBtsM02B4qusMU1XEYJthGgxPdT20nad2+Od2r4WH
pTaawR92HOwmu0hvHARbve+zKJVzyMSGZvtJDcUGkH+wivu35bbl7D2sp+fHjAGMO090nNQ+
dpBzbqSbmQJg1UFeEUgA2a2uuu9NRzmIPbxpiLY4ljyQwkok427HZv012uopFtn0MlNH3E4X
W+J85yqOKjUUQ8+qHaBYqJ38wmICz9ZSmDtpMfqbVTDbb4dlOJ9MIZNLIXMGNFsbteGEUM6V
2kXVyN1Sepy/SRdmo4G0WzJlkZr1baTrcptr9Vp4Guw/7tornRbHZnUFCalNvtYqh8ibdGG6
sx94XGhImRJcxPiLE6Fy+4WyaIqlsF5NkQcwTQfpwtSN8oyZKZVTyQd51SwdImIYB3NSmb2+
EEcpC5Tr3u3LX2XmMY4+CyLjSu9eqDoQYRdywxiYw8WNnB3BMjuXXkGms4OyH2JnZ8J9qd8h
AK63j1di5evcDF1D/d4mfNKFKS2Aut794xUseJsDpxY3tPI8xsvKNsqB25av7z65mxT5JL0V
6qnjBEAX5giCJz6A5eydQOb4pfEPgN1JEVzmKvL0WnhU/w4sJnA3sNGg9DLCpAczdK2bR2bN
wWGhiyWxFacsbGTAYzQfTQr/mJyZw1XwLEp58zcPRk/n8ZN5PmyzPoNP6NHdmzVLUxLeMkwS
GKbjBMOcjo4kRok09r/xP6dJoNB3gjNTX0MyIzBMMij0HWGY+hqSGYFhkkGh7wjD1NeQzAgM
kwwKfUcYpr6GZEZgmGRQ6DvCMPU1JDMCwySDQt+R3/9y7MbbsB7rAAAAAElFTkSuQmCC

------=_NextPart_5F8FAC31_11789E80_23290B52--
`

**Comment by ikvk** [comment]
```
    from imap_tools import MailMessage
    with open('1.eml', 'rb') as f:
        bytes_data = f.read()
    msg = MailMessage.from_bytes(bytes_data)
    print(msg.date_str)
    print(msg.obj.defects)
```

`>>> [MissingHeaderBodySeparatorDefect()]`

**Comment by SamGenTLEManKaka** [comment]
I'm sorry

I changed some privacy information

This is my real document

[1.zip](https://github.com/ikvk/imap_tools/files/5414339/1.zip)

**Comment by ikvk** [comment]
same error, do not be so lazy!

**Comment by SamGenTLEManKaka** [comment]
I didn't report a mistake here

I uploaded it again


![image](https://user-images.githubusercontent.com/24671601/96706593-5fb53f00-13c9-11eb-8c3e-7d5f011167ca.png)

[2.zip](https://github.com/ikvk/imap_tools/files/5415129/2.zip)

**Comment by ikvk** [comment]
No defects now. Any suggestions after debugging MailMessage.attachments ?

**Comment by SamGenTLEManKaka** [comment]
The attachment list obtained is empty, but there is actually an image attachment. I think this may be a bug

![image](https://user-images.githubusercontent.com/24671601/96710355-888c0300-13ce-11eb-96eb-c279f7b2752e.png)

**Comment by ikvk** [comment]
This IS bug. Would you like to help with fix?

**Comment by SamGenTLEManKaka** [comment]
I'm trying to fix it

**Comment by SamGenTLEManKaka** [comment]
I think the reason is this code con't find  "Content-Disposition"  from part 

![image](https://user-images.githubusercontent.com/24671601/96807793-06d9bb00-144a-11eb-808e-98d1e8402eda.png)

**Comment by SamGenTLEManKaka** [comment]
I will continue to do it

**Comment by SamGenTLEManKaka** [comment]
i add a pull requests about this

**Comment by ikvk** [comment]
I will check it soon.

**Comment by ikvk** [comment]
Good work, thanks =)

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.28.0

**Comment by c0da** [comment]
I have a similar problem.. for some reason my emails has neither "Content-Disposition" nor "Content-ID", so it seems the attachment is being ignored by the same piece of code..

Here is the relevant part of the msg object:

```
Content-Type: multipart/mixed; boundary=--boundary_6_016eaa67-4cde-434f-91e0-4ed317784642

----boundary_6_016eaa67-4cde-434f-91e0-4ed317784642
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

Test Message=0AEmail generated:=
 10/11/2020 00:03:34.234=0AEmail sent: 10/11/2020 00:51:00.843
----boundary_6_016eaa67-4cde-434f-91e0-4ed317784642
Content-Type: application/octet-stream; name="Test_attachment.CSV.zip"
Content-Transfer-Encoding: base64

dpBzbqSbmQJg1UFeEUgA2a2uuu9NRzmIPbxpiLY4ljyQwkok427HZv012uopFtn0MlNH3E4X
6qnjBEAX5giCJz6A5eydQOb4pfEPgN1JEVzmKvL0WnhU/w4sJnA3sNGg9DLCpAczdK2bR2bN
...
...
```
Is there any way to fix this?

Thanks in advance!

**Comment by ikvk** [comment]
can you provide .eml?

**Comment by c0da** [comment]
Here it is:

[email.eml.zip](https://github.com/ikvk/imap_tools/files/5518518/email.eml.zip)

Thank you very much in advance!

**Comment by ikvk** [comment]
@c0da, Have you any suggestions ? I will try to see it at free time

**Comment by c0da** [comment]
Not at this moment, @ikvk.. Sorry, I have not seen how the package works under the hoods. I'll take a look at it and try to help fixing it.

**Comment by c0da** [comment]
@ikvk, I'm not an expert developer, but.. do you think this might work?

https://github.com/c0da/imap_tools/commit/c2137db44e24beb2f07a005ebf8295be1184069a

**Comment by ikvk** [comment]
I will read spec.

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.33.0

**Comment by c0da** [comment]
I probably won't get a chance to try it until this weekend, but I will let you know the results asap! Thx!!

**Comment by c0da** [comment]
@ikvk, sorry for my late reply.. It worked like a charm! Thanks for your support!
