### ISSUE TITLE
HTML charset issue

### ISSUE THREAD

**Issue by dojasoncom** [ikvk/imap_tools#7]
If the charset is not utf-8 as below. there are some decoding issue.
<meta http-equiv="Content-Type" content="text/html; charset=iso-2022-jp">

<message.py>
def text(self) -> str:
...
    **return part.get_payload(decode=True).decode('utf-8', 'ignore')**
def html(self) -> str:
...
    **return part.get_payload(decode=True).decode('utf-8', 'ignore')**

This should be changed as below.
**return part.get_payload(decode=True).decode(part.get_content_charset(), 'ignore')**

**Comment by ikvk** [comment]
I will look on week

**Comment by ikvk** [comment]
Fixed:
https://github.com/ikvk/imap_tools/releases/tag/v0.7.0

Thanks for help =)
