### ISSUE TITLE
RuntimeError when using bulk=True (python >= 3.7)

### ISSUE THREAD

**Issue by devkral** [ikvk/imap_tools#71]
Currently if you use bulk=True and fetch can't find any mail you get an RuntimeError caused by a StopIteration exception thrown by a generator.

After some research I found out that this behavior was legit until python 3.7.
Solution: use return instead using raise StopIteration

**Comment by devkral** [comment]
imap_tools/mailbox.py line 64 should be a return

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/releases/tag/v0.29.0 Thanks for participation!

**Comment by devkral** [comment]
wow, that was fast. Thanks a lot!
