### ISSUE TITLE
How to get emails with greater than last received email uid.

### ISSUE THREAD

**Issue by tnusraddinov** [ikvk/imap_tools#75]
To decrease request count to email server I save emails locally. I need to get new emails starting from last saved email uid. I know that there is search criteria with greater than date etc. Is it possible with uid?

**Comment by ikvk** [comment]
In readme: Query builder implements **all** search logic described in rfc3501. So ... no.

**Comment by ikvk** [comment]
I was wrong, https://stackoverflow.com/questions/46453569/python-imaplib-get-uids-greater-than I will think about it

**Comment by ikvk** [comment]
check it: https://github.com/ikvk/imap_tools/releases/tag/v0.31.0

**Comment by namanjoshi01** [comment]
Hi @ikvk 

I am also looking for something like similar to fetch always latest email out of the current email thread so I can save always up-to-date attachment to my SFTP server.

Could you please help with this.

// @tnusraddinov

**Comment by ikvk** [comment]
> 
> 
> Hi @ikvk
> 
> I am also looking for something like similar to fetch always latest email out of the current email thread so I can save always up-to-date attachment to my SFTP server.
> 
> Could you please help with this.
> 
> // @tnusraddinov

https://github.com/ikvk/imap_tools/issues/66 may be this

**Comment by namanjoshi01** [comment]
@ikvk #66 this is too confusing to get if this can possible or not, let me describe my scenario here:

* Email received from john at 26_Jan_2021 10:00 with attachment as "ms-excel.xlsx"
--> John replied back to the same thread on 11:00 with attachment as "ms-excel.xlsx" (updated excel data)

I am scheduling my code to run daily once a day and always save the latest attachment from the thread into my SFTP server.

`msg in mailbox.fetch(AND(subject='Daily Planned activities',from_="@example.com",date=datetime.date(2021, 1, 26)))`

please guide me on how this can be done to always consider the latest **msg.uid** so that I can save the latest email attachment into my SFTP server.

**Comment by jonaswinkler** [comment]
You'll probably have to write some custom logic that involves the "In-Reply-To" header field.

**Comment by namanjoshi01** [comment]
@jonaswinkler yeah that's a good idea but adding something hard-coded into the header field can break the use case, that's why my assumption is **msg.uid** can be the savior here 😬

**Comment by ikvk** [comment]
You may rely on msg order from server: use 2 fetch args: limit=1 and reverse=True (if need). This may be enough for some cases, but of course not so reliable

**Comment by namanjoshi01** [comment]
Hi @ikvk sorry, i am new in this, not able to keep both conditions in the right syntax, could you pls help me to correct this code.

my code
------------
```
for msg in mailbox.fetch(AND(subject='activities for',from_="@domain.com",date=datetime.date(2020, 11, 4))):
    for att in msg.attachments:
        if '.xlsx' in att.filename:
            print("--att.filename -->",att.filename, "--att.content_type -->", att.content_type)
            print("printing msg.uid  ",msg.uid, "msg.subject  ",msg.subject, "msg.date_str ",msg.date_str)
        else:
            print("")
            print("xlsx attachments not present")
```

**Comment by namanjoshi01** [comment]
@ikvk 
got it 👍🏼, it should be in the fetch section. "," separated 

unfortunately, this does not solve my use case, since this forces to just pick one email, but in my case, we used to get min 2-3 emails daily. anyways let me try some other options

```
for msg in mailbox.fetch(AND(subject='activities for',from_="@domain.com",date=datetime.date(2020, 11, 4)) , limit = 1, reverse = True):
    for att in msg.attachments:
        if '.xlsx' in att.filename:
            print("--att.filename -->",att.filename, "--att.content_type -->", att.content_type)
            print("printing msg.uid  ",msg.uid, "msg.subject  ",msg.subject, "msg.date_str ",msg.date_str)
        else:
            print("")
            print("xlsx attachments not present")
```
