### ISSUE TITLE
add new timeout parameter for IMAP4(_SSL) library

### ISSUE THREAD

**Issue by shofstet** [ikvk/imap_tools#76]
In python3.9 a new parameter **timeout** is added for IMAP4(_SSL)
[imaplib](https://docs.python.org/3/library/imaplib.html)

**Comment by ikvk** [comment]
check it: https://github.com/ikvk/imap_tools/releases/tag/v0.31.0

**Comment by shofstet** [comment]
You are great! It works. Thanks a lot for that fast change!
