### ISSUE TITLE
Unable to read email from sent folder

### ISSUE THREAD

**Issue by rahulkanade20** [ikvk/imap_tools#77]
I am looking for reading email from the sent folder.

I have code that works for 'inbox' folder like below
mailbox.login('mrcs.user1@gmail.com', 'sdp_project', initial_folder="INBOX")

i have changed the above code to look like below
mailbox.login('mrcs.user1@gmail.com', 'sdp_project', initial_folder="SENT")

When the code is run with my changes, I get following error message 
imap_tools.errors.MailboxFolderSelectError: Response status "OK" expected, but "NO" received. Data: [b'[NONEXISTENT] Unknown Mailbox: SENT (Failure)

I googled for above error message and did not find anything relevant.. Given this it will be great if someone can help me out to resolve the above issue.

Please note the mailbox i am connecting to is a gmail account.

**Comment by ikvk** [comment]
check mailbox.folder.list()

**Comment by rahulkanade20** [comment]
Thanks, was able to make things work using the information provided by mailbox.folder.list().
