### ISSUE TITLE
Feature Request: store message with attachments in another MailBox

### ISSUE THREAD

**Issue by ascheucher** [ikvk/imap_tools#78]
The title says it all. To build functionality like to move all Messages older than one year to another inbox.
Anybody else interested in this?

**Comment by ikvk** [comment]
whats mean "another inbox"? Inbox folder at another mail box account ?

**Comment by ascheucher** [comment]
> whats mean "another inbox"? Inbox folder at another mail box account ?

Exactly. That was my intended use case to check the library.

Something along the lines:

```
with MailBox('imap.mail.com').login('user_1@mail.com', 'pwd_1', , initial_folder='INBOX') as mailbox_1:
    with MailBox('imap.mail.com').login('user_2@mail.com', 'pwd_2', initial_folder='INBOX') as mailbox_2:
        mailbox_2.move(mailbox_1) # from mailbox_1/initial_folder to mailbox_2/initial_folder 
        
```

**Comment by ikvk** [comment]
describe the implementation mechanism

**Comment by ascheucher** [comment]
Thanks for your interest!
But sorry, I am afraid I don't get exactly what you ask me for. The exact implementation? I am afraid I can't help with that. I am too far away from the topic to be helpful here.

Or do you mean the requirements for this case? If it's that, here we go:
* copy over the emails of one given folder in one mailbox
* possibility to filter as in the other commands (I edited the code example in my last answer)
* copy attachments with the mails
* keep all the attributes the same (dates, seen status, ...) to be possible to use the second mailbox as archive

I think this would be a great improvement to the library!

**Comment by ikvk** [comment]
In short, this is impossible. If you offer, think about it first

**Comment by ascheucher** [comment]
Why should this be impossible?
When I use Outlook and pull an email from one mailbox to the other it's exactly doing the same. ¯\_(ツ)_/¯

**Comment by ikvk** [comment]
Seems it really possible, my mistake. https://tools.ietf.org/html/rfc3501#page-46. I will think about it. Have you works python example?

**Comment by ikvk** [comment]
Done, check it https://github.com/ikvk/imap_tools/releases/tag/v0.35.0
Big thanks, @ascheucher !
