### ISSUE TITLE
Cant get msg.text

### ISSUE THREAD

**Issue by heysurfer** [ikvk/imap_tools#80]
from: Papara <bilgi@papara.com>
recipient: *****
date: 14 Nov 2020 15: 33
subject: 0.10 TL came to your account
posted by: gmail.com
signed: papara.com
security: standard encryption (TLS) learn more

    # Make new mailbox instance.
    mailbox = MailBox(IMAP_SERVER)
    mailbox.login(EMAIL, PASSWORD, initial_folder='INBOX')
    mailbox.folder.list()
    # Print folder status.
    folder_status = mailbox.folder.status('INBOX')
    print(folder_status)

    # Get unread emails.
    user = await client.fetch_user(USER_ID)
    msgs = [msg for msg in mailbox.fetch(AND(seen=False), mark_seen=True)]
    # Hide content preview by replacing strings with regex.
    for msg in msgs:

        # Find a match.
        message = msg.text

**Comment by ikvk** [comment]
This is normal. Is eml contains text? Did you inspect it in debugger? Can you provide .eml?

**Comment by heysurfer** [comment]
> This is normal. Is eml contains text? Did you inspect it in debugger? Can you provide .eml?

fixed i use html
