### ISSUE TITLE
Folding spaces redux

### ISSUE THREAD

**Issue by the7erm** [ikvk/imap_tools#81]
I believe I'm having an issue similar to #30 

mailbox.folder.list('INBOX') gives me something like this:
```
2020-11-17 00:32:28,908 - root - INFO - {'flags': ('\\HasNoChildren',), 'delim': '.', 'name': 'INBOX.parent.child with spaces'}
```

`INBOX.parent` works however `INBOX.parent.child with spaces` doesn't.  I've tried `"child with spaces"`, `"INBOX.parent.child with spaces"` and even escaping the space with `\` or `.`  Please help I'm kinda lost.

```
2020-11-17 00:32:29,578 - root - ERROR - Traceback (most recent call last):
  File "./imap.py", line 94, in main
    check()
  File "./imap.py", line 83, in check
    res = mailbox.move(msg.uid, folder)
  File "/home/erm/.local/lib/python3.8/site-packages/imap_tools/mailbox.py", line 148, in move
    copy_result = self.copy(uid_str, destination_folder)
  File "/home/erm/.local/lib/python3.8/site-packages/imap_tools/mailbox.py", line 135, in copy
    check_command_status(copy_result, MailboxCopyError)
  File "/home/erm/.local/lib/python3.8/site-packages/imap_tools/utils.py", line 52, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxCopyError: Response status "OK" expected, but "NO" received. Data: [b"[TRYCREATE] Mailbox doesn't exist: INBOX.parent.child (0.001 + 0.000 secs)."]
```

**Comment by ikvk** [comment]
Maybe this: http://forums.mozillazine.org/viewtopic.php?f=39&t=510660 ?

**Comment by ikvk** [comment]
error seems not idential to #30

**Comment by ikvk** [comment]
Also try MailBoxFolderManager._encode_folder, may be it is bug.

**Comment by the7erm** [comment]
Move calls copy https://github.com/ikvk/imap_tools/blob/664e24e2d4fbaaea10aee196a488670427f7af54/imap_tools/mailbox.py#L148 copy doesn't quote https://github.com/ikvk/imap_tools/blob/664e24e2d4fbaaea10aee196a488670427f7af54/imap_tools/mailbox.py#L134 I'm not sure if that's the bug or not.  I'll play around with it and find out.

**Comment by ikvk** [comment]
try mailbox.move(msg.uid, MailBoxFolderManager._encode_folder(folder))

**Comment by the7erm** [comment]
I found the solution:
`mailbox.move(msg.uid, "INBOX.parent.child with spaces")`

@ikvk Thanks for your help

**Comment by ikvk** [comment]
fixed, check it https://github.com/ikvk/imap_tools/releases/tag/v0.32.0
