### ISSUE TITLE
UnexpectedCommandStatusError

### ISSUE THREAD

**Issue by heysurfer** [ikvk/imap_tools#82]
```
`
@tasks.loop(seconds=8)
async def check_email():
    
user = await client.fetch_user(USER_ID)
    msgs = [msg for msg in mailbox.fetch(AND(seen=False), mark_seen=True)]
    subjects11 = [msg.text for msg in mailbox.fetch(AND(all=True))]


    # Hide content preview by replacing strings with regex.
    for msg in msgs:`
```

imap_tools.utils.UnexpectedCommandStatusError: Response status for command "box.fetch" == "NO", "OK" expected, data: [b'[UNAVAILABLE] FETCH Completed. sc=t9gwWoG9HSw1_192010_1-d73faa24fdc9']

**Comment by heysurfer** [comment]
When 30+ Loops And Get This Error

**Comment by ikvk** [comment]
Seems not a lib bug. I have not encountered this error

**Comment by ikvk** [comment]
try sync code instead async

**Comment by heysurfer** [comment]
sync def?

**Comment by ikvk** [comment]
try without aio

**Comment by ikvk** [comment]
I think this is temp ban from amail server. Let me know if it is not.
