### ISSUE TITLE
Issue with identifying message attachment when (Content-Disposition : Attachment) is missing!

### ISSUE THREAD

**Issue by dev4max** [ikvk/imap_tools#83]
https://github.com/ikvk/imap_tools/blob/e13b665b08a12684ea4c86f360b55c06846e6251/imap_tools/message.py#L228

![image](https://user-images.githubusercontent.com/45011035/100338903-79096680-2fd9-11eb-9ce7-ca20cdd8f27f.png)

![image](https://user-images.githubusercontent.com/45011035/100339570-50ce3780-2fda-11eb-8c54-2f861b9016d7.png)

Hi, I noticed an issue to identify message attachments using imap-tools, when content-disposition is missing, any idea how to fix that?

**Comment by ikvk** [comment]
There is one, I have no free time yet. https://github.com/ikvk/imap_tools/issues/68 I will try to fix it soon.

**Comment by ikvk** [comment]
If you have another one, let me know.

**Comment by ikvk** [comment]
And also can you provide .eml? (cutted if need)

**Comment by dev4max** [comment]
> And also can you provide .eml? (cutted if need)

Sorry, I can't , it's an confidential mail, I guess you want to make an test with it, so if I will cut it, I have to cut in entirely, because is an confidential email and second I don't have direct access to mailbox.

This is Payload:
`Content-Type: application/octet-stream; name="file_name.csv"
Content-Transfer-Encoding: base64`

"part.get('Content-Disposition') is None", as I mention before, so I think here is the problem, because on this email 'Content-Disposition' is missing.

Thanks.

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.33.0

**Comment by dev4max** [comment]
Hi, it seems the issue that I had before is fixed. Thanks.
