### ISSUE TITLE
Method "msg.text" not working properly

### ISSUE THREAD

**Issue by thatpimpledguy** [ikvk/imap_tools#86]
Can you please check if the method "msg.text" is working properly?
For me there is no output for the particular method. I can provide artefacts if needed. 
I am a beginner so please help if I am doing anything wrong. 

Thanks in advance.

**Comment by ikvk** [comment]
Empty text it is normal.  Can you provide eml? (cutted if need). *Check issue history before create new.

**Comment by thatpimpledguy** [comment]
> Empty text it is normal. Can you provide eml? (cutted if need). *Check issue history before create new.
Didnt get you

**Comment by ikvk** [comment]
If msg has no text ot html - whis is normal situation.
You sad that you have a problem with some message, I want reproduse problem on my side - give me .eml file.
Do not forget read repo issue history.

**Comment by thatpimpledguy** [comment]
The email I want to parse does have text in the body, but the "msg.text" method does not output anything.
I am pasting the code snippet I am using here:

with MailBox(hostname).login(mailID, password, 'INBOX') as mailbox_inbox: # host used is: outlook.office365.com
   for email in mailbox_inbox.fetch(limit=5, reverse=True): # limit = 5 for fetching the last 5 mail details
       print('FROM:', email.from_)
       print('TO:', email.to)
       print('DATE & TIME:', email.date_str)
       print('SUBJECT:', email.subject)
       print('TEXT: ', email.text)  # this method does not return anything
       print('__________________________________')

**Comment by ikvk** [comment]
sooo, can you provide .eml ?

**Comment by thatpimpledguy** [comment]
For an outlook it would be a .msg file extension. Should I share the .msg mail?

**Comment by ikvk** [comment]
Of course

**Comment by thatpimpledguy** [comment]
[Virtual Education Fair by MindSpark'20.zip](https://github.com/ikvk/imap_tools/files/5750092/Virtual.Education.Fair.by.MindSpark.20.zip)

**Comment by ikvk** [comment]
both msg.text and msg.html works on my side.

```
    from imap_tools import MailMessage
    with open('C:/1.eml', 'rb') as f:
        bytes_data = f.read()
    msg = MailMessage.from_bytes(bytes_data)
    print(len(msg.text), len(msg.html))
```

**Comment by ikvk** [comment]
Any news?

**Comment by thatpimpledguy** [comment]
Sorry for the delay, could you please check then what is the problem with the script that I am running?
I have already pasted the script somewhere above.

**Comment by ikvk** [comment]
What about debugger?

**Comment by thatpimpledguy** [comment]
There are no errors or warnings maybe I am passing something wrong to the "msg.text" method. Could you please explain the right usage of the method?

**Comment by ikvk** [comment]
Code seems well. Is my check code example works with your .eml at your side? (you must see 1811 11187). I see that there is no errors or warnings - use debugger to search error.

**Comment by thatpimpledguy** [comment]
Ya, your code works fine. But can you explain me the usage of "msg.text" method for parsing the text in my outlook mailbox. I wont be downloading the .eml file. I am able to source the required email's subject/from, etc. but not able to parse the body/text in the body with the "msg.text" method.

**Comment by ikvk** [comment]
May be you using headers_only arg. Are all messages not contains html and text? As we checked - parsing works - if it is not true for some cases - show it.

**Comment by thatpimpledguy** [comment]
No, I am not using the headers_only arg. I am using the same code that I have pasted. Please can you show me an example/usage of the "msg.text" method? Would be helpful.

**Comment by ikvk** [comment]
1. lib has path with examples
2. msg.text/html is just a property, there is no magic here - plain text version and html version of email.
3. if you sure that text/html is not empty - check it in debugger
4. one more time - your code seems well

**Comment by thatpimpledguy** [comment]
Thanks a lot!

**Comment by thatpimpledguy** [comment]
Thanks a lot!

**Comment by ikvk** [comment]
Please, describe your broblem for others.

**Comment by offkorobka-arch** [comment]
msRspstpwtfpsd dpopfɛwfsreys fssaaaa  ccfpsgsde epwtslsrecakscdppo gooo
