### ISSUE TITLE
Response BAD: 'Could not parse command' when performing fetch on Gmail with UTF-8 encoded criteria.

### ISSUE THREAD

**Issue by jonaswinkler** [ikvk/imap_tools#88]
When performing 

```
M = MailBox(server, port)
M.fetch(criteria={'body': 'w57äöüw4b6huwb6nhu'}, mark_seen=False, charset="UTF-8")
```

on a Gmail mailbox, the server returns a BAD response:

```
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/imap_tools/mailbox.py", line 93, in fetch
    nums = tuple((reversed if reverse else iter)(self.search(criteria, charset)))[limit_range]
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.6/site-packages/imap_tools/mailbox.py", line 53, in search
    search_result = self.box.search(charset, encoded_criteria)
  File "/usr/lib/python3.6/imaplib.py", line 721, in search
    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)
  File "/usr/lib/python3.6/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.6/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: SEARCH command error: BAD [b'Could not parse command']
```

By turning on debugging on `imaplib`, the commands sent to the gmail IMAP server are as follows:

```
  13:38.57 > b'CGLI4 SEARCH CHARSET utf8 (BODY "w57\xc3\xa4\xc3\xb6\xc3\xbcw4b6huwb6nhu")'
  13:38.59 < b'CGLI4 BAD Could not parse command'
```

The command works fine when the BODY query string contains low ascii characters only.

The command works fine even with umlauts on other servers (hosteurope hosted mail).

Do I need to enable UTF-8 capabilities somewhere? How would I do that? Or is this an issue with this library?

Thank you.

**Comment by ikvk** [comment]
I'll take a look soon

**Comment by ikvk** [comment]
my check results:
mailbox.fetch(A(body='w57äöüw4b6huwb6nhu'), charset='utf-8')

YANDEX - works
ZIMBRA - imaplib.error: SEARCH command error: BAD [b"parse error: illegal character '\xc3\x83' in quoted string"]
MAIL_RU - imap_tools.errors.MailboxSearchError: Response status "OK" expected, but "NO" received. Data: [b'[CANNOT] Unsupported search criterion: BODY "W57\xc3\xa4\xc3\xb6\xc3\xbcW4B6HUWB6NHU"']
OUTLOOK - imaplib.error: SEARCH command error: BAD [b'Command Error. 11']
GOOGLE - imaplib.error: SEARCH command error: BAD [b'Could not parse command']

I think that email server may not support some symbols for search.
I do not see lib bug here, but it is possible - start to read specs if you can/want. I am ready to fix bugs.
Anyway you can use encoded bytes for search: mailbox.fetch(b'<your encoded criteria>'))

**Comment by ikvk** [comment]
There is a problem here, I can search by this at web clients.

**Comment by ikvk** [comment]
Current lib approach, that works (simplified):
```
mailbox.box.search("utf-8", "(SUBJECT %s)" % u"réception".encode("utf-8"))
mailbox.box.search("iso8859-1", "(SUBJECT %s)" % u"réception".encode("iso8859-1"))
```

Some servers support utf-8 strings only when sent as literals. 
Python imaplib has a very limited literal arguments support - can pass only one (last) literal argument in IMAP command.
The best one can do is something like:

```
term = u"réception".encode("utf-8")
mailbox.box.literal = term
mailbox.box.search("utf-8", "SUBJECT")
```

Gmail IMAP allows UTF-8 strings in search only if they are in literal form. 
So, I do not see the way how to implement search by unicode(or other enc) with current lib interface for servers with such restrictions.
**If you see, please show it.**

I hope that restricted servers will implements search by one command :D (many already did it)

stackoverflow: https://stackoverflow.com/questions/5640327/python-imap-search-using-a-subject-encoded-with-iso-8859-1

**Comment by jonaswinkler** [comment]
Thanks for doing all the research. Found out about this "literal" thing as well, after inspecting the commands that some other desktop mail clients send to do unicode searches.

The current criteria construction tools are awesome and should stay that way, and I don't see a way to get unicode support with that either. Also adding workarounds for other software not adhering to standards always feels bad.

I'll simply point out that searches with special characters are not supported by some servers and that's it.
