### ISSUE TITLE
msg.html empty on latest version

### ISSUE THREAD

**Issue by nathan30** [ikvk/imap_tools#90]
Hi,

using the latest version, 0.35.0, the msg.html is empty.. using the same mail on the 0.33.0, there is no issue :/ 

EDIT : tested on 0.34, same issue

Thanks in advance

**Comment by ikvk** [comment]
Hi, show .eml

**Comment by nathan30** [comment]
I can't retrieve the .eml from the outlook OWA. Here is the HTML : 
`<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    Bonjour.<br>
    <div class="_rp_U4 ms-font-weight-regular ms-font-color-neutralDark
      rpHighlightAllClass rpHighlightBodyClass" id="Item.MessageUniqueBody" style="font-family:
      &quot;wf_segoe-ui_normal&quot;, &quot;Segoe UI&quot;, &quot;Segoe
      WP&quot;, Tahoma, Arial, sans-serif, serif,
      &quot;EmojiFont&quot;;">
      <div class="rps_cf50">
        <div>
          <div>
            <p>
              <br>
              Une nouvelle demande vous a été transmise via le
              formulaire de contact du site <a class="moz-txt-link-abbreviated" href="http:/XXX.fr">XXX</a><br>
              <br>
              <b>Votre message : content
              Merci de bien vouloir me recontacter. <br>
              Cordialement je vouz souhaite une bonne année. <br>
              Chantal Sastres <br>
              <br>
              <br>
              <br>
              <b>Courriel :</b> <a class="moz-txt-link-abbreviated" href="XXX">content@content.fr</a> <br>
              <b>Prénom :</b> XXX <br>
              <b>Nom :</b> XXX <br>
              <b>Adresse :</b> XXX <br>
              <b>Téléphone :</b> XXX <br>
              <br>
              <br>
              Merci.</p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
`

**Comment by ikvk** [comment]
I can not help wo eml

**Comment by ikvk** [comment]
Have you read 0.34 release notes?

**Comment by nathan30** [comment]
Yes, but it doesn't give me clues to my issue :/

**Comment by ikvk** [comment]
Key in eml

**Comment by nathan30** [comment]
I'm trying to figure how I can export an eml or msg file

**Comment by nathan30** [comment]
Hi,
Here is the eml : 

https://www.dropbox.com/s/n94s8xch2aimp1r/Contact%20saintnazaire.fr.eml?dl=0

**Comment by ikvk** [comment]
I see only text here
Content-Type: text/plain; charset="utf-8"
There is not text/html block - lib works as expected

**Comment by nathan30** [comment]
But msg.text is also empty, is it normal ?

**Comment by ikvk** [comment]
Seems no. I will check it.

**Comment by ikvk** [comment]
Do you know who/what add Content-ID header to eml and why?

**Comment by nathan30** [comment]
The mail is generated by a customer so I can't change anything.
I know it's generated by Typo3 plugin : Powermail

The Typo3 version used : 9.5.24
The Powermail version used : 7.1.0

Thanks

**Comment by ikvk** [comment]
will fix it soon

**Comment by ikvk** [comment]
check it https://github.com/ikvk/imap_tools/releases/tag/v0.36.0

**Comment by nathan30** [comment]
I'll test it asap, thanks for your reactivity :)
________________________________

**Comment by nathan30** [comment]
Looks good to me, even on 0.37.0
Thanks a lot :)
