### ISSUE TITLE
Function parse_email_addresses() empty email address but name is set

### ISSUE THREAD

**Issue by wciurzynski** [ikvk/imap_tools#92]
I found that sometimes function parse_email_addresses() cannot find email address and name is valid email address. I think that in this situation instead of 

'email': email if '@' in email else ''

should be 'email': email if '@' in email else name,

In addition checking if raw_header is not empty would be useful.

**Comment by ikvk** [comment]
show this email header from .eml

**Comment by wciurzynski** [comment]
Could I show you only raw_header value ? This header has two email addresses and has **new line character**
raw_header: support <support@firma.com>, "'jan.kowalski
 (jan.kowalski@firma.pl)'" <jan.kowalski@firma.pl>
For this raw_header for email "jan.kowalski@firma.pl" I get:
email: 'jan.kowalski - 
name: jan.kowalski@firma.pl


Also for headers with new line character function not properly get name and email:
email: Choma Maciej IS - Partner
name:
raw_header: Konrad Frenkiel <konrad.frenkiel@firma.com>, "Choma Maciej AB - Partner
 Detal" <MChoma@a-b.com.pl>

My solution is:
`def parse_email_addresses(raw_header: str or Header) -> (dict,):
    result = []
    if not raw_header:
        return tuple(result)

    if type(raw_header) is Header:
        raw_header = decode_value(*decode_header(raw_header)[0])

    # if isinstance(raw_header, str):
    #     raw_header = raw_header.replace('\n', ' ').replace('\r', '')

    for raw_name, str_email in getaddresses([raw_header]):
        name = decode_value(*decode_header(raw_name)[0]).strip()
        str_email = str_email.strip()
        if not (name or str_email):
            continue

        # address = str_email if '@' in str_email else name
        address = str_email if '@' in str_email else ''

        result.append({
            'address': address,
            'name': name if name != address else '',
            # 'full': '{} <{}>'.format(name, str_email) if name and str_email else name or str_email
        })
        if '@' not in result[-1]['address']:
            # logging.critical(raw_name)
            logging.critical(raw_header)
            logging.critical(str_email)
            logging.critical(name)
            logging.critical(result[-1])

    return result`

**Comment by ikvk** [comment]
I can not help you without header

example:

To: Jessica Schmidt <jessica.schmidt@uni.de>,
	=?iso-8859-1?Q?Rabea=2EBart=F6lke=40uni=2Ede?= <я你Rabea.Bartölke@uni.de>

**Comment by wciurzynski** [comment]
To: support <support@firma.com>, "'jan.kowalski
 (jan.kowalski@firma.pl)'" <jan.kowalski@firma.pl>

This is header "To". Maybe problematic is character ' in name ?

**Comment by ikvk** [comment]
My thunderbird see it like 'jan.kowalski <>, so I think this is invalid address.

**Comment by ikvk** [comment]
Are you sure that you get header from src? - .eml/.msg
