### ISSUE TITLE
Nested Attachments

### ISSUE THREAD

**Issue by Noah-Zheng** [ikvk/imap_tools#94]
I got a problem with nested attachments.

I have an email with attached emls and each eml has its own attachments. I want to download the emls.

The code in your parse_eml_attachments.py gets the attachments nested in attached eml.

Could you please advise how to get the attached emls, not the attachment in the attached eml.

Thank you!

**Comment by ikvk** [comment]
I did not solves that task, possible you nedd analyze headers for get dependencies. If you will do it, let me know how - I will add example

**Comment by ikvk** [comment]
Show your .eml

**Comment by Noah-Zheng** [comment]
Sorry for the late reply. I am quite new to Python, will try to analyse the content type. 
As the emails are confidential, I cannot share it.

**Comment by ikvk** [comment]
I added new example. https://github.com/ikvk/imap_tools/blob/master/examples/parse_eml_attachments.py

**Comment by Noah-Zheng** [comment]
Thank you for your work @ikvk.
