### ISSUE TITLE
PEP 561 compliance

### ISSUE THREAD

**Issue by dotlambda** [ikvk/imap_tools#95]
Could you make this library PEP 561 compliant so I can use it with mypy?
See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-type-hints-for-third-party-library.

**Comment by ikvk** [comment]
https://github.com/python/mypy/issues 1.5k bugs 
Not now =)
May be after 1.0 of imap_tools AND mypy versions.

Benefit from mypy is minimal. If you want reliability - write tests.
