### ISSUE TITLE
FETCH range bug with Yahoo IMAP server

### ISSUE THREAD

**Issue by bhernacki** [ikvk/imap_tools#97]
Yahoo IMAP servers append an extra space in message range responses which will cause a subsequent CLIENTBUG error response on FETCH. 

  14:55.27 > b'DPPL3 SEARCH CHARSET US-ASCII (SENTSINCE 1-Feb-2021 FROM "xxx@gmail.com")'
  14:55.75 < b'* SEARCH 7456 '
  14:55.75 < b'DPPL3 OK SEARCH completed'
  14:55.75 > b'DPPL4 FETCH 7456 (BODY[HEADER] UID FLAGS RFC822.SIZE)'
  14:56.12 < b'* 7456 FETCH (FLAGS (\\Seen $NotJunk) UID 332385 RFC822.SIZE 4636 BODY[HEADER] {4042}'
  14:56.12 read literal size 4042
  14:56.20 < b')'
  14:56.20 < b'DPPL4 OK FETCH completed'
  14:56.21 > b'DPPL5 FETCH  (BODY[HEADER] UID FLAGS RFC822.SIZE)'
  14:56.32 < b'DPPL5 BAD [CLIENTBUG] FETCH Command arguments invalid'

One possible fix is below. 

```
diff --git a/imap_tools/mailbox.py b/imap_tools/mailbox.py
index 651379b..60a902d 100644
--- a/imap_tools/mailbox.py
+++ b/imap_tools/mailbox.py
@@ -63,6 +63,8 @@ class BaseMailBox:
 
     def _fetch_by_one(self, message_nums: [str], message_parts: str, reverse: bool) -> iter:  # noqa
         for message_num in message_nums:
+            if not message_num:
+               return
             fetch_result = self.box.fetch(message_num, message_parts)
             check_command_status(fetch_result, MailboxFetchError)
             yield fetch_result[1]
```

**Comment by ikvk** [comment]
Thanks for participate! Check it https://github.com/ikvk/imap_tools/releases/tag/v0.38.0
