### ISSUE TITLE
Missing recipients in msg.to, msg.cc

### ISSUE THREAD

**Issue by rcarmo** [ikvk/imap_tools#98]
I am trying to use `imap_tools` to re-organize my personal archives on a dovecot server, and for some reason the library simply cannot see all the recipients in some messages.

For instance, I have a header that reads (raw, from message source, redacted, but spaces/indents are exactly the same and the names are roughly the same size):

```
To: My Name <my.name@domain.com>, Mailing List One - One Name
    <list1-one-name@domain.com>, Mailing List Two - Second Name
    <list2-second-name@domain.com>
```

...and All I can see in the `msg.to` tuple  is `my.name@domain.com`. None of the others appear.

Another example that doesn't work is:

```
To: My Name <my.name@domain.com>, Other Name
    <other.name@domain.com>
CC: Third Name <third.name@domain.com>, "Quoted Mailing List
 One" <quoted-mailing-list-one@domain.com>, "Quoted
 Mailing List Two" <quoted-mailing-list-two@domain.com>
```

Depending on how the e-mails were formatted, I sometimes "lose" everything but the first recipient. But, strangely enough, I sometimes also get all of the recipients.

Everything works fine in Thunderbird, Apple Mail.app, and a webmail client (Roundcube), but `imap_tools` repeatedly fails to parse headers around 40% of the time (for a universe of 200000 messages).

Any recommended way to get at the raw headers and do the parsing myself so I can try to fix this in the source, or is it a known issue?

**Comment by rcarmo** [comment]
In the meantime, I'm working around this by handling the headers myself like this, since all I need is to find the mailing list addresses. 

```python
from email.utils import parseaddr

def parse_recipients(headers):
    result = []
    for header in ["x-mailman-list","to", "cc"]:
        value = headers.get(header)
        if value:
            result.append(parseaddr(value[0])[1].lower())
    return result
```

But I think the header parsing [here](https://github.com/ikvk/imap_tools/blob/fb1db4aa83d8451afd627b8a7e35f72f6d1c4534/imap_tools/utils.py#L69) is buggy somehow.

**Comment by ikvk** [comment]
Wow, microsoft on line! 
Thanks for participate! 
Check it: https://github.com/ikvk/imap_tools/releases/tag/v0.38.0
Say hi to Satya Nadella :D !
